# -*- coding: utf-8 -*-
# 4장: 루틴 (달력 → 데이터 → 카드 → 추가 폼 → 반복 규칙 → 템플릿 → 오늘 할 일 → 상세)

CONCEPTS_CH = {
    "late": ("late 변수", "<code>late DateTime _selectedDate;</code>는 \"지금은 값이 없지만 <b>쓰기 전에는 반드시 채우겠다</b>\"는 약속입니다. null을 허용하는 <code>DateTime?</code>과 달리 쓸 때마다 null 검사를 안 해도 됩니다. 값을 <code>initState</code>에서 채우거나, <code>late final x = ...;</code>처럼 <b>처음 쓰는 순간에</b> 계산되게 할 수도 있습니다(widget 값을 쓰는 초기값에 유용합니다)."),
    "family": ("Provider.family (인자를 받는 provider)", "<code>Provider.family&lt;결과, 인자&gt;</code>는 \"인자마다 따로 만들어지는 provider\"입니다. <code>ref.watch(routinesForDateProvider(날짜))</code>처럼 인자를 붙여 쓰며, 같은 인자면 같은 결과를 캐싱해서 돌려줍니다. 날짜별 목록, id별 루틴 하나처럼 <b>\"무엇에 대한\"</b>이 필요한 데이터에 씁니다."),
    "switchexpr": ("switch 식 (=>)", "<code>switch (값) { 'A' =&gt; 결과1, 'B' =&gt; 결과2, _ =&gt; 나머지 }</code>는 값에 따라 <b>결과를 돌려주는 식</b>입니다(<code>_</code>는 \"그 외 전부\"). 위젯 목록 안에서 \"탭에 따라 다른 위젯\"을 고를 때 깔끔합니다. 옛 형태의 <code>switch (x) { case 'A': ...; return ...; }</code> 문장도 같이 쓰입니다."),
    "spread": ("[...목록, 새원소] 와 ..", "<code>[..._steps, text]</code>는 \"<code>_steps</code>의 모든 원소를 펼치고 뒤에 <code>text</code>를 붙인 <b>새 리스트</b>\"입니다. 기존 리스트를 직접 고치지 않고 새로 만들어 대입하면 상태 변경이 안전합니다. <code>[..._steps]..removeAt(i)</code>의 <code>..</code>(캐스케이드)는 \"앞의 값에 이 동작을 한 뒤 그 값 자신을 돌려줘라\"입니다."),
    "setmap": ("Set 과 {키: 값} 컬렉션", "<code>Set&lt;String&gt;</code>은 <b>중복 없는 모음</b>입니다(<code>{'지예', '예담'}</code>). <code>contains</code>, <code>add</code>, <code>remove</code>로 \"선택됐나/선택/해제\"를 표현하기 좋습니다. <code>Map&lt;String, X&gt;</code>은 키로 값을 찾는 사전이고, <code>{ for (final p in 목록) p.name: p }</code>처럼 반복으로 사전을 만들 수도 있습니다."),
    "pickers": ("showTimePicker / showDatePicker", "시간·날짜를 고르는 <b>표준 팝업</b>을 띄우는 함수입니다. <code>await showTimePicker(...)</code>가 사용자가 고른 값을 돌려주고, 팝업을 그냥 닫으면 <code>null</code>이 옵니다. 그래서 <code>if (picked == null) return;</code>로 취소를 처리합니다."),
    "listview": ("ListView.separated", "항목이 많은 목록을 <b>화면에 보이는 것만</b> 만들어 효율적으로 그리는 스크롤 목록입니다. <code>itemCount</code>(몇 개), <code>itemBuilder</code>(i번째 항목 위젯을 만드는 함수), <code>separatorBuilder</code>(항목 사이 간격 위젯)를 줍니다. <code>(_, _) =&gt; ...</code>의 밑줄은 \"쓰지 않는 인자\"입니다."),
    "painter": ("CustomPaint 와 Canvas", "기본 위젯으로 못 그리는 모양은 <code>CustomPainter</code>를 만들어 <code>paint(Canvas, Size)</code> 안에서 선·원·호를 직접 그립니다. <code>Paint()</code>에 색과 굵기를 정하고 <code>canvas.drawCircle</code>, <code>canvas.drawArc</code> 같은 함수로 그립니다. <code>shouldRepaint</code>는 \"값이 바뀌었을 때만 다시 그려라\"를 알려줍니다."),
    "recordtype": ("레코드 ({a, b})와 typedef", "<code>({int childId, DateTime from, DateTime to})</code>처럼 괄호 안에 이름 붙은 값 여럿을 묶으면 <b>레코드</b>입니다. 클래스를 만들 필요 없이 값 묶음을 만들 수 있고, <b>값이 같으면 같은 것으로 비교</b>됩니다(그래서 provider family의 조회 키로 쓰기 좋습니다). <code>typedef 이름 = 타입;</code>은 긴 타입에 짧은 이름을 붙입니다. 꺼낼 때는 <code>query.childId</code>처럼 이름으로 씁니다."),
    "enum": ("enum", "정해진 값 몇 개 중 하나만 가능한 타입입니다(<code>enum RepeatType { range, weekly, dates }</code>). 값마다 <code>const RepeatType(this.code)</code>처럼 데이터를 달아 둘 수 있어서, 화면 이름과 서버로 보낼 글자를 한 곳에 묶을 수 있습니다."),
    "valuechanged": ("ValueChanged&lt;T&gt; 와 제네릭 위젯", "<code>ValueChanged&lt;int&gt;</code>는 \"int를 받는 함수\"의 타입 이름입니다. 부모가 <code>onMonthChanged: (v) =&gt; setState(() =&gt; _repeatMonth = v)</code>처럼 <b>\"값이 바뀌면 이렇게 해라\"</b>를 넘기고, 자식은 선택이 바뀔 때 그 함수를 부릅니다. 위젯 이름 뒤의 <code>&lt;T&gt;</code>(예: <code>_Dropdown&lt;T&gt;</code>)는 \"어떤 타입이든 쓰는 위젯\"이라는 뜻입니다."),
}

STOPS_CH = []

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_screen.dart",
    title="루틴 탭: 달력과 그날의 카드",
    role="루틴 탭 (/routine)",
    arrive="하단 탭바 두 번째 아이콘 → <code>bottom_nav_bar.dart</code> 38줄 <code>context.go('/routine')</code> → <code>router.dart</code> 91줄 <code>RoutineScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 10, "하단 탭바, <b>자녀 선택 칩</b>(<code>child_selector.dart</code>), 루틴 provider, \"+\" 버튼, 루틴 카드 목록 위젯.", []),
        (12, 27, "문서 주석. 진짜 달력 + 선택한 날짜의 루틴 카드 + \"+\" 버튼 구성이고, 카드는 하드코딩이 아니라 <b>서버에서 받은 현재 자녀의 루틴</b>이라는 점, 그리고 목록 맨 아래를 더 당기면(overscroll) \"오늘 할 일\" 화면으로 넘어간다는 동작이 적혀 있습니다.", []),
        (28, 33, "<b>달력 월과 선택 날짜가 바뀌므로 Stateful.</b> <code>ref</code>도 필요해서 <code>ConsumerStatefulWidget</code>입니다.", ["stateful"]),
        (35, 36, "State 클래스와 배경색.", []),
        (38, 43, "<b>화면이 들고 있는 값 둘.</b> <code>_displayedMonth</code>(지금 달력에 펼친 달, 일은 항상 1)와 <code>_selectedDate</code>(눌러서 고른 날). <code>late</code>는 선언할 때 값이 없고 아래 <code>initState</code>에서 채운다는 약속입니다.", ["late"]),
        (45, 52, "<b>화면이 처음 생길 때 한 번.</b> 오늘 날짜로 두 값을 정합니다. <code>DateTime(년, 월, 일)</code>로 시·분·초를 0으로 맞춥니다(<code>super.initState()</code>를 먼저 부르는 것이 규칙).", ["stateful"]),
        (54, 62, "<b>달력 칸을 눌렀을 때.</b> <code>setState</code>로 선택 날짜를 바꾸고, 다른 달의 칸을 눌렀다면 보여주는 달도 그 날짜의 달로 맞춥니다.", []),
        (64, 72, "<b>달 넘기기.</b> <code>_shiftMonth(-1)</code>은 이전 달. <code>DateTime(년, 월 + delta)</code>에서 월이 0이나 13이어도 Dart가 알아서 이전·다음 해로 넘겨 줍니다.", []),
        (74, 77, "맨 아래를 넘어 <b>60픽셀</b> 더 당기면 \"오늘 할 일\"로 넘어갑니다. 너무 작으면 실수로 넘어가고, 너무 크면 반응이 없는 느낌이라는 설명입니다.", ["const"]),
        (79, 96, "<b>중복 이동을 막는 깃발.</b> 긴 주석의 요지: 한 번 드래그하는 동안 스크롤 알림이 여러 번 오기 때문에, 깃발이 없으면 <code>push</code>가 겹쳐 호출돼 \"오늘 할 일\" 화면이 여러 겹 쌓입니다. <code>push</code>가 돌려주는 Future가 끝날 때(= 그 화면이 닫혀 돌아올 때) 깃발을 내립니다. 과거에 다른 방식으로 풀려다 생긴 버그 이력도 적혀 있습니다.", ["async"]),
        (98, 122, "<b>스크롤 알림 처리.</b> 맨 끝을 이미 넘어 더 당긴 거리(<code>pixels - maxScrollExtent</code>)를 직접 계산해 60을 넘으면 <code>context.push('/routine/today')</code>를 합니다. iOS 스타일 스크롤은 <code>OverscrollNotification</code>을 안 보내고 <code>ScrollUpdateNotification</code>만 보내서 이렇게 계산해야 한다고 주석이 설명합니다. <code>.then((_) {...})</code>는 push가 끝난 뒤 실행할 일이고, <code>false</code>를 돌려줘야 알림이 위로 계속 전달됩니다.", ["gopush"]),
        (124, 131, "build 시작. <b>선택한 날의 루틴 목록</b>과 <b>이 달의 날짜별 개수</b> 두 가지를 provider에서 읽습니다. 둘 다 인자를 받는 provider(<code>family</code>)입니다. 선택 날짜나 표시 월이 바뀌면 인자가 달라져 자동으로 다른 목록을 읽습니다.", ["build", "family"]),
        (133, 138, "<b>Stack으로 \"스크롤되는 본문\"과 \"고정된 + 버튼\"을 겹칩니다.</b> + 버튼은 스크롤해도 같은 자리에 떠 있어야 해서 스크롤 영역 바깥에 둡니다.", ["layout"]),
        (139, 145, "주석: <code>Positioned.fill</code>이 없으면 Stack이 스크롤 내용의 높이에만 맞춰 줄어들어서, 루틴이 없는 날에는 + 버튼이 화면 아래가 아니라 짧은 내용 바로 밑에 붙어버립니다. fill로 화면 전체를 차지하게 합니다.", []),
        (146, 150, "<code>SafeArea</code> 안에 <code>NotificationListener</code>. 이 위젯이 아래에서 올라오는 스크롤 알림을 <code>_handleScrollNotification</code>으로 받습니다.", ["scroll"]),
        (151, 163, "<b>스크롤 물리.</b> 안드로이드 기본은 끝에서 멈춰서 overscroll이 생기지 않으니, 끝에서 튕기는 <code>BouncingScrollPhysics</code>가 필요하고, 내용이 짧아도 당길 수 있게 <code>AlwaysScrollableScrollPhysics</code>로 감쌉니다.", []),
        (164, 180, "<code>Column</code>의 첫 자식은 <b>자녀 선택 칩 줄</b>(<code>ChildSelector</code>, 서버 루틴 API가 자녀별이라 어느 자녀를 볼지 고름), 그 아래 월 제목 줄(<code>_MonthHeader</code>). 화살표 눌림에 <code>_shiftMonth(-1)</code>/<code>(1)</code>을 연결하고 18 간격.", ["layout"]),
        (181, 187, "요일 헤더 줄과 <b>달력 그리드</b>. 어느 달인지, 어느 날이 선택됐는지, 날짜별 개수, 날짜를 눌렀을 때 할 일(<code>_selectDate</code>)을 넘깁니다. 부모(이 State)가 값을 들고 있고 자식은 그리기만 합니다.", []),
        (188, 200, "<b>그날의 루틴 카드 목록.</b> <code>RoutineCardList(routines: ...)</code>에 선택한 날의 루틴을 넘깁니다. 아래 여백 120은 + 버튼에 마지막 카드가 가리지 않게 하려는 것입니다.", []),
        (201, 211, "<b>고정 \"+\" 버튼</b>(오른쪽·아래 위치는 두 화면이 공유하는 상수)과 하단 탭바(<code>currentIndex: 1</code> — 루틴 탭 켜짐).", []),
        (213, 249, "<b>월 제목 줄 위젯.</b> 큰 \"10월\" 글자와 좌우 화살표 둘. 디자인에는 화살표가 없었지만 월을 넘길 수 있어야 해서 추가했다고 주석에 적혀 있습니다. 화살표 에셋은 홈 캐러셀 것을 재사용합니다.", ["voidcallback"]),
        (251, 285, "<b>월 화살표 버튼 하나.</b> 원본 아이콘이 위쪽(^)을 가리켜서 <code>RotatedBox(quarterTurns)</code>로 3(왼쪽)이나 1(오른쪽)만큼 돌려 씁니다. 눌리는 반경 18, 안쪽 여백 8로 손가락이 닿기 쉽게 합니다.", ["tap"]),
        (287, 311, "<b>요일 헤더 \"일 월 화 수 목 금 토\".</b> 리스트를 <code>for</code>로 돌며 <code>Expanded</code> 일곱 칸을 만듭니다. 일요일·토요일도 같은 회색인 것이 Figma 값입니다.", ["collectionif", "layout"]),
        (313, 329, "<b>달력 그리드 위젯.</b> 달, 선택 날짜, 날짜별 개수(<code>Map&lt;int,int&gt;</code>), 눌림 함수를 받습니다. <code>ValueChanged&lt;DateTime&gt;</code>은 \"날짜를 받는 함수\" 타입입니다.", ["valuechanged"]),
        (331, 344, "<b>빈 칸 계산.</b> 그 달의 일수와 1일의 요일을 구합니다. Dart의 요일은 월=1…일=7이라 \"일요일 시작 달력\"에는 <code>% 7</code>로 앞에 둘 빈 칸 수를 얻습니다(일→0칸, 월→1칸). 마지막 주도 7칸을 채우게 뒤 빈 칸 수도 계산합니다.", []),
        (346, 372, "<b>칸 목록 만들기.</b> 앞 빈 칸 → 1일부터 말일까지 날짜 칸(<code>_CalendarDayCell</code>) → 뒤 빈 칸. 날짜 칸에는 오늘인지, 선택됐는지, 그날 개수를 계산해 넘깁니다. 빈 칸은 크기 0의 <code>SizedBox.shrink()</code>입니다.", ["setmap"]),
        (374, 389, "<b>7칸씩 끊어 한 주(Row)로, 주들을 Column으로.</b> <code>sublist(i, i + 7)</code>이 7개씩 잘라내고 <code>.map(...).toList()</code>로 각 칸을 <code>Expanded</code>로 감쌉니다.", ["maplist"]),
        (391, 410, "<b>날짜 칸 하나.</b> 날짜, 요일 번호(<code>column</code>, 0=일…6=토), 오늘/선택 여부, 개수, 눌림 함수를 받습니다.", []),
        (412, 415, "색 상수 넷(일요일 빨강, 토요일 파랑, 선택 하늘색, 개수 배지 회색).", ["const"]),
        (417, 428, "<b>숫자 색 정하기.</b> 선택됐으면 흰색, 아니면 일요일(0)은 빨강, 토요일(6)은 파랑, 나머지는 검정. <code>Color textColor;</code>는 값 없이 선언했다가 if / else if로 한 번씩 정합니다.", []),
        (430, 455, "<b>눌리는 영역 + 날짜 숫자.</b> 25×25 상자에 숫자를 가운데 놓고, 선택됐으면 하늘색 원 배경을 깝니다(<code>조건 ? 꾸밈 : null</code>).", ["tap"]),
        (456, 483, "<b>그날 루틴이 1개 이상이면</b> 작은 회색 원 안에 개수를 보여주고(<code>routineCount! &gt; 0</code>의 <code>!</code>는 위의 null 검사를 보증), 없으면 같은 높이의 빈 상자로 칸 높이를 맞춥니다.", ["collectionif", "null"]),
    ],
    next_hint="자녀 선택 칩(<code>ChildSelector</code>)은 다음 정류장에서 보고, 그 뒤 <code>routinesForDateProvider</code>를 Ctrl+클릭해 <code>routine_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/children/presentation/child_selector.dart",
    title="자녀 선택 칩",
    role="자녀 선택 줄",
    arrive="<code>routine_screen.dart</code> 170줄 <code>ChildSelector()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, 자녀 provider.", []),
        (6, 13, "문서 주석. 서버의 루틴·기기 API가 자녀별이라 루틴 탭 맨 위에서 자녀를 고르게 하고, 선택은 <code>selectedChildIdProvider</code>에 담깁니다. 자녀는 최대 10명이라 칩이 가로로 스크롤됩니다.", []),
        (14, 17, "provider만 읽는 <code>ConsumerWidget</code>과 색 상수.", ["consumer"]),
        (19, 22, "<b>자녀 목록과 값 꺼내기.</b> <code>async.value</code>는 값이 도착했을 때만 있고(<code>List&lt;Child&gt;?</code>) 아직이면 <code>null</code>입니다.", ["asyncvalue", "build"]),
        (24, 36, "<b>값이 아직 없을 때 두 갈래.</b> 로딩이면 칩 높이(31)만큼 빈 상자(로딩이 짧아 스피너는 오히려 깜빡이니까), 오류면 안내 글을 보여주고 <b>누르면 <code>ref.invalidate</code>로 다시 시도</b>합니다.", ["null", "tap"]),
        (37, 41, "<b>자녀가 0명</b>이면 칩 대신 \"등록된 자녀가 없어요\".", []),
        (42, 43, "<b>지금 기준 자녀</b>(<code>currentChildProvider</code>)를 읽습니다. 칩이 켜졌는지 비교하는 데 씁니다.", []),
        (44, 61, "<b>칩 줄.</b> 가로 스크롤 안의 <code>Row</code>에 자녀마다 칩을 만듭니다(첫 칩만 빼고 앞에 6 간격). 칩을 누르면 <code>ref.read(selectedChildIdProvider.notifier).state = child.childId</code>로 선택만 바꿉니다. 그러면 이 값을 watch하는 위젯들이 다시 그려집니다.", ["stateprovider", "collectionif"]),
        (63, 70, "<b>칩 한 개.</b> 이름, 켜졌는지, 눌림 함수를 받습니다.", ["voidcallback"]),
        (72, 99, "알약 모양(높이 31, 모서리 44). 켜진 칩은 하늘색 배경에 흰 글씨, 아니면 흰 배경에 회색 글씨와 옅은 그림자. 루틴 추가 폼의 탭 칩과 같은 모양입니다.", ["tap"]),
    ],
    next_hint="이제 루틴 목록을 만드는 <code>routine_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/data/routine_providers.dart",
    title="서버 루틴에서 \"그날 것\"을 뽑아내는 provider들",
    role="루틴 provider",
    arrive="<code>routine_screen.dart</code> 126줄 <code>routinesForDateProvider(_selectedDate)</code>, 129줄 <code>routineCountsByDayProvider</code>에서 왔습니다.",
    chunks=[
        (1, 9, "Riverpod, 오류 타입, 인증 provider(서버 통신 객체를 가져옴), <b>현재 자녀 provider</b>, 수정·삭제 범위 enum, 새 루틴 요청 모델, 루틴 모델, 루틴 저장소. 루틴이 서버 데이터라 자녀와 서버 통신 객체가 재료로 들어옵니다. (이전에 있던 Hive 도구 provider는 템플릿까지 서버로 옮기면서 <b>사라졌습니다</b>.)", []),
        (11, 13, "루틴 저장소 provider. 안쪽이 Hive가 아니라 <b>서버를 부르는 <code>ApiRoutineRepository</code></b>로 바뀌었습니다. 화면은 이 provider만 알아서 코드를 거의 안 고쳐도 됐습니다.", []),
        (15, 17, "<b>조회 키 타입.</b> \"어느 자녀의, 어느 기간\"을 레코드 <code>({childId, from, to})</code>로 묶습니다. 값이 같으면 같은 키로 취급돼 같은 조회가 캐시를 공유합니다.", ["recordtype"]),
        (19, 19, "시·분·초를 뗀 날짜만 만드는 작은 함수. 이름의 <code>_</code>는 이 파일 안에서만 쓴다는 뜻.", ["private"]),
        (21, 29, "<b>\"한 달\" 조회 키 만들기.</b> 그 달 1일부터 말일까지. <code>DateTime(년, 월 + 1, 0)</code>의 0일은 \"전달 말일\"이라 말일을 구하는 흔한 방법입니다. 서버가 한 번에 한 달치를 주도록 달 단위로 자릅니다.", []),
        (31, 42, "<b>서버에서 한 기간을 읽는 provider(핵심).</b> <code>FutureProvider.autoDispose.family</code>: <b>family</b>는 조회 키마다 따로 만들고, <b>autoDispose</b>는 그 데이터를 보는 화면이 모두 사라지면 캐시를 버립니다. 그래서 화면에 <b>다시 들어올 때마다 서버에서 새로 받습니다</b> — 아이가 기기에서 할 일을 완료하면 서버에만 반영되고 앱은 알 수 없기 때문입니다(서버 문서의 권고).", ["family", "asyncvalue"]),
        (44, 53, "<b>\"지금 보는 자녀의 이 달 루틴\"(내부용 파생 provider).</b> 현재 자녀가 아직 없으면(로딩·미등록) 빈 목록, 있으면 그 자녀의 달 조회를 읽어 값이 있을 때만 씁니다. 로딩 중에는 빈 목록이라 화면이 스피너 없이 \"루틴 없음\"으로 보이다가 데이터가 오면 다시 그려집니다.", ["family", "null"]),
        (55, 66, "<b>날짜별 목록.</b> 위의 달 목록에서 같은 날(<code>r.date == day</code>)만 걸러 시작 시각 글자(\"07:30\")순으로 정렬합니다. 시각이 \"HH:mm\" 두 자리 형식이라 글자 비교가 곧 시간순입니다.", ["family"]),
        (68, 77, "<b>달력 칸 아래 개수 배지용 맵.</b> 그 달 루틴을 돌며 <code>일 → 개수</code>를 셉니다(<code>(counts[일] ?? 0) + 1</code>). 루틴이 없는 날은 키가 없습니다.", ["setmap", "null"]),
        (79, 81, "<b>쓰기 기능 묶음 provider.</b> 루틴 만들기·수정·삭제와 하위 할 일 편집이 모두 여기 모여 있고, 끝날 때마다 달력 캐시를 무효화해서 달력·오늘 할 일·홈 카드·상세가 새 값을 받게 합니다.", ["invalidate"]),
        (83, 86, "<code>Ref</code>를 받는 쓰기 클래스.", []),
        (88, 96, "<b>루틴 만들기 (1) 현재 자녀 확인.</b> 서버 API가 자녀별이라 현재 자녀가 없으면 보낼 곳이 없습니다. 그러면 <code>ApiException(code: 'NO_CHILD', ...)</code>을 던져 화면이 스낵바로 알리게 합니다.", ["null"]),
        (97, 102, "<b>(2) 서버에 만들고 캐시 비우기.</b> 저장소의 <code>createRoutine</code>을 부르고, <code>ref.invalidate(routineCalendarProvider)</code>로 <b>family 전체</b>의 낡은 캐시를 한꺼번에 버립니다. 서버가 돌려준 \"만들어진 개수\"를 반환합니다.", ["invalidate", "async"]),
        (104, 120, "<b>루틴 수정.</b> 루틴과 새 이름·시각, <b>범위(<code>ChangeScope</code>)</b>를 받아 저장소에 넘기고 캐시를 비웁니다. 새 값은 이름 있는 인자 네 개(<code>required</code>)로 받습니다.", ["constructor", "invalidate"]),
        (122, 127, "<b>루틴 삭제.</b> 범위와 함께 저장소를 부르고 캐시를 비웁니다.", []),
        (129, 139, "<b>하위 할 일 편집 묶음의 첫 번째: 추가.</b> 주석: 서버가 바꾸는 범위가 동작마다 달라서 <b>추가만 범위를 고를 수 있고</b> 나머지는 그 날짜의 그 루틴에만 적용됩니다.", []),
        (141, 146, "<b>이름 변경.</b> 할 일(<code>SmallRoutine</code>)과 새 이름만 받습니다(범위 없음).", []),
        (148, 151, "<b>할 일 삭제.</b> 역시 범위 없음.", []),
        (153, 160, "<b>순서 변경.</b> 새 순서로 정렬된 할 일 목록을 받아 <b>id 목록만 뽑아</b>(<code>[for (final s in ordered) s.id]</code>) 저장소에 넘깁니다.", ["collectionif"]),
    ],
    next_hint="<code>routineRepositoryProvider</code> 안의 <code>ApiRoutineRepository</code>를 보려고 <code>routine_repository.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/data/routine_repository.dart",
    title="루틴을 서버에서 읽고 만들기",
    role="루틴 저장소(서버)",
    arrive="<code>routine_providers.dart</code> 15줄 <code>ApiRoutineRepository(...)</code>에서 왔습니다.",
    chunks=[
        (1, 8, "Dio, 서버 통신 객체, <b>날짜 형식 도구</b>(<code>api_date.dart</code>, 날짜를 \"2026-10-05\" 글자로), 오류 변환, 새 루틴 요청 모델, 루틴 모델.", []),
        (10, 62, "<b>저장소가 할 일 약속.</b> 읽기(<code>getCalendar</code>), 만들기(<code>createRoutine</code>)에 더해 이번에 <b>수정·삭제·하위 할 일 편집</b> 다섯 가지가 추가됐습니다. 약속의 주석이 각 호출이 <b>어디까지 적용되는지</b>를 적어 둡니다: 루틴 수정·삭제와 할 일 <b>추가</b>는 <code>scope</code>(이 날짜만/같은 반복 전체)를 고를 수 있고, 할 일 <b>이름 변경·삭제·순서 변경은 scope가 없어서 그 날짜 한 행에만</b> 적용됩니다.", ["abstract"]),
        (64, 68, "Dio 구현체. 이전의 Hive 구현(<code>LocalRoutineRepository</code>)을 <b>대체</b>했습니다. 화면과 provider는 약속(<code>RoutineRepository</code>)만 봐서 구현만 바꿔 끼웠습니다.", []),
        (70, 80, "<b>읽기: <code>GET /children/:childId/calendar?from=&to=</code>.</b> 자녀 id를 주소에 끼우고(<code>'/children/$childId/calendar'</code>) 기간은 <code>queryParameters</code>로 보냅니다.", ["interp", "async"]),
        (81, 89, "<b>응답 펼치기.</b> 서버는 \"날짜별 묶음\"을 주는데 앱은 루틴 한 줄씩이 편해서, 날짜마다 <code>bigRoutines</code>를 돌며 <code>Routine.fromCalendarJson(그 날짜, ...)</code>으로 만들어 한 리스트에 모읍니다. 날짜 글자는 <code>DateTime.parse</code>로 날짜 객체로 바꿉니다.", ["factory"]),
        (90, 93, "실패하면 <code>ApiException</code>으로 바꿔 던집니다.", ["trycatch"]),
        (95, 106, "<b>만들기: <code>POST /children/:childId/big-routines</code>.</b> 요청 모델의 <code>toJson()</code>을 본문으로 보내고, 응답의 <code>createdCount</code>(실제로 만들어진 개수)를 돌려줍니다. 서버가 오류 코드(시간 범위 오류, 날짜 개수 초과 등)를 주면 같은 방식으로 <code>ApiException</code>이 되어 폼의 스낵바에 그대로 보입니다.", ["async"]),
        (108, 126, "<b>루틴 수정: <code>PATCH /big-routines/:id?scope=...</code>.</b> 본문은 이름·시작·종료 시각 셋뿐이고, 범위는 쿼리(<code>queryParameters: {'scope': scope.code}</code>)로 보냅니다. 서버는 <code>series</code>면 같은 반복의 <b>오늘 이후</b> 날짜도 함께 바꾸고, 고른 날짜 자체는 지난 날짜여도 고칩니다.", ["async"]),
        (127, 138, "<b>루틴 삭제: <code>DELETE /big-routines/:id?scope=...</code>.</b> 실제로 지우지 않는 soft delete라 이행률 통계가 보존됩니다. 응답 본문이 없어서(204) 돌려줄 값이 없습니다.", []),
        (139, 155, "<b>할 일 추가: <code>POST /big-routines/:id/small-routines?scope=...</code>.</b> 이름만 보냅니다. <code>series</code>면 같은 반복의 오늘 이후 날짜에도 같은 할 일이 생깁니다(서버가 새 미션으로 보고 새 <code>seriesId</code>를 발급).", []),
        (156, 164, "<b>할 일 이름 변경: <code>PATCH /small-routines/:id</code>.</b> <code>scope</code>가 없어서 <b>그 날짜의 그 할 일 하나</b>만 바뀝니다(이름이 바뀌어도 서버의 통계용 미션 식별자는 유지).", []),
        (165, 173, "<b>할 일 삭제: <code>DELETE /small-routines/:id</code>.</b> 역시 그 날짜의 그 할 일 하나만.", []),
        (174, 192, "<b>할 일 순서 변경: <code>PUT /big-routines/:id/small-routines/order</code>.</b> <b>요청 본문의 최상위가 배열</b>이고(문서 확정), 이 루틴의 할 일 <b>전부</b>를 <code>[{smallRoutineId, order}]</code>로 보내야 합니다(하나라도 빠지면 서버가 <code>ROUTINE_ORDER_MISMATCH</code>로 거절). 화면이 정한 새 순서의 id 목록을 받아 1부터 번호를 매기고, 서버가 그 번호로 줄을 세운 뒤 1, 2, 3으로 다시 매깁니다.", ["collectionif"]),
        (193, 193, "클래스 끝.", []),
    ],
    next_hint="<code>Routine.fromCalendarJson</code>의 <code>Routine</code>을 Ctrl+클릭해 모델 <code>routine.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/domain/routine.dart",
    title="루틴 하루치와 하위 할 일",
    role="루틴 모델",
    arrive="<code>routine_repository.dart</code> 47줄 <code>Routine.fromCalendarJson(...)</code>에서 왔습니다.",
    chunks=[
        (1, 8, "문서 주석. 서버 용어로는 <b>빅루틴 하루치</b>이고, 같은 반복에서 나온 행들은 <code>seriesId</code>가 같고 날짜만 다릅니다. 완료 여부는 루틴이 아니라 <b>하위 할 일마다</b> 있고, 아이의 기기가 올리며 앱은 읽기만 합니다.", []),
        (9, 18, "생성자. 이전 모델의 <code>participants</code>와 <code>tag</code>가 <b>사라졌고</b>, 서버 모양(<code>seriesId</code>, <code>startTime</code>, <code>endTime</code>, <code>smallRoutines</code>)이 들어왔습니다. <code>smallRoutines = const []</code>는 안 넘기면 빈 목록입니다.", ["constructor"]),
        (20, 38, "<b>필드.</b> 서버의 <code>bigRoutineId</code>(<code>int</code>), 반복 묶음 id, 날짜(시각 0시), 제목, 시작·종료 시각(<code>\"07:30\"</code> 글자, 없으면 빈 글자), 그리고 하위 할 일 목록. 단일 루틴도 제목과 같은 이름의 할 일 하나를 갖는 이유가 주석에 있습니다(완료 여부가 할 일에 붙기 때문).", []),
        (40, 41, "<b>계산해서 얻는 값(getter) 둘.</b> 전체 할 일 수, 끝낸 할 일 수. 카드의 \"・완료 1/3\"과 상세의 진행 링이 이 값을 씁니다.", ["getter"]),
        (43, 47, "<b>시간 표기 만들기.</b> 시작 시각이 없으면 빈 글자, 종료가 없으면 시작만, 둘 다 있으면 \"07:30~08:30\".", ["interp"]),
        (49, 60, "<b>날짜 + 시작 시각을 하나의 <code>DateTime</code>으로.</b> 정렬·기간 비교용입니다. 시각 글자를 <code>:</code>로 쪼개 숫자로 바꾸고(<code>int.tryParse</code>는 실패하면 null이라 <code>?? 0</code>), 형식이 이상하면 날짜 0시를 돌려줍니다.", ["null"]),
        (62, 78, "<b>서버 JSON → 모델.</b> 응답의 <code>bigRoutines</code> 원소 하나와 \"그 날짜\"를 받습니다(날짜는 바깥 묶음에 있어서 따로 넘김). 하위 할 일을 모델로 바꾸고 <code>sortOrder</code> 순으로 정렬(<code>..sort</code>)한 뒤 필드를 채웁니다. 서버가 값을 비워 줄 수 있는 필드는 <code>as String? ?? ''</code>로 안전하게 받습니다.", ["factory", "maplist", "spread"]),
        (79, 79, "클래스 끝.", []),
        (81, 94, "<b>하위 할 일 한 개(\"세수하기\").</b> id, 이름, 순서, <code>done</code>(끝났는지).", ["constructor"]),
        (96, 104, "<b>서버 JSON → 하위 할 일.</b> <code>done</code>은 <code>json['status'] == 'DONE'</code>이라는 비교 결과(true/false)를 그대로 담습니다. <code>PENDING</code>이면 false.", ["factory"]),
    ],
    next_hint="새 루틴을 만들 때 보내는 요청 모델 <code>new_routine.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/domain/new_routine.dart",
    title="새 루틴을 서버로 보내는 요청 모양",
    role="루틴 생성 요청 모델",
    arrive="<code>routine_providers.dart</code> 7줄의 <code>new_routine.dart</code>, 즉 <code>add_routine_screen.dart</code>가 폼 값으로 만드는 <code>NewRoutine</code>에서 왔습니다.",
    chunks=[
        (1, 1, "날짜를 서버 글자(\"2026-10-05\")로 바꾸는 작은 도구(<code>core/network/api_date.dart</code>). <code>padLeft(2, '0')</code>로 한 자리 월·일 앞에 0을 붙입니다.", []),
        (3, 17, "<b><code>enum RepeatType</code>: 서버가 날짜를 펼치는 세 가지 방식.</b> <code>range</code>(기간 안 매일), <code>weekly</code>(기간 안 지정한 요일마다), <code>dates</code>(지정한 날짜들만). 각 값이 서버에 보낼 글자(<code>code</code>)를 들고 있는 enum입니다(<code>const RepeatType(this.code)</code>).", ["enum"]),
        (19, 20, "<b>\"날짜 몇 개까지\" 상한 12.</b> <code>DATES</code> 모드에서 서버가 받는 최대 개수라서 폼이 13번째를 막을 때 이 상수를 씁니다.", ["const"]),
        (22, 35, "<b>요청 내용 클래스.</b> 반복 모드마다 쓰는 필드가 달라서(<code>startDate</code>·<code>endDate</code>는 range/weekly, <code>repeatDays</code>는 weekly, <code>repeatDates</code>는 dates) 안 쓰는 건 비워 둡니다.", ["constructor"]),
        (37, 56, "필드: 제목, 시작·종료 시각(<code>\"07:30\"</code>), 반복 방식, 날짜들, 요일 코드(<code>MON</code>~<code>SUN</code>), 하위 할 일 이름들.", []),
        (58, 73, "<b>서버에 보낼 JSON 만들기.</b> 필수 값 외에 <b>리스트 안의 <code>if</code></b>로 모드에 맞는 필드만 끼웁니다(<code>if (startDate != null) 'startDate': ...</code>). 하위 할 일은 <code>for</code>로 돌며 <code>{'title': 이름, 'order': i + 1}</code>을 만듭니다. 서버가 이 번호로 줄을 세웁니다.", ["collectionif", "interp"]),
        (74, 74, "클래스 끝.", []),
    ],
    next_hint="이제 이 값들을 쓰는 화면으로 돌아가 <code>routine_card.dart</code>를 봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/widgets/routine_card.dart",
    title="루틴 카드와 카드 목록",
    role="루틴 카드 위젯",
    arrive="<code>routine_screen.dart</code> 191줄 <code>RoutineCardList(routines: ...)</code>에서 왔습니다. \"오늘 할 일\" 화면도 같은 위젯을 씁니다.",
    chunks=[
        (1, 5, "Flutter 위젯, SVG, 화면 이동, 루틴 모델.", []),
        (7, 16, "문서 주석. 카드 한 장 = \"07:30~08:30 아침 준비 ・완료 1/3\" 한 줄 + (할 일이 둘 이상이면) 아래 번호 붙은 하위 할 일들. 완료한 할 일은 번호 배지가 하늘색입니다. 완료는 아이 기기가 서버에 올린 값이라 앱은 읽기만 합니다. 카드를 누르면 상세 화면으로 가며 받아 둔 루틴을 <code>extra</code>로 같이 넘깁니다.", []),
        (17, 23, "<b>루틴 하나를 받아 그리는 위젯.</b> 공용 위젯이라 두 화면 어디서든 씁니다.", ["class"]),
        (25, 30, "<b>그릴 값 준비.</b> 하위 할 일이 <b>둘 이상일 때만</b> 목록을 펼칩니다(<code>length &gt; 1</code>) — 단일 루틴은 제목과 같은 이름의 할 일 하나뿐이라 또 보여주면 중복입니다. 시간 글자는 모델의 <code>timeLabel</code>(\"07:30~08:30\")을 그대로 씁니다.", ["build"]),
        (32, 47, "<b>카드 전체가 눌리는 영역.</b> 누르면 <code>context.push(\'/routine/detail/${routine.id}\', extra: routine)</code>로 상세 화면을 쌓고, <b>이미 받은 루틴 객체를 <code>extra</code>로 같이 넘깁니다</b>(상세가 서버를 다시 부르지 않아도 되게). 흰 배경·둥근 모서리 25·옅은 그림자 상자입니다.", ["tap", "gopush"]),
        (48, 50, "<code>Column</code>으로 \"첫 줄\" 아래에 하위 할 일들을 쌓을 준비.", ["layout"]),
        (51, 85, "<b>첫 줄: \"시각 제목 ・완료 1/3\"과 오른쪽 \">\".</b> 글자 둘은 <code>Wrap</code> 안에 있어서 길면 다음 줄로 넘어갑니다. 옆 글자는 <b>완료한 할 일 수 / 전체 할 일 수</b>(예전의 \"・공통\" 꼬리표가 이것으로 바뀜). <code>Expanded</code>로 화살표를 오른쪽 끝에 밀어냅니다.", []),
        (86, 97, "<b>하위 할 일이 둘 이상일 때만</b>(<code>if (hasSteps) ...[</code>) 14 간격 뒤에 번호 줄들을 그립니다. 각 줄에 이름과 <b>끝났는지(<code>done</code>)</b>를 넘깁니다. 첫 줄은 위 여백 0, 그 다음부터 12.", ["collectionif"]),
        (98, 103, "괄호 닫기.", []),
        (105, 116, "<b>하위 할 일 한 줄 위젯</b>의 선언. 번호, 이름, <b>끝났는지</b>를 받습니다.", []),
        (118, 147, "번호 배지(14×13, 모서리 2)와 글자. <b>끝난 할 일이면 하늘색, 아니면 회색 배지</b>입니다(<code>done ? 하늘색 : 회색</code>). 번호는 <code>i + 1</code>로 1부터 보여줍니다.", ["build"]),
        (149, 178, "<b>루틴이 하나도 없을 때의 안내 카드.</b> \"등록된 루틴이 없어요 / 오른쪽 아래 + 버튼으로 추가해 보세요\".", []),
        (180, 201, "<b>목록 위젯.</b> 비었으면 안내 카드를 돌려주고(<code>if (...) return</code>으로 먼저 끝냄), 아니면 <code>for</code>로 루틴마다 카드 + 10 간격을 쌓습니다.", ["collectionif"]),
    ],
    next_hint="카드를 누르면 가는 상세 화면은 뒤에서 보고, 먼저 <code>routine_screen.dart</code> 204줄의 \"+\" 버튼 <code>AddRoutineButton</code>을 열어봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/widgets/add_routine_button.dart",
    title="오른쪽 아래 \"+\" 버튼",
    role="+ 버튼 위젯",
    arrive="<code>routine_screen.dart</code> 204줄 <code>AddRoutineButton()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, SVG, 화면 이동.", []),
        (5, 11, "<b>위치 상수 두 개.</b> 달력 화면과 \"오늘 할 일\" 화면이 똑같이 써야 화면을 오가도 버튼이 같은 자리에 떠 있는 것처럼 보입니다. 주석이 사용법까지 보여줍니다. 앞의 <code>k</code>는 상수 관례입니다.", ["const"]),
        (13, 16, "버튼 위젯 선언. 누르면 \"단일/복합/템플릿\" 중 고르는 화면으로 간다는 설명.", []),
        (18, 30, "<b>한 줄 핵심: <code>onTap: () =&gt; context.push('/routine/add')</code>.</b> 78×78 SVG가 버튼 그림이고 반경 39로 눌러서, 누르면 물결이 번집니다.", ["tap", "gopush"]),
    ],
    next_hint="<code>/routine/add</code> → <code>router.dart</code> 126줄 <code>RoutineTypeSelectScreen()</code> → <code>routine_type_select_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_type_select_screen.dart",
    title="무엇을 추가할까요?",
    role="루틴 유형 선택",
    arrive="<code>add_routine_button.dart</code> 21줄 <code>context.push('/routine/add')</code> → <code>router.dart</code> 126줄 <code>RoutineTypeSelectScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, SVG, 화면 이동.", []),
        (5, 5, "하단 탭바.", []),
        (7, 13, "문서 주석. 세 선택지가 모두 실제 화면으로 이어지고, 단일/복합은 같은 <code>AddRoutineScreen</code>을 <code>compound</code> 플래그만 다르게 연다는 설명.", []),
        (14, 15, "상태가 없는 화면이라 StatelessWidget.", ["class"]),
        (17, 18, "색 상수 둘.", []),
        (20, 28, "화면 틀과 Column.", ["build", "layout"]),
        (29, 63, "<b>맨 위 줄: 뒤로가기 화살표 + 제목.</b> <code>context.pop()</code>이 쌓인 화면을 한 장 걷어냅니다. 제목 글자가 \"오늘 할 일\"인 것은 Figma 값을 그대로 복사한 것이라 이 화면 제목으로는 어색할 수 있습니다.", ["gopush"]),
        (64, 64, "33 간격.", []),
        (65, 88, "<b>선택지 카드 세 장.</b> 각각 아이콘 경로, 글자, 눌렸을 때 이동할 주소를 넘깁니다: <code>/routine/add/single</code>, <code>/routine/add/compound</code>, <code>/routine/add/templates</code>. 카드 사이 9 간격.", []),
        (89, 95, "괄호 닫기와 하단 탭바(루틴 탭 켜짐).", []),
        (97, 103, "<b>선택지 카드 위젯.</b> 아이콘, 글자, 눌림 함수(null 가능)를 받습니다.", ["voidcallback"]),
        (105, 137, "<b>알약 모양 카드.</b> 높이 88, 모서리 44, 옅은 그림자. 안에 아이콘(28×31) → 20 간격 → 글자(21). 위젯 하나를 세 번 재사용해서 세 카드가 같은 모양입니다.", ["tap"]),
    ],
    next_hint="\"단일 루틴 추가하기\"를 누르면 <code>router.dart</code> 133줄 <code>AddRoutineScreen</code> → <code>add_routine_screen.dart</code>(1,164줄, 이 앱에서 가장 큰 파일)로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/add_routine_screen.dart",
    title="루틴 추가 폼 (일반·기간·반복·다중)",
    role="루틴 추가 폼",
    arrive="<code>routine_type_select_screen.dart</code> 72줄 <code>context.push('/routine/add/single')</code> → <code>router.dart</code> 133줄 <code>AddRoutineScreen(...)</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 11, "오류 타입, 루틴 provider, 템플릿 provider와 모델, 새 루틴 요청 모델, <b>공용 폼 위젯</b>(<code>routine_form_widgets.dart</code> — 알약 입력 칸·시간 버튼, 수정 화면과 같이 쓰려고 이 파일에서 <b>뺐습니다</b>). 예전의 반복 날짜 계산은 서버가 날짜를 펼치게 되면서 사라졌습니다.", []),
        (13, 35, "<b>이 폼의 설계도(문서 주석).</b> 단일/복합은 <code>compound</code> 플래그 하나만 달라 화면 하나로 합쳤습니다. 만든 루틴은 <b>지금 보는 자녀의 것으로 서버에 저장</b>되고, 네 탭이 서버 반복 모드에 대응합니다: 일반·기간 → <code>RANGE</code>, 반복 → <code>WEEKLY</code>(종료일 필수), 다중 → <code>DATES</code>(최대 12개). 날짜를 펼치는 일은 서버가 하고, 서버는 단일/복합을 구분하지 않아서 단일 루틴도 제목과 같은 이름의 할 일 하나를 보냅니다. 수정은 서버 규칙에 맞춰 다시 만들 때까지 뺐다는 설명도 있습니다.", []),
        (36, 47, "<b>입력으로 받는 값 둘.</b> <code>compound</code>(복합 여부)와 <code>template</code>(템플릿으로 들어왔을 때). 예전의 <code>editing</code>(수정 중인 루틴)은 수정 기능을 뺀 것과 함께 없어졌습니다.", ["constructor", "null"]),
        (49, 52, "State와 색 상수 셋.", []),
        (54, 58, "<b>고정 목록들.</b> 탭 이름, 요일 글자(일~토), 그리고 <b>같은 순서의 서버 요일 코드</b>(<code>SUN</code>~<code>SAT</code>). 번호(0=일…6=토)로 두 목록을 짝지어 씁니다. 예전의 구성원 목록(지예·예담·예소)은 사라졌습니다.", ["const"]),
        (60, 68, "<b>입력 상태 초기값.</b> 이름 칸은 \"템플릿이면 템플릿 이름, 아니면 빈 글자\"로 시작하고, 하위 할 일은 <code>List.of(...)</code> <b>복사본</b>이라 고쳐도 템플릿 원본이 안 바뀝니다. <b>시작·종료 시각도 템플릿의 시각으로 시작합니다</b>(<code>parseHhmm</code>, 없거나 형식이 이상하면 00:00).", ["late", "null"]),
        (69, 71, "시작·종료 시각(기본 00:00), 지금 탭, 저장 중 여부, 템플릿 저장 체크 여부. 예전의 \"선택된 구성원\"은 없습니다.", []),
        (73, 86, "<b>탭마다 따로 가지는 상태.</b> 일반(날짜 하나), 기간(시작·끝), 다중(날짜 모음 <code>Set</code>), 반복(요일 모음, 시작일, 종료일). <b>반복은 서버 <code>WEEKLY</code>가 시작·종료일을 모두 요구해서</b> 종료일도 null이 아닙니다. 이전의 매월·매년·주기 상태 9개가 통째로 사라졌습니다.", ["setmap", "late"]),
        (88, 96, "<b><code>initState</code>.</b> 오늘 날짜(시·분·초 0)로 \"일반\"과 반복의 시작일을 맞추고, 반복 종료일은 <b>기본 4주 뒤</b>로 잡습니다.", ["stateful"]),
        (98, 103, "컨트롤러 둘 정리.", []),
        (105, 118, "<b>시간 고르기.</b> <code>showTimePicker</code>로 표준 시간 팝업을 띄우고, 취소하면 <code>null</code>이라 그냥 끝냅니다. 시작/종료는 <code>isStart</code>로 구분합니다.", ["pickers", "async"]),
        (120, 127, "<b>하위 할 일 추가.</b> 입력 글자를 <code>trim()</code>해서 비었으면 무시하고, <code>[..._steps, text]</code>로 <b>새 리스트</b>를 만들어 대입한 뒤 입력 칸을 비웁니다.", ["spread"]),
        (129, 133, "하위 할 일 삭제(복사본에서 <code>removeAt</code>).", ["spread"]),
        (135, 137, "<b>스낵바 한 줄 도우미.</b> 폼 검사 메시지를 여러 곳에서 보이려고 함수로 뺐습니다.", []),
        (139, 143, "<b>폼 값을 서버 요청으로 바꾸는 함수.</b> 선택한 탭에서 덜 정해진 값이 있으면 이유를 스낵바로 알리고 <code>null</code>을 돌려줍니다. 먼저 보낼 할 일 목록을 정합니다: <b>비어 있으면 제목과 같은 할 일 하나</b>(단일 루틴이나 할 일을 안 적은 복합 루틴).", ["null"]),
        (144, 162, "<b>함수 안의 함수 <code>build</code>.</b> 탭마다 달라지는 값(반복 방식, 날짜, 요일, 날짜들)만 인자로 받고, 공통 값(제목, 시각, 할 일)은 한 곳에서 채워 <code>NewRoutine</code>을 만듭니다.", ["constructor"]),
        (164, 170, "<b>탭별 요청 1: \"기간\".</b> 시작일과 종료일이 모두 있어야 합니다. <code>RepeatType.range</code>.", ["switchexpr"]),
        (171, 184, "<b>\"반복\"(매주).</b> 요일이 하나도 없으면 막고, 고른 번호를 <code>sort</code>한 뒤 서버 요일 코드로 바꿉니다(<code>_weekdayCodes[i]</code>). <code>RepeatType.weekly</code> + 시작·종료일.", ["maplist"]),
        (185, 193, "<b>\"다중\".</b> 날짜가 하나도 없으면 막고, 있으면 정렬한 날짜 목록을 <code>RepeatType.dates</code>로 보냅니다(최대 12개 제한은 아래 날짜 누르는 함수가 막음).", []),
        (194, 197, "<b>기본값 = \"일반\".</b> 하루짜리는 <code>RANGE</code>에 <b>시작일과 종료일을 같게</b> 보냅니다(서버에 별도 \"하루\" 모드가 없음).", []),
        (199, 204, "<b>\"완료\" 처리 (1) 이름 검사.</b>", ["async"]),
        (205, 211, "<b>(2) 시간 검사.</b> 종료가 시작보다 뒤여야 합니다. 서버도 검사하지만(<code>ROUTINE_INVALID_TIME_RANGE</code>) 미리 알려 왕복을 줄입니다. 시각을 \"분\" 단위 정수로 바꿔 비교합니다.", []),
        (212, 213, "<b>(3) 요청 만들기.</b> 탭 검사에서 실패하면(<code>null</code>) 여기서 끝납니다.", ["null"]),
        (215, 217, "<b>(4) 서버에 저장.</b> 저장 중 표시를 켜고 <code>routineActionsProvider.createRoutine(request)</code>를 기다립니다. 지금 보는 자녀에게 <code>POST big-routines</code>를 보내고 달력 캐시를 무효화합니다.", ["trycatch", "invalidate"]),
        (219, 234, "<b>(5) 템플릿에 저장하기가 켜진 복합 루틴</b>이면 이름·시각·할 일을 템플릿으로도 <b>서버에 저장</b>합니다. 루틴이 이미 만들어진 뒤라서, 템플릿 저장이 실패해도 화면에 남아 다시 누르게 하면 같은 루틴이 또 생깁니다. 그래서 오류는 변수(<code>templateError</code>)에 담아 두고 <b>알림만 하고 달력으로 넘어갑니다</b>.", []),
        (236, 242, "<b>(6) 끝내기.</b> 화면이 살아 있으면 <code>context.go('/routine')</code>으로 달력에 돌아갑니다(선택 화면까지 두 겹 쌓여 있어 <code>pop</code> 대신 <code>go</code>).", ["gopush"]),
        (243, 249, "<b>서버 오류 처리.</b> <code>ApiException</code>의 메시지를 그대로 스낵바에 보입니다(기간이 너무 길다, 날짜가 너무 많다 같은 서버 규칙 위반을 서버가 한국어로 알려 줍니다). 끝나면 저장 중 표시를 끕니다.", ["trycatch"]),
        (251, 261, "<b>build.</b> 흰 배경, 스크롤, 아래 여백 32, <code>Column</code>.", ["build", "scroll"]),
        (262, 293, "<b>맨 위 줄: 뒤로가기 + 제목.</b> 제목은 <code>_titleForMode()</code>가 \"단일 루틴 추가하기\"/\"복합 루틴 추가하기\"로 돌려줍니다.", []),
        (294, 294, "간격.", []),
        (295, 301, "<b>\"루틴 이름\"</b> 라벨. 좌우 37 여백 안의 <code>Column</code>.", ["layout"]),
        (302, 313, "<b>이름 입력 칸.</b> 알약 모양 껍데기(<code>_PillField</code>) 안의 <code>TextField</code>. 컨트롤러를 연결하고 밑줄 없는 꾸밈입니다.", ["formfield"]),
        (314, 316, "\"시간 설정\" 라벨.", []),
        (317, 335, "<b>시작·종료 시간 칸 두 개</b>를 가로로. 눌리면 <code>_pickTime</code>을 시작/종료로 구분해 부릅니다. 이 아래에는 예전에 <b>\"대상 선택\" 구성원 칩이 있었지만 서버에 참여자 개념이 없어 없어졌습니다</b>.", ["layout"]),
        (336, 363, "<b>복합 루틴일 때만</b>(<code>if (widget.compound)</code>) \"행동 추가\" 입력 칸. 글자 칸 + \"+\" 아이콘. 엔터(<code>onSubmitted</code>)나 + 누름이 <code>_addStep</code>을 부릅니다.", ["collectionif"]),
        (364, 404, "<b>추가된 하위 할 일 목록.</b> 번호 배지 + 글자 + \"×\" 삭제(<code>_removeStep(i)</code>). 목록이 비면 아무것도 안 그립니다.", ["collectionif"]),
        (405, 415, "간격 뒤에 회색 둥근 상자(<b>날짜 설정 영역</b>)를 엽니다.", []),
        (416, 431, "<b>탭 버튼 네 개.</b> 누르면 <code>_activeTab</code>이 바뀌어 아래 내용이 바뀝니다. (수정 모드가 있던 때는 숨겨야 해서 조건이 붙어 있었지만 지금은 항상 보입니다.)", ["collectionif"]),
        (432, 463, "<b>탭에 따라 다른 위젯을 고르는 <code>switch</code> 식.</b> 일반·기간·다중은 같은 <code>_MonthCalendar</code>를 쓰되 \"무엇을 선택된 것으로 볼지\"와 \"날짜를 누르면 무엇을 할지\"만 다르게 넘기고, 나머지(반복)는 <code>_RepeatSettings</code>에 요일·시작일·종료일과 \"바뀌면 이렇게\" 함수를 넘깁니다. 시작일을 바꿨는데 종료일이 앞서면 4주 뒤로 다시 잡습니다.", ["switchexpr", "valuechanged"]),
        (464, 467, "괄호 닫기.", []),
        (468, 493, "<b>복합 루틴일 때만 \"템플릿에 저장하기\" 체크박스.</b> 누르면 <code>_saveAsTemplate</code>을 반대로 뒤집습니다.", ["collectionif", "tap"]),
        (494, 510, "<b>\"완료\" 버튼.</b> 저장 중이면 <code>onPressed: null</code>이라 눌리지 않고, 누르면 <code>_submit</code>.", []),
        (511, 516, "괄호 닫기.", []),
        (518, 518, "<b>제목 글자.</b> 복합/단일 두 가지(수정 모드가 없어져 단순해졌습니다).", ["arrow"]),
        (520, 521, "<b>같은 날인지 비교하는 작은 함수.</b> 연·월·일이 모두 같으면 true.", []),
        (523, 527, "<b>\"기간\" 탭에서 이 날이 선택 범위 안인가.</b> 끝이 아직 없으면 시작일만, 있으면 시작 이상 끝 이하.", []),
        (529, 542, "<b>\"기간\" 탭 날짜 누르기 규칙.</b> 첫 탭은 시작일, 그보다 늦은 날을 또 누르면 끝일, 시작일보다 이른 날을 누르면 시작일을 새로 잡습니다.", []),
        (543, 558, "<b>\"다중\" 탭 날짜 누르기.</b> 이미 찍은 날이면 빼고, 아니면 추가합니다. 단, <b>서버가 <code>DATES</code>로 받는 날짜는 최대 12개</b>라서 13번째를 찍으면 추가하지 않고 \"최대 12개까지\" 스낵바를 띄웁니다(<code>firstOrNull</code>은 없으면 null).", ["setmap"]),
        (559, 560, "<b>시간 버튼.</b> \"00:00 부터\"처럼 시각과 안내 글자를 양끝에 놓습니다.", []),
        (562, 594, "<b>탭 버튼.</b> 활성이면 하늘색 배경에 흰 글자, 아니면 흰 배경에 회색 글자.", []),
        (596, 609, "<b>일반·기간·다중이 공유하는 달력.</b> 부모가 <code>isSelected</code>(이 날이 선택됐나?)와 <code>onSelectDate</code>(누르면 무엇을?)를 정해 주므로 달력 그리드 하나로 세 가지 선택 방식을 표현합니다. <code>bool Function(DateTime)</code>은 \"날짜를 받아 bool을 돌려주는 함수\"의 타입입니다.", ["valuechanged"]),
        (610, 623, "<b>그 달의 칸 계산.</b> 이번 달 일수와 1일의 요일(앞 빈 칸 수)은 루틴 화면 달력과 같은 방식입니다. 이 폼의 달력은 <b>이번 달 하나만</b> 보여줍니다(월 이동 없음).", []),
        (624, 655, "<b>날짜 칸 만들기.</b> 선택 여부를 부모에게 물어 색을 정하고(선택=흰색, 일요일=빨강, 토요일=파랑), 29×29 상자에 숫자를 놓고 선택됐으면 하늘색 원을 깝니다.", ["tap"]),
        (656, 668, "뒤 빈 칸을 채우고 7칸씩 한 주(Row)로 묶습니다.", ["maplist"]),
        (670, 694, "<b>달력 맨 위 \"10월 2026\" 제목 + 요일 헤더 + 주들.</b> 마지막 <code>...rows</code>의 <code>...</code>는 주 목록을 펼쳐서 Column의 자식으로 끼웁니다.", ["spread"]),
        (696, 709, "<b>\"반복\" 탭 위젯.</b> 서버가 지원하는 <b>\"매주\"만</b> 남겼습니다(매월·매년·주기는 서버에 없어서 제거). 요일을 고르고 시작·종료 날짜를 고릅니다. 요일이 기간 안에 하루도 없으면 서버가 오류 없이 0개를 만듭니다.", ["constructor"]),
        (711, 720, "<b>필드.</b> 요일 글자 목록, 선택된 요일 번호 모음, \"요일을 눌렀을 때\" 함수, 시작·종료 날짜와 \"바뀌면 부를\" 함수. 예전의 20여 개에서 7개로 줄었습니다.", ["valuechanged"]),
        (722, 740, "build. \"반복 요일\" 라벨과 요일 동그라미 7개(<code>Wrap</code>, 눌리면 <code>onToggleWeekday(i)</code>), 16 간격.", ["build"]),
        (741, 756, "<b>\"시작 날짜\"</b> 행. 누르면 <code>showDatePicker</code>로 표준 날짜 팝업을 띄워(전후 1년·5년 범위) 고른 날짜를 부모에게 알립니다. 취소하면 <code>null</code>이라 무시합니다.", ["pickers"]),
        (757, 776, "<b>\"종료 날짜\"</b> 행. 선택 가능한 가장 이른 날은 시작일입니다(<code>firstDate: start</code>). 예전에는 \"없음\"으로 비워 둘 수 있었지만 <b>서버 WEEKLY는 종료일이 필수</b>라 항상 값이 있습니다.", ["pickers"]),
        (778, 795, "<b>\"라벨 ····· 오른쪽 위젯\"</b> 한 줄 위젯. 양끝 정렬(<code>spaceBetween</code>).", []),
        (797, 813, "<b>날짜 버튼.</b> \"2026년 10월 5일\" 글자만 보여주고 누르면 부모가 준 함수를 부릅니다. 값이 없을 때의 \"없음\"과 지우기(\"×\")는 종료일이 필수가 되면서 뺐습니다.", []),
        (815, 847, "<b>요일 동그라미 하나.</b> 32×32 원, 선택되면 하늘색. 이 파일 끝입니다.", []),
    ],
    next_hint="템플릿에 저장한 것을 쓰는 쪽, <code>routine_template_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/data/routine_template_providers.dart",
    title="저장해 둔 템플릿: 서버에서 읽고 저장·삭제",
    role="템플릿 provider",
    arrive="<code>add_routine_screen.dart</code> 225줄 <code>ref.read(routineTemplateActionsProvider).addTemplate(...)</code>에서 왔습니다.",
    chunks=[
        (1, 7, "Riverpod, 오류 타입, 인증·자녀 provider, 템플릿 모델, 템플릿 저장소. 템플릿도 이제 <b>자녀별 서버 데이터</b>라서 서버 통신 객체와 현재 자녀가 재료입니다.", []),
        (9, 11, "템플릿 저장소 provider. 안쪽이 Hive가 아니라 <b>서버를 부르는 <code>ApiRoutineTemplateRepository</code></b>입니다(루틴 저장소와 같은 모양).", ["provider"]),
        (13, 20, "<b>템플릿 목록 provider.</b> <code>autoDispose</code>라서 \"템플릿 사용\" 화면에 들어올 때마다 서버에서 새로 받습니다. 자녀가 아직 없으면 빈 목록, 있으면 그 자녀의 템플릿을 읽습니다. <code>async</code> 함수 안에서 값이 없으면 먼저 <code>return</code>하는 모양입니다.", ["asyncvalue", "null"]),
        (22, 27, "쓰기 기능 provider와 <code>Ref</code>를 받는 클래스.", ["provider"]),
        (29, 35, "<b>템플릿 저장.</b> 이름·시작·종료 시각·할 일 이름들을 이름 있는 인자로 받습니다. <b>이전에는 이름과 할 일만</b> 저장했는데 서버 양식이 시간도 담아서 늘었습니다.", ["constructor"]),
        (36, 42, "현재 자녀가 없으면 보낼 곳이 없어서 <code>NO_CHILD</code> 오류를 던집니다(루틴 만들기와 같은 방식).", ["null"]),
        (43, 51, "<b>서버에 저장하고 목록 캐시 무효화.</b> 저장소의 <code>createTemplate</code>을 부른 뒤 <code>ref.invalidate(routineTemplateListProvider)</code>로 낡은 목록을 버립니다. 이 앱의 \"저장 + invalidate\" 패턴 그대로입니다.", ["invalidate", "async"]),
        (53, 57, "<b>템플릿 삭제.</b> 템플릿 id만으로 지우고(자녀와 무관하게 서버가 소유권을 검사) 목록 캐시를 비웁니다. 이 템플릿으로 이미 만든 루틴은 그대로 남습니다.", ["invalidate"]),
    ],
    next_hint="템플릿 목록 화면 <code>routine_template_list_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_template_list_screen.dart",
    title="템플릿 사용: 고르면 폼이 미리 채워진다",
    role="템플릿 목록 화면",
    arrive="<code>routine_type_select_screen.dart</code> 84줄 <code>context.push('/routine/add/templates')</code> → <code>router.dart</code> 145줄 <code>RoutineTemplateListScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 8, "Flutter 위젯, Riverpod, SVG, 화면 이동, 오류 타입, 템플릿 provider와 모델.", []),
        (10, 17, "문서 주석. 지금 보는 자녀의 템플릿(이름·시간·할 일)을 <b>서버에서 받아</b> 보여주고, 하나를 고르면 단일 루틴 폼에 이름/시간/할 일이 미리 채워집니다(날짜·반복은 폼에서 새로 고름). 카드 오른쪽 <b>휴지통으로 템플릿을 지울 수 있고</b> 이미 만든 루틴은 남습니다.", []),
        (18, 19, "provider만 읽는 <code>ConsumerWidget</code>.", ["consumer"]),
        (21, 22, "색 상수 둘.", []),
        (24, 26, "템플릿 목록 읽기(없으면 빈 리스트).", ["asyncvalue", "build"]),
        (28, 34, "화면 틀과 Column.", ["layout"]),
        (35, 62, "<b>뒤로가기 화살표 + \"템플릿 사용\" 제목 줄.</b> 앞의 유형 선택 화면과 같은 모양입니다(같은 코드가 화면마다 복붙돼 있습니다).", []),
        (63, 63, "간격.", []),
        (64, 83, "<b>비었으면 안내 글자, 있으면 <code>ListView.separated</code>.</b> 안내는 \"저장된 템플릿이 없어요 — 루틴을 추가할 때 '템플릿에 저장하기'를 켜면 여기에 모여요\". <code>Expanded</code> 안에 넣어 남는 세로 공간을 목록이 쓰게 합니다.", ["listview"]),
        (84, 89, "괄호 닫기.", []),
        (91, 91, "클래스 선언 줄(위 설명).", []),
        (92, 94, "<b>템플릿 카드 위젯.</b> 이제 삭제 때 <code>ref</code>가 필요해서 <code>ConsumerWidget</code>입니다.", ["consumer"]),
        (96, 118, "<b>삭제 확인과 실행.</b> 확인창을 띄우고(<code>showDialog&lt;bool&gt;</code>) <code>true</code>이면 <code>routineTemplateActionsProvider.deleteTemplate(id)</code>를 부릅니다. 서버 오류면 스낵바로 알립니다. 목록은 삭제 뒤 캐시가 무효화되어 알아서 갱신됩니다.", ["dialog", "trycatch"]),
        (120, 136, "<b>누르면 <code>context.push('/routine/add/single', extra: template)</code>.</b> <code>extra</code>는 주소에 안 들어가는 <b>덤 데이터</b>를 다음 화면에 실어 보내는 go_router 기능입니다. <code>router.dart</code>가 <code>state.extra as RoutineTemplate?</code>로 받아 폼에 넘깁니다. 이하는 흰 둥근 카드 꾸밈.", ["gopush"]),
        (137, 161, "<b>첫 줄: \"시각 이름\"과 오른쪽 휴지통.</b> 시각은 <code>timeLabel</code>처럼 \"07:30~08:30\" 모양으로 만들어 붙입니다. 휴지통(<code>InkResponse</code>)을 누르면 삭제 확인입니다.", []),
        (162, 197, "<b>하위 할 일이 있으면 번호 배지 + 글자 줄들.</b> 루틴 카드의 단계 줄과 같은 모양을 한 번 더 직접 그렸습니다(공용 위젯으로 뺄 수 있는 중복).", ["collectionif"]),
        (198, 203, "괄호 닫기.", []),
    ],
    next_hint="오른쪽 위 \"+\" 쪽으로 돌아가서, 달력 목록의 맨 아래를 당기면 가는 <code>today_routines_screen.dart</code>를 봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/today_routines_screen.dart",
    title="오늘 할 일: 위로 당기면 달력으로",
    role="오늘 할 일 목록",
    arrive="<code>routine_screen.dart</code> 116줄 <code>context.push('/routine/today')</code> → <code>router.dart</code> 108줄 <code>TodayRoutinesScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 9, "하단 탭바, 루틴 provider, <b>+ 버튼과 카드 목록</b>(달력 화면과 같은 위젯을 재사용).", []),
        (11, 22, "문서 주석. 달력 화면과 <b>대칭</b>입니다. 거기서는 맨 아래를 넘어 당기면 이 화면으로 오고, 여기서는 맨 위를 넘어 당기거나 위쪽 화살표를 누르면 돌아갑니다. + 버튼 위치 상수를 같게 쓴 이유도 적혀 있습니다.", []),
        (23, 24, "Stateful + <code>ref</code>가 필요한 <code>ConsumerStatefulWidget</code>.", ["stateful"]),
        (26, 29, "State 연결.", []),
        (31, 32, "State 클래스와 배경색.", []),
        (34, 36, "달력 화면과 같은 값 60(px).", ["const"]),
        (38, 43, "<b>\"한 번만 pop\" 깃발.</b> 화살표 탭과 위로 당기는 알림이 거의 동시에 오면 <code>pop</code>이 두 번 불려 스택이 꼬일 수 있어서 막는다는 설명.", []),
        (45, 49, "<b>뒤로 가기.</b> 이미 한 번 불렸으면 무시하고, 아니면 깃발을 세운 뒤 <code>context.pop()</code>.", ["gopush"]),
        (51, 63, "<b>스크롤 알림 처리(맨 위 버전).</b> 맨 위(<code>minScrollExtent</code>)를 넘어 더 당긴 거리가 60을 넘으면 <code>_goBack()</code>. 달력 화면의 함수와 부호만 반대입니다.", []),
        (65, 69, "build. <b>오늘 날짜의 루틴 목록</b>을 읽습니다(날짜는 시·분·초를 뺀 0시로).", ["build", "family"]),
        (71, 79, "<code>Stack</code>으로 본문과 고정 + 버튼을 겹칩니다. 주석은 <code>Positioned.fill</code>이 필요한 이유(루틴이 하나뿐일 때 버튼이 짧은 내용 밑에 붙는 문제)입니다.", ["layout"]),
        (80, 91, "<code>SafeArea</code> → <code>NotificationListener</code> → <code>SingleChildScrollView</code>. 위로 당김도 감지하려면 항상 당길 수 있게 + 살짝 튕기는 물리가 필요합니다.", ["scroll"]),
        (92, 103, "<b>Column: 제목 줄 → 간격 → 카드 목록.</b> 제목 줄에 <code>onBack: _goBack</code>을 연결합니다. 카드 목록은 달력 화면과 같은 <code>RoutineCardList</code>.", []),
        (104, 120, "닫기, <b>고정 + 버튼</b>, 하단 탭바(<code>currentIndex: 1</code>).", []),
        (122, 128, "<b>\"^ 오늘 할 일\" 제목 줄 위젯.</b> 위로 당겨도 같은 곳으로 돌아가므로 화살표도 위를 가리킵니다.", []),
        (130, 165, "화살표 아이콘(원본이 이미 위쪽이라 돌릴 필요 없음)과 \"오늘 할 일\" 글자. 주석에 \"왼쪽 화살표였을 때는 반시계 90도 돌렸었다\"는 이력이 있습니다.", ["tap"]),
    ],
    next_hint="카드를 눌러 가는 <code>routine_detail_screen.dart</code>로 갑니다(<code>routine_card.dart</code> 36줄 <code>/routine/detail/:id</code>).",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_detail_screen.dart",
    title="루틴 상세: 진행 현황과 수정·삭제 메뉴",
    role="루틴 상세 (/routine/detail/:id)",
    arrive="<code>routine_card.dart</code> 33줄 <code>context.push('/routine/detail/${routine.id}', extra: routine)</code> → <code>router.dart</code> 120줄 <code>RoutineDetailScreen(routine: state.extra as Routine?)</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, <b>Riverpod</b>(이제 달력 캐시를 다시 읽으려고 다시 씁니다), SVG, 화면 이동.", []),
        (6, 12, "하단 탭바, 원형 진행률 위젯, 오류 타입, 루틴 provider, <b>수정·삭제 범위 enum</b>, 루틴 모델, <b>범위를 묻는 팝업</b>(<code>scope_dialog.dart</code>, 아래에서 봅니다).", []),
        (14, 26, "문서 주석. 하위 할 일이 몇 개 끝났는지를 진행 링 + 완료/미완료 목록으로 보여주고(읽기 전용), <b>오른쪽 위 톱니바퀴가 메뉴(수정 / 할 일 편집 / 삭제)를 연다</b>는 설명. 루틴은 처음에 <code>state.extra</code>로 받고, 수정·편집 후에는 달력 캐시에서 같은 루틴을 다시 찾아 최신 값을 보여줍니다.", []),
        (27, 33, "<b>ConsumerWidget으로 바뀌었습니다.</b> 이전에는 루틴만 받는 StatelessWidget이었는데, 최신 값을 읽고 삭제를 호출하려고 <code>ref</code>가 필요해졌습니다.", ["consumer", "null"]),
        (35, 61, "<b>톱니바퀴 메뉴(바텀시트).</b> <code>showModalBottomSheet</code>가 아래에서 올라오는 목록을 띄우고, 항목을 누르면 <code>Navigator.pop('edit')</code> 같은 <b>글자 값을 돌려주며 닫힙니다</b>. 항목은 수정, 할 일 편집, (빨간) 삭제입니다.", ["async", "tap"]),
        (62, 72, "<b>고른 항목에 따라 분기.</b> 아무것도 안 골랐으면(<code>null</code>, 바깥을 눌러 닫음) 끝냅니다. 수정과 할 일 편집은 <code>context.push</code>로 새 화면을 쌓으며 <b>루틴을 <code>extra</code>로 넘기고</b>, 삭제는 아래 함수로 갑니다. 새 문법: <code>switch</code> 문에서 <code>case</code> 뒤에 <code>break</code>가 필요 없습니다.", ["gopush", "switchexpr"]),
        (74, 93, "<b>삭제 흐름.</b> ① 범위 팝업(서버 기본값이 \"이 날짜만\"이라 그것을 권장으로 표시) ② 취소했으면 끝 ③ <code>deleteRoutine</code> 호출 ④ 서버 오류면 스낵바를 띄우고 이 화면에 남음 ⑤ 성공하면 <code>context.go('/routine')</code>으로 달력에 돌아감. 삭제는 되돌리기 어려워서 기본을 좁은 범위로 둔 서버 설계를 그대로 따릅니다.", ["dialog", "trycatch", "async"]),
        (95, 106, "<b>최신 값 다시 찾기.</b> 수정·할 일 편집이 끝나면 달력 캐시가 새로 받아집니다. 그래서 같은 날짜(<code>routinesForDateProvider(날짜)</code>)에서 <b>같은 id</b>의 루틴을 다시 찾아 쓰고(<code>.firstOrNull</code>), 못 찾으면(아직 로딩 등) 처음 받은 값을 씁니다. <code>this.routine</code>은 필드이고 아래의 <code>routine</code>은 같은 이름의 지역 변수입니다.", ["family", "null", "asyncvalue"]),
        (108, 115, "화면 틀. 루틴이 없으면(<code>extra</code> 없이 들어옴) \"루틴을 찾을 수 없어요\".", ["build"]),
        (116, 126, "스크롤 영역 안 <code>Column</code>과 헤더. 헤더에 뒤로가기와 <b>메뉴를 여는 함수</b>(<code>onMenu: () =&gt; _showMenu(...)</code>)를 넘깁니다.", ["layout", "arrow"]),
        (127, 131, "32 간격 뒤 <b>진행률 카드</b>.", []),
        (132, 139, "25 간격 뒤 <b>\"완료\" 구역</b>(<code>done</code>이 true인 할 일만).", ["maplist"]),
        (140, 147, "<b>\"미완료\" 구역</b>(<code>!s.done</code>).", []),
        (148, 156, "아래 여백 120, 하단 탭바(루틴 탭 켜짐), 괄호 닫기.", []),
        (158, 165, "<b>헤더 위젯.</b> 뒤로가기 함수와 <b>메뉴 함수</b> 둘을 받습니다. 한동안 빠졌던 톱니바퀴가 돌아왔습니다.", ["voidcallback"]),
        (166, 213, "뒤로가기 화살표, \"오늘 할 일\" 글자, <code>Spacer()</code>로 밀어낸 <b>오른쪽 끝 톱니바퀴</b>(누르면 <code>onMenu</code>).", ["tap"]),
        (215, 222, "<b>진행률 카드 위젯.</b> 루틴 하나를 받습니다.", []),
        (223, 227, "<b>비율 계산.</b> 전체 할 일 수, 끝낸 수, 비율(0개면 0.0), 백분율.", []),
        (229, 247, "흰 카드 상자와 루틴 제목.", ["layout"]),
        (248, 254, "시간이 있으면 제목 아래 \"07:30~08:30\".", ["collectionif"]),
        (255, 266, "28 간격 뒤 <b><code>ProgressRing</code></b>(가운데 \"N%\").", ["interp"]),
        (267, 280, "\"끝낸 수/전체 수\" 큰 숫자와 괄호 닫기.", ["interp"]),
        (282, 289, "<b>\"완료\" 또는 \"미완료\" 구역 위젯.</b> 소제목과 그 상태의 하위 할 일 목록.", []),
        (291, 293, "해당하는 할 일이 없으면 구역 자체를 안 그립니다.", []),
        (295, 314, "소제목 + 16 간격 + <code>Wrap</code> 안에 <code>for</code>로 할 일마다 칩.", ["collectionif"]),
        (316, 339, "<b>할 일 하나를 나타내는 흰 칩.</b> 이름 글자만.", []),
    ],
    next_hint="메뉴의 \"루틴 수정\"은 <code>routine_edit_screen.dart</code>로 갑니다. 먼저 이 화면이 쓰는 <code>ProgressRing</code>(<code>progress_ring.dart</code>)을 봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_edit_screen.dart",
    title="루틴 수정: 이름과 시간만",
    role="루틴 수정 (/routine/edit/:id)",
    arrive="<code>routine_detail_screen.dart</code> 66줄 <code>context.push('/routine/edit/${routine.id}', extra: routine)</code> → <code>router.dart</code>의 <code>edit/:id</code> 경로에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, Riverpod, 화면 이동.", []),
        (5, 11, "뒤로가기 줄, 오류 타입, 루틴 provider, 범위 enum, 루틴 모델, <b>공용 폼 위젯</b>, <b>범위 팝업</b>.", []),
        (13, 21, "문서 주석. 서버의 수정 API가 이름·시작·종료 시각 <b>세 가지만</b> 바꿀 수 있어서 날짜·반복·할 일까지 다루는 추가 폼을 <b>재사용하지 않고 화면을 따로</b> 두었습니다. 저장하면 어디까지 적용할지 묻습니다.", []),
        (22, 30, "<b>고칠 루틴을 받는 ConsumerStatefulWidget.</b> 입력 중인 값(글자, 시각)이 있어서 Stateful입니다.", ["stateful", "null"]),
        (32, 36, "<b>상태 초기값.</b> 이름과 시각을 <b>지금 루틴의 값으로 미리 채웁니다</b>(<code>widget.routine?.title ?? ''</code>, <code>parseHhmm</code>). 저장 중 여부.", ["late", "null"]),
        (38, 42, "컨트롤러 정리.", []),
        (44, 46, "스낵바 한 줄 도우미.", []),
        (48, 61, "<b>시간 고르기.</b> 표준 시간 팝업(<code>showTimePicker</code>)이고 취소하면 <code>null</code>입니다.", ["pickers", "async"]),
        (63, 74, "<b>저장 (1) 입력 검사.</b> 이름이 비었거나 종료가 시작보다 뒤가 아니면 알리고 끝냅니다. 시각을 \"분\" 단위 정수로 바꿔 비교합니다.", ["async"]),
        (75, 97, "<b>(2) 범위 묻기 → 서버에 수정.</b> 팝업에서 \"이 날짜만 / 같은 반복 전체\"를 고르고(수정은 되돌릴 수 있어 서버 기본값이 같은 반복 전체), 취소하면(<code>null</code>) 아무것도 안 합니다. 고르면 <code>updateRoutine</code>을 부르고 <b><code>context.pop()</code>으로 상세 화면에 돌아갑니다</b> — 상세가 달력 캐시를 보고 있어서 고친 값이 바로 보입니다.", ["dialog", "gopush", "invalidate"]),
        (98, 104, "서버 오류(시간 범위 오류 등)는 스낵바로, 끝나면 저장 중 표시를 끕니다.", ["trycatch"]),
        (106, 119, "build. <b>루틴이 없으면 안내</b>, 있으면 폼. 뒤로가기 줄(<code>BackHeader</code>, \"루틴 수정하기\")을 씁니다.", ["build"]),
        (120, 150, "<b>\"루틴 이름\" 라벨과 입력 칸.</b> 공용 <code>PillField</code>(알약 입력 껍데기) 안의 <code>TextField</code>입니다.", ["formfield"]),
        (151, 185, "<b>시작·종료 시간 칸 둘</b>(공용 <code>TimeField</code>)과 안내 문구: 날짜와 반복은 여기서 못 바꾸니 바꾸려면 지우고 새로 만들라는 설명.", ["layout"]),
        (186, 203, "<code>Spacer</code>로 아래로 민 <b>\"저장\" 버튼</b>. 저장 중이면 눌리지 않고 로딩 원을 보여줍니다.", []),
    ],
    next_hint="상세 메뉴의 \"할 일 편집\"은 <code>routine_steps_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_steps_screen.dart",
    title="할 일 편집: 추가·이름·삭제·순서",
    role="할 일 편집 (/routine/steps/:id)",
    arrive="<code>routine_detail_screen.dart</code> 68줄 <code>context.push('/routine/steps/${routine.id}', extra: routine)</code> → <code>router.dart</code>의 <code>steps/:id</code> 경로에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, Riverpod, 화면 이동.", []),
        (5, 11, "뒤로가기 줄, 오류 타입, 루틴 provider, 범위 enum, 루틴 모델, 공용 폼 위젯, 범위 팝업.", []),
        (13, 23, "문서 주석. <b>저장 버튼 없이 각 동작이 눌리는 즉시 서버에 반영</b>되고, 서버가 바꾸는 범위가 동작마다 달라서 화면에 안내한다는 설명: 추가는 범위를 고르고, <b>이름 변경·삭제·순서 변경은 이 날짜에만</b> 적용됩니다. 지난 날짜는 서버가 막지 않지만 <b>이행률(분모)이 바뀌어 지난 성적이 달라지므로 앱에서 막습니다</b>.", []),
        (24, 32, "고칠 루틴을 받는 <code>ConsumerStatefulWidget</code>.", ["stateful", "null"]),
        (34, 38, "<b>새 할 일 입력 컨트롤러와 <code>_busy</code>.</b> 서버 호출이 진행되는 동안은 다른 편집을 막아 요청이 겹치지 않게 합니다.", ["formfield"]),
        (40, 48, "컨트롤러 정리와 스낵바 도우미.", []),
        (50, 62, "<b>서버 호출을 감싸는 공통 함수 <code>_run</code>.</b> 진행 표시를 켜고, 동작을 실행하고, <code>ApiException</code>이면 알리고, 끝나면 끕니다. <b>성공했는지(<code>true</code>/<code>false</code>)를 돌려줍니다.</b> 함수를 인자로 받는 타입 <code>Future&lt;void&gt; Function()</code>에 주목하세요.", ["trycatch", "voidcallback", "async"]),
        (64, 79, "<b>추가.</b> 입력이 비었으면 무시하고, 범위 팝업(서버 기본값 같은 반복 전체)으로 어디에 추가할지 묻고, 성공하면 입력 칸을 비웁니다.", ["dialog"]),
        (81, 100, "<b>이름 변경.</b> 이름을 담은 컨트롤러로 입력 팝업을 띄웁니다. 취소·빈 값·같은 이름이면 서버를 안 부릅니다. 팝업이 끝나면 직접 만든 컨트롤러를 <code>dispose</code>해서 정리합니다.", ["dialog", "null"]),
        (102, 119, "<b>삭제.</b> 확인창에서 \"지우기\"를 눌렀을 때만 서버에 보냅니다. 문구에 \"이 날짜의 루틴에서\"라고 적어 범위를 알립니다.", ["dialog"]),
        (121, 128, "<b>순서 변경.</b> 끌어서 옮긴 결과(<code>oldIndex</code> → <code>newIndex</code>)로 새 순서의 리스트를 만들어(<code>removeAt</code> 후 <code>insert</code>) 서버에 보냅니다. <code>onReorderItem</code>이 주는 새 위치는 이미 \"빼고 난 뒤 기준\"이라 따로 보정하지 않습니다.", ["spread"]),
        (130, 145, "build 시작. <b>달력 캐시에서 같은 날짜·같은 id의 루틴을 다시 찾아</b> 편집 직후의 최신 할 일 목록을 보여주고, <b>오늘 이전이면 편집을 막습니다</b>(<code>editable</code>).", ["build", "family", "null"]),
        (146, 175, "화면 틀, 뒤로가기 줄, 안내 문구. 편집 가능하면 \"이름 변경·삭제·순서 변경은 이 날짜에만…\", 지난 날짜면 \"바꿀 수 없어요\"로 바뀝니다.", ["layout"]),
        (176, 205, "<b>할 일 목록(<code>ReorderableListView</code>).</b> 끌어서 순서를 바꿀 수 있는 목록입니다. 기본 끌기 손잡이를 끄고(<code>buildDefaultDragHandles: false</code>) 줄마다 직접 만든 손잡이만 쓰며, 줄마다 <b>고유 키(할 일 id)</b>가 있어야 어떤 줄을 끌었는지 구분됩니다.", ["listview"]),
        (206, 239, "<b>할 일 추가 입력 칸</b>(편집 가능할 때만)과 괄호 닫기. 엔터나 + 아이콘이 <code>_add</code>를 부르고, 서버 호출 중에는 꺼집니다.", ["collectionif"]),
        (241, 251, "<b>할 일 한 줄 위젯.</b> 끌기 손잡이 + 번호 배지 + 이름(누르면 이름 변경) + 삭제 아이콘.", []),
        (253, 257, "필드 다섯: 번호, 할 일, 편집 가능 여부, 이름 변경·삭제 함수.", ["voidcallback"]),
        (259, 314, "편집할 수 없으면 손잡이·삭제를 안 그리고 이름도 눌려도 반응이 없습니다. 번호 배지는 <b>끝난 할 일이면 하늘색</b>입니다. <code>ReorderableDragStartListener</code>가 이 손잡이를 끌 때만 순서 변경이 시작되게 합니다.", ["tap"]),
    ],
    next_hint="두 화면이 쓰는 <code>ChangeScope</code>(<code>change_scope.dart</code>)를 봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/domain/change_scope.dart",
    title="\"어디까지 적용할까\" 두 가지",
    role="수정·삭제 범위 enum",
    arrive="<code>routine_edit_screen.dart</code>, <code>routine_steps_screen.dart</code>, <code>routine_repository.dart</code>의 <code>scope</code> 인자에서 왔습니다.",
    chunks=[
        (1, 3, "문서 주석. 반복 루틴은 날짜마다 따로 저장된 행이 같은 <code>seriesId</code>로 묶여 있어서 \"어디까지 적용할지\"를 고르게 한다는 이유.", []),
        (4, 11, "<b><code>enum ChangeScope</code>.</b> <code>single</code>(그 날짜만)과 <code>series</code>(같은 반복의 <b>오늘 이후</b> 전체, 고른 날짜 포함). 서버는 <b>지난 날짜의 같은 반복 루틴은 건드리지 않습니다</b> — 지난 기록은 그때 하기로 했던 내용을 남겨야 해서입니다.", ["enum"]),
        (13, 17, "<b>서버 쿼리로 보낼 글자(<code>code</code>).</b> 이름 있는 enum 값마다 <code>'single'</code>, <code>'series'</code>를 달아 둬서 <code>queryParameters: {'scope': scope.code}</code>로 그대로 씁니다.", ["constructor"]),
    ],
    next_hint="이 값을 사용자에게 묻는 팝업 <code>scope_dialog.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/widgets/scope_dialog.dart",
    title="범위를 묻는 팝업",
    role="범위 선택 팝업",
    arrive="<code>routine_detail_screen.dart</code> 77줄 <code>showScopeDialog(...)</code>, 수정 화면, 할 일 편집 화면에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯과 범위 enum.", []),
        (5, 10, "문서 주석. 고른 범위를 돌려주고 취소하면 <code>null</code>. 서버는 이 루틴이 반복에 속하는지 알려 주지 않아서 <b>하루짜리 루틴에도 질문이 뜹니다</b>. 서버의 기본값(수정·추가는 같은 반복 전체, 삭제는 그 날짜만)에 \"(권장)\"을 붙입니다.", []),
        (11, 16, "<b>팝업을 띄우는 함수.</b> 반환 타입 <code>Future&lt;ChangeScope?&gt;</code>은 \"나중에 범위가 오거나, 취소하면 null\"입니다. 제목·설명·권장 범위를 이름 있는 인자로 받아 세 곳(수정·삭제·추가)이 문구만 바꿔 재사용합니다.", ["async", "null", "generic"]),
        (17, 28, "<code>SimpleDialog</code>(선택지 목록형 팝업)와 위쪽 설명 글.", ["dialog"]),
        (29, 36, "<b>선택지를 enum 값에서 만듭니다.</b> <code>for (final scope in ChangeScope.values)</code>로 두 개의 옵션을 만들고, 누르면 <code>Navigator.pop(scope)</code>로 그 값을 돌려주며 닫힙니다. 권장 범위에만 \" (권장)\"을 붙입니다.", ["collectionif"]),
        (37, 44, "<b>\"취소\"</b>는 값 없이 <code>pop()</code>해서 <code>null</code>을 돌려줍니다.", []),
        (46, 49, "<b>범위 이름을 글자로 바꾸는 <code>switch</code> 식.</b> 이름 앞 <code>_</code>라 이 파일 안에서만 씁니다.", ["switchexpr", "private"]),
    ],
    next_hint="수정·할 일 편집 화면이 공유하는 입력 위젯 <code>routine_form_widgets.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/widgets/routine_form_widgets.dart",
    title="추가·수정 폼이 같이 쓰는 입력 칸",
    role="공용 폼 위젯",
    arrive="<code>add_routine_screen.dart</code>, <code>routine_edit_screen.dart</code>, <code>routine_steps_screen.dart</code>의 <code>PillField</code>·<code>TimeField</code>에서 왔습니다.",
    chunks=[
        (1, 1, "Flutter 위젯.", []),
        (3, 7, "문서 주석(처음에는 추가 폼 파일 안에만 있었는데 <b>수정 화면이 생기면서 공용으로 뺐다</b>)과 색 상수 둘. 앞의 <code>k</code>는 상수 관례.", ["const"]),
        (9, 33, "<b><code>PillField</code>: 흰 알약 입력 껍데기.</b> 높이 55, 모서리 21, 옅은 그림자. 안에 무엇이든 <code>child</code>로 받고, <code>onTap</code>이 있으면 눌리는 <code>InkWell</code>로 감쌉니다. 앞의 <code>_</code>가 사라져(<code>_PillField</code> → <code>PillField</code>) 다른 파일에서도 씁니다.", ["class", "tap"]),
        (35, 60, "<b><code>TimeField</code>: \"00:00 부터\" 시간 버튼.</b> <code>PillField</code> 안에 시각과 안내 글자를 양끝으로 놓습니다. 누르면 부모가 시간 팝업을 띄웁니다.", ["layout"]),
        (62, 64, "<b><code>TimeOfDay</code> → 서버 형식 \"07:30\".</b>", ["arrow"]),
        (66, 74, "<b>서버 형식 → <code>TimeOfDay</code>(안전하게).</b> <code>null</code>·빈 글자·형식 오류면 <code>fallback</code>(00:00)을 돌려줍니다. <code>int.tryParse</code>는 숫자가 아니면 예외 대신 <code>null</code>을 줍니다.", ["null"]),
    ],
    next_hint="상세 화면이 쓰는 <code>ProgressRing</code>(<code>progress_ring.dart</code>)으로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/app/widgets/progress_ring.dart",
    title="직접 그리는 원형 진행률",
    role="원형 게이지",
    arrive="<code>routine_detail_screen.dart</code> 166줄 <code>ProgressRing(ratio: ..., center: ...)</code>에서 왔습니다. 기기 통계 화면도 같은 위젯을 씁니다.",
    chunks=[
        (1, 3, "<code>dart:math</code>(원주율 <code>math.pi</code> 등), Flutter 위젯.", []),
        (5, 10, "문서 주석. Figma 원본은 66% 상태 이미지 하나뿐이라 <b>비율이 바뀌는 화면에는 못 써서</b> 직접 그린다는 이유. 회색 트랙 위에 파란 호를 12시 방향에서 시계 방향으로 비율만큼 그립니다.", []),
        (11, 16, "<b>비율(0.0~1.0), 가운데 위젯, 지름(기본 200)</b>을 받는 위젯.", ["constructor"]),
        (18, 35, "<code>Stack</code>으로 <b>그림(<code>CustomPaint</code>)과 가운데 글자를 겹칩니다.</b> 지름 크기의 정사각형 안에서 가운데 정렬.", ["layout", "build"]),
        (37, 40, "<b>실제로 그리는 클래스.</b> <code>CustomPainter</code>를 상속하고 비율을 받습니다.", ["painter"]),
        (42, 44, "트랙 회색, 진행 하늘색, 선 굵기 18.", ["const"]),
        (46, 57, "<b>트랙(바탕 원) 그리기.</b> 반지름은 \"짧은 변 − 선 굵기\"의 절반(선이 상자 밖으로 안 나가게). <code>Paint()</code>에 <code>..color = ..</code>처럼 <code>..</code>로 속성을 이어 적고, 끝을 둥글게(<code>StrokeCap.round</code>) 해서 <code>drawCircle</code>.", ["painter"]),
        (59, 73, "<b>진행 호 그리기.</b> 비율이 0 이하면 여기서 끝. 아니면 <code>drawArc</code>로 -90°(12시)부터 <code>2π × ratio</code>만큼(360° 최대) 그립니다. <code>clamp(0.0, 1.0)</code>은 범위를 벗어난 값을 잘라 줍니다.", ["painter"]),
        (75, 78, "<b>다시 그릴지 판단.</b> 비율이 바뀌었을 때만 다시 그려 불필요한 작업을 줄입니다. 4장 끝.", ["arrow"]),
    ],
    next_hint="4장 끝. 5장에서 프로필 탭(하단 탭 3번)과 계정 화면들을 읽습니다.",
))
