# -*- coding: utf-8 -*-
# 5장: 프로필과 계정 (내 정보 탭 → 설정 카드 → 프로필 관리/아바타 → 사용자 설정 → 언어/로그인 기록)

CONCEPTS_CH = {
    "dialog": ("showDialog 와 AlertDialog", "<code>showDialog&lt;bool&gt;(...)</code>는 화면 위에 팝업을 띄우고, 사용자가 버튼으로 닫을 때 <code>Navigator.of(context).pop(값)</code>에 넣은 값을 돌려줍니다. 그래서 <code>final confirmed = await showDialog&lt;bool&gt;(...)</code>로 \"취소(false)\"인지 \"확인(true)\"인지 받습니다. 팝업 바깥을 눌러 닫으면 <code>null</code>이 오므로 <code>confirmed == true</code>로 비교하는 것이 안전합니다. <code>AlertDialog</code>는 제목·내용·버튼 줄이 있는 표준 확인창입니다."),
    "fileio": ("기기 파일 다루기 (File · FileImage · path)", "<code>dart:io</code>의 <code>File(경로)</code>는 기기 안 파일입니다. <code>FileImage(File(경로))</code>는 그 파일을 이미지로 보여주고, <code>.copy(새 경로)</code>로 복사합니다. <code>path</code> 패키지의 <code>p.join(폴더, 이름)</code>은 경로를 안전하게 이어 붙이고 <code>p.extension(경로)</code>은 \".jpg\" 같은 확장자를 알려줍니다. 웹에서는 쓸 수 없는 모바일·데스크톱 전용 기능입니다."),
    "record": ("레코드 (a, b) 와 $1", "<code>('iPhone 13', '2일 전 접속')</code>처럼 괄호로 묶은 값은 <b>레코드</b>(이름 없는 작은 묶음)입니다. 첫째 값은 <code>$1</code>, 둘째는 <code>$2</code>로 꺼냅니다. 클래스를 따로 만들 만큼 크지 않은 묶음에 편합니다. 문자열 보간의 <code>$이름</code>과 같은 기호지만 <code>entry.$1</code>은 \"entry 레코드의 첫 값\"입니다."),
    "hittest": ("HitTestBehavior.opaque", "<code>GestureDetector</code>는 기본적으로 <b>실제로 그려진 자식(글자·아이콘)</b>에만 반응합니다. 글자와 화살표 사이 빈 공간을 눌러도 반응하게 하려면 <code>behavior: HitTestBehavior.opaque</code>로 \"이 위젯이 차지한 영역 전체가 눌림 대상\"이라고 알려야 합니다. 줄 전체를 눌러야 하는 설정 목록에서 필수입니다."),
}

STOPS_CH = []

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/presentation/profile_screen.dart",
    title="내 정보 탭",
    role="프로필 탭 (/profile)",
    arrive="하단 탭바 네 번째 아이콘 → <code>bottom_nav_bar.dart</code> 38줄 <code>context.go('/profile')</code> → <code>router.dart</code> 193줄 <code>ProfileScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 1, "<code>dart:io</code>. 기기 안 <code>File</code>을 쓰려고 가져옵니다(프로필 사진 파일).", ["fileio"]),
        (3, 5, "Flutter 위젯, Riverpod, 화면 이동.", []),
        (7, 12, "하단 탭바, <b>계정 정보 provider</b>(<code>currentUserProvider</code>, 1장의 <code>auth_providers.dart</code>), 프로필 사진 provider, 설정 카드 위젯들.", []),
        (14, 20, "문서 주석. 프로필 카드(아바타+이름) 아래 \"앱 설정\"·\"계정\" 카드, 로그아웃·탈퇴·앱 버전 카드. Figma에 있던 \"이용 안내\" 카드는 보여줄 문서가 없어서 뺐다는 이력.", []),
        (21, 26, "스위치 값이 바뀌므로 Stateful, provider도 읽어서 <code>ConsumerStatefulWidget</code>.", ["stateful"]),
        (28, 29, "State와 색 상수.", []),
        (31, 35, "<b>알림·다크모드 스위치의 상태 둘.</b> 주석: 아직 실제 알림이나 앱 테마와 연결되지 않아서 <b>이 화면 안에서만 켜고 끌 수 있는 자리 잡기</b>입니다(테마는 <code>theme.dart</code>에 고정).", []),
        (37, 43, "<b>build 시작: provider 두 개 읽기.</b> 계정 정보(<code>currentUserProvider</code>)에서 이름을, 프로필 사진 경로(<code>avatarPathProvider</code>)를 읽습니다. 로딩·에러 중에는 이름이 빈 문자열로 순간적으로 비어 보일 수 있다고 주석이 설명합니다. 둘 다 <code>.value</code>로 꺼냅니다.", ["build", "asyncvalue", "null"]),
        (44, 52, "화면 틀, 스크롤, 좌우 28 여백, <code>Column</code>.", ["scroll", "layout"]),
        (53, 57, "\"내 정보\" 제목과 24 간격.", []),
        (58, 61, "<b>프로필 줄 전체가 눌립니다.</b> 누르면 <code>/profile/edit</code>(프로필 관리)로 push. 안은 <code>Row</code>.", ["tap", "gopush"]),
        (62, 69, "<b>원형 아바타.</b> 사진 경로가 있으면 <code>FileImage(File(경로))</code>로 기기 안 사진을, 없으면(<code>null</code>) 회색 배경에 사람 아이콘을 보여줍니다. 같은 <code>avatarPath == null ? A : B</code> 판단이 두 번 반복됩니다.", ["fileio", "null"]),
        (70, 89, "12 간격 뒤에 <b>이름 + \"프로필 관리 &gt;\"</b> 두 줄. 이름 글자가 방금 읽은 <code>userName</code>입니다.", []),
        (90, 111, "<b>\"앱 설정\" 카드.</b> <code>SettingsCard</code>(제목 + 줄들)에 줄 셋: \"언어 — 한국어\"(눌러서 언어 화면), \"알림\" 스위치, \"다크모드\" 스위치. 스위치는 값을 이 State의 변수와 연결하고 바뀌면 <code>setState</code>로 저장합니다.", ["valuechanged"]),
        (112, 125, "<b>\"계정\" 카드.</b> \"사용자 설정\"과 \"로그인 기록\" 줄, 각각 다른 화면으로 push.", []),
        (126, 137, "<b>제목 없는 마지막 카드.</b> \"앱 버전 0.1.0\"(값만 보여주는 줄), \"로그아웃\", 빨간 \"탈퇴하기\". 누르면 확인창 함수를 부릅니다.", []),
        (138, 144, "괄호 닫기와 하단 탭바(<code>currentIndex: 3</code> — 내 정보 탭 켜짐).", []),
        (146, 168, "<b>로그아웃 확인창.</b> <code>showDialog&lt;bool&gt;</code>로 \"취소 / 로그아웃하기\" 팝업을 띄우고 결과를 <code>await</code>로 기다립니다. <code>true</code>이면 <code>authRepository.logout()</code>(서버의 <code>access_uuid</code>를 비우고 기기 쪽 세션도 지움)을 기다린 뒤 <code>context.go('/login')</code>으로 로그인 화면에 갑니다. 팝업 안의 <code>context</code>가 바깥과 같은 이름이라 헷갈리기 쉽습니다. 서버 호출이 실패해도 로컬 세션은 지워진다고 주석이 설명합니다.", ["dialog", "async", "null"]),
        (170, 199, "<b>탈퇴하기 확인창과 실행.</b> 확인창은 위와 같은 구조이고, <code>true</code>이면 <code>accountActions.withdraw()</code>를 부릅니다(다음 정류장). 성공하면 <code>/login</code>으로 가고, 서버가 실패하면(네트워크 오류 등) <b>아무것도 지우지 않고</b> 오류 문구를 스낵바로 보여준 뒤 이 화면에 남습니다(<code>on ApiException catch</code> 안의 <code>return</code>). 지금까지의 \"로그아웃과 똑같은 동작\"을 진짜 탈퇴로 바꾼 부분입니다.", ["dialog"]),
    ],
    next_hint="탈퇴 처리의 본체 <code>account_actions.dart</code>로 갑니다. 그 다음 <code>SettingsCard</code>(<code>settings_card.dart</code>)를 봅니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/auth/data/account_actions.dart",
    title="탈퇴 처리: 서버 먼저, 그 다음 기기 정리",
    role="탈퇴 로직",
    arrive="<code>profile_screen.dart</code> 191줄 <code>ref.read(accountActionsProvider).withdraw()</code>, <code>user_settings_screen.dart</code> 102줄에서 왔습니다.",
    chunks=[
        (1, 1, "Riverpod.", []),
        (3, 11, "필요한 재료가 많습니다: 오류 타입, Hive 도구, <b>지워야 할 캐시를 가진 provider들</b>(기기·알림·프로필 사진·루틴·템플릿), 인증 provider. 한 기능이 다른 기능의 provider를 여럿 아는 드문 파일입니다.", []),
        (13, 13, "쓰기 기능 묶음 provider. 기기·루틴·템플릿·아바타의 <code>*Actions</code>와 같은 패턴입니다.", ["provider"]),
        (15, 19, "<code>Ref</code>를 받는 클래스.", []),
        (21, 27, "<b>순서가 핵심입니다.</b> 서버를 <b>먼저</b> 부르고 성공했을 때만 기기 데이터를 지웁니다. 서버가 실패했는데 로컬만 지우면 계정은 남고 기기 데이터만 사라지기 때문입니다. 예외로 \"이미 탈퇴한 계정\"이나 \"세션 무효(401)\"는 서버가 이미 정리된 상태라 로컬 정리까지 진행합니다.", []),
        (28, 36, "<b>실행.</b> <code>deleteUser()</code>를 부르고, <code>ApiException</code>이 오면 코드가 <code>USER_NOT_FOUND</code>이거나 상태가 401일 때만 삼키고(<code>alreadyGone</code>) 나머지는 <code>rethrow</code>로 화면에 되던집니다. 그 뒤 로컬 정리.", ["trycatch", "async"]),
        (38, 41, "<b>무엇을 지우는지</b>: 프로필 사진 파일, Hive 상자 전부(로그인 세션 포함), 메모리 캐시. 마지막 것을 빼먹으면 다음에 로그인한 계정에 이전 이름·루틴이 앱을 다시 켜기 전까지 보일 수 있다는 주석.", []),
        (42, 44, "<b>파일과 상자 삭제.</b> 사진은 경로만 Hive에 있고 파일은 따로 있어서 <code>deleteAvatarFile()</code>(다음에 볼 <code>avatar_providers.dart</code>)을 먼저 부르고, 이어서 <code>LocalStorageService().deleteAllBoxes()</code>로 상자를 지웁니다. 로그인 세션이 든 <code>auth</code> 상자도 같이 지워져서 따로 로그아웃 처리가 필요 없습니다.", []),
        (46, 56, "<b>캐시 비우기.</b> <code>ref.invalidate(...)</code>를 아홉 번: 내 정보, 자녀 목록과 선택, 루틴, 템플릿, 기기 목록, 홈 캐러셀 번호, 사진 경로, 알림. 각각 낡은 값을 버려 다음에 읽을 때 새로(빈 상태로) 불러오게 합니다.", ["invalidate"]),
    ],
    next_hint="사진 파일 삭제 함수는 <code>avatar_providers.dart</code>에, 설정 카드는 <code>settings_card.dart</code>에 있습니다. 다음은 <code>settings_card.dart</code>입니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/presentation/widgets/settings_card.dart",
    title="설정 카드와 줄 세 종류",
    role="설정 카드 위젯",
    arrive="<code>profile_screen.dart</code> 91·113·127줄 <code>SettingsCard(...)</code>, 94줄 <code>SettingsChevronRow</code>, 100줄 <code>SettingsSwitchRow</code>, 129줄 <code>SettingsValueRow</code>에서 왔습니다.",
    chunks=[
        (1, 2, "Flutter 위젯, SVG.", []),
        (4, 8, "<b>소제목 + 줄 목록</b>을 담는 흰 카드. 제목은 선택이라 <code>this.title</code>(null 가능), 줄들은 <code>required this.children</code>입니다.", ["constructor"]),
        (10, 13, "제목(<code>String?</code>)과 줄 위젯 목록(<code>List&lt;Widget&gt;</code>), 색 상수.", ["null"]),
        (15, 26, "<b>흰 카드 틀.</b> 가로 꽉 채움, 모서리 19, 옅은 그림자, 안쪽 여백 좌우 23·위아래 16.", ["build"]),
        (27, 42, "<b>카드 안 내용.</b> 제목이 있을 때만 제목 글자 + 12 간격(<code>if (title != null) ...[</code>, <code>title!</code>의 <code>!</code>는 null 아님을 보증). 그 아래 <code>for</code>로 줄을 쌓고, 첫 줄 말고는 앞에 16 간격을 넣습니다.", ["collectionif", "null"]),
        (43, 45, "괄호 닫기.", []),
        (47, 63, "<b>줄 종류 1: 라벨 + (선택) 값 + 화살표.</b> 옵션 인자가 많습니다: <code>value</code>(오른쪽 글자), <code>valueColor</code>, <code>danger</code>(빨간 위험 표시, 기본 false), <code>onTap</code>.", ["constructor", "voidcallback"]),
        (65, 66, "색 상수(일반, 위험 빨강).", []),
        (68, 70, "위험(<code>danger</code>)이면 빨강, 아니면 일반 글자색.", []),
        (71, 89, "<b>한 줄 그리기.</b> 라벨, <code>Spacer</code>로 오른쪽 끝에 밀어낸 뒤 값(있을 때만), \">\" 화살표(<code>quarterTurns: 1</code>로 돌림). 위험이면 화살표도 빨갛게 덮어씁니다.", ["layout", "collectionif"]),
        (90, 97, "<b>눌림이 없으면 그냥 줄, 있으면 <code>GestureDetector</code>로 감쌉니다.</b> <code>HitTestBehavior.opaque</code>가 핵심: 이게 없으면 글자와 화살표 사이의 빈 공간을 눌러도 반응하지 않습니다. 주석이 이유를 자세히 적어 두었습니다.", ["hittest"]),
        (99, 113, "<b>줄 종류 2: 라벨 + 스위치.</b> 현재 값과 \"바뀌면 부를 함수\" 둘 다 필수입니다. <code>ValueChanged&lt;bool&gt;</code>은 true/false를 받는 함수 타입입니다.", ["valuechanged"]),
        (115, 129, "<b>라벨 → Spacer → <code>Switch</code>.</b> Material 기본 스위치 위젯이고 켜졌을 때 바 색만 브랜드 하늘색으로 바꿨습니다.", ["build"]),
        (131, 140, "<b>줄 종류 3: 라벨 + 값만.</b> 눌러도 반응이 없는 줄(예: \"앱 버전\").", []),
        (141, 151, "라벨, Spacer, 값 글자. 세 줄이 같은 <code>Row</code> 모양이라 서로 어긋나지 않습니다.", []),
    ],
    next_hint="<code>profile_screen.dart</code> 41줄 <code>avatarPathProvider</code>를 Ctrl+클릭해 <code>avatar_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/data/avatar_providers.dart",
    title="프로필 사진 고르기·저장",
    role="아바타 provider",
    arrive="<code>profile_screen.dart</code> 43줄 <code>ref.watch(avatarPathProvider)</code>, <code>profile_edit_screen.dart</code> 81줄 <code>avatarActionsProvider</code>에서 왔습니다.",
    chunks=[
        (1, 1, "<code>dart:io</code>(기기 파일).", ["fileio"]),
        (3, 6, "Riverpod, <b>사진 고르기 패키지</b>(<code>image_picker</code>), 경로 이어 붙이기(<code>path</code>, <code>as p</code>는 이름을 <code>p</code>로 줄여 쓰겠다는 뜻), 앱 전용 폴더 위치(<code>path_provider</code>).", []),
        (8, 9, "Hive 도구와 아바타 저장소.", []),
        (11, 11, "이 파일 안에서만 쓰는 Hive 도구 provider(<code>_</code>).", ["private"]),
        (13, 15, "아바타 저장소 provider.", ["provider"]),
        (17, 21, "<b>사진 경로 provider.</b> 문자열이거나 없으면 <code>null</code>(<code>FutureProvider&lt;String?&gt;</code>). 한 번도 사진을 안 골랐으면 화면이 기본 사람 아이콘을 보여줍니다.", ["asyncvalue", "null"]),
        (23, 23, "쓰기 기능 묶음 provider.", []),
        (25, 28, "<code>Ref</code>를 받는 쓰기 클래스.", []),
        (30, 37, "<b>갤러리에서 사진 고르기.</b> <code>ImagePicker().pickImage(...)</code>가 폰 갤러리를 열고, 고르면 파일 정보를, 취소하면 <code>null</code>을 돌려줍니다. 취소면 아무것도 바꾸지 않고 끝냅니다.", ["async", "pickers"]),
        (39, 43, "<b>앱 전용 폴더로 복사.</b> 갤러리 원본은 앱이 지워지거나 옮겨지면 사라질 수 있으니 앱이 계속 읽을 수 있는 안정된 위치(<code>getApplicationDocumentsDirectory</code>)로 복사합니다. 파일 이름을 <b>항상 같은 이름</b>(<code>profile_avatar.확장자</code>)으로 써서 새 사진이 옛 사진을 덮어쓰게 해 기기에 파일이 쌓이는 것을 막습니다.", ["fileio"]),
        (45, 47, "<b>경로를 Hive에 저장하고 <code>invalidate</code>.</b> 사진 파일 자체가 아니라 <b>경로 글자</b>만 저장합니다. 백엔드에 이미지 업로드 API가 없기 때문입니다. 낡은 캐시를 버려서 내 정보 탭·프로필 관리 화면이 새 사진을 바로 보여줍니다.", ["invalidate"]),
        (49, 58, "<b>프로필 사진 파일 지우기(탈퇴용).</b> 경로만 Hive에 있고 파일은 앱 폴더에 따로 있어서, 상자를 지워도 사진 파일은 남기 때문에 따로 지웁니다. 경로가 없거나(<code>null</code>) 파일이 이미 없으면 아무것도 안 합니다. <code>AccountActions</code>가 상자를 지우기 <b>전에</b> 이것을 불러야 경로를 읽을 수 있습니다.", ["fileio", "null"]),
    ],
    next_hint="<code>LocalAvatarRepository</code>를 보려고 <code>avatar_repository.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/data/avatar_repository.dart",
    title="사진 경로를 'profile' 상자에",
    role="아바타 저장소(Hive)",
    arrive="<code>avatar_providers.dart</code> 14줄 <code>LocalAvatarRepository(...)</code>에서 왔습니다.",
    chunks=[
        (1, 1, "Hive.", []),
        (3, 3, "Hive 도구.", []),
        (5, 12, "<b>저장소 약속과 설계 이유.</b> 서버에 아바타 업로드 API가 없어서 이미지는 올리지 않고 경로만 로컬에 남기는 \"로컬 우선\" 패턴이라는 설명. 읽기(<code>String?</code>)와 쓰기 두 함수.", ["abstract"]),
        (14, 15, "Hive 구현체.", []),
        (17, 19, "<b>상자 이름 <code>'profile'</code>과 키 <code>'avatar_path'</code>.</b> 기기·루틴 상자는 \"id → 항목\" 여러 개를 담았지만, 여기는 한 개의 값만 담는 <b>키-값 저장소</b>로 씁니다.", []),
        (21, 21, "상자를 여는 getter.", ["getter"]),
        (23, 32, "<b>읽기.</b> 저장된 Map에서 <code>raw['path']</code>를 꺼냅니다. <code>LocalStorageService.openBox</code>가 <code>Box&lt;Map&gt;</code>만 열어주기 때문에 문자열 하나도 <code>{'path': ...}</code>로 한 번 감싸 저장한다고 주석이 설명합니다. 값이 없으면 null.", ["null"]),
        (34, 39, "<b>쓰기.</b> <code>{'path': 경로}</code>로 감싸 <code>put</code>합니다.", []),
    ],
    next_hint="프로필 줄을 누르면 가는 <code>profile_edit_screen.dart</code>로 갑니다(<code>profile_screen.dart</code> 57줄 <code>/profile/edit</code>).",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/presentation/profile_edit_screen.dart",
    title="프로필 관리: 사진과 이름 바꾸기",
    role="프로필 관리 (/profile/edit)",
    arrive="<code>profile_screen.dart</code> 59줄 <code>context.push('/profile/edit')</code> → <code>router.dart</code> 196줄 <code>ProfileEditScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 1, "<code>dart:io</code>(사진 파일).", ["fileio"]),
        (3, 5, "Flutter 위젯, Riverpod, 화면 이동.", []),
        (7, 10, "뒤로가기 줄 공용 위젯(<code>BackHeader</code>), <code>ApiException</code>, 계정 provider·사용자 저장소, 아바타 provider.", []),
        (12, 20, "문서 주석. 사진은 서버에 올리지 않고 기기에만 저장, 닉네임은 <code>PATCH /users/me</code>(백엔드 필드 이름은 <code>name</code>)로 저장하며, 온보딩 1단계의 \"보호자 성명\"과 <b>같은 값</b>이라는 설명.", []),
        (21, 26, "입력과 로딩 상태가 있어서 <code>ConsumerStatefulWidget</code>.", ["stateful"]),
        (28, 31, "<b>상태 셋.</b> 닉네임 칸 컨트롤러, <code>_prefilled</code>(처음 한 번만 채웠는가), <code>_saving</code>(저장 중).", ["formfield"]),
        (33, 37, "컨트롤러 정리.", []),
        (39, 41, "<b>\"완료\" 처리 시작.</b> 로딩을 켜고 실패할 수 있는 일을 시작.", ["trycatch"]),
        (42, 47, "<b>이름 저장.</b> 1장의 <code>updateMe(name: ...)</code>를 다시 씁니다(서버에 PATCH). 이어서 <b><code>ref.invalidate(currentUserProvider)</code></b>로 캐시한 계정 정보를 버려서, 이 화면을 나가면 \"내 정보\" 탭과 사용자 설정이 새 이름을 다시 받아오게 합니다. 그 뒤 <code>context.pop()</code>으로 한 장 걷어냅니다.", ["invalidate", "gopush"]),
        (48, 54, "실패하면 스낵바, 끝나면 로딩 끄기. 로그인 화면과 같은 구조입니다.", []),
        (56, 66, "<b>서버에서 받은 이름을 입력 칸에 한 번만 채우기.</b> 이름이 도착했고(<code>name != null</code>) 아직 안 채웠으면(<code>!_prefilled</code>) 컨트롤러에 넣고 깃발을 세웁니다. 주석: <b>build마다 덮어쓰면 사용자가 타이핑 중인 글자가 지워지기 때문에</b> 깃발로 최초 1회만 합니다. build 안에서 값을 대입하는 드문 경우입니다.", ["build", "asyncvalue"]),
        (67, 78, "프로필 사진 경로를 읽고, 화면 틀(흰 배경, 좌우 26 여백)을 엽니다. 맨 위에 20 간격과 <code>BackHeader</code>(\"프로필 관리\", 뒤로가기는 <code>pop</code>), 40 간격.", ["layout"]),
        (79, 92, "<b>큰 원형 아바타(반지름 45).</b> 누르면 <code>pickAndSaveAvatar()</code>로 갤러리를 엽니다. <code>Stack</code>으로 아바타 위에 \"+\" 배지를 겹칩니다(<code>clipBehavior: Clip.none</code>은 배지가 바깥으로 삐져나가도 잘리지 않게).", ["tap", "fileio"]),
        (93, 109, "<b>오른쪽 아래 \"+\" 배지.</b> <code>Positioned(right: -2, bottom: -2)</code>로 아바타 모서리 바깥에 걸치게 놓은 26×26 하늘색 원.", []),
        (110, 127, "<b>\"닉네임\" 라벨과 입력 칸.</b> 높이 44, 둥근 테두리 상자 안에 밑줄 없는 <code>TextField</code>. 컨트롤러를 연결합니다.", ["formfield"]),
        (128, 128, "남는 공간을 먹는 <code>Spacer</code>. 버튼을 맨 아래로 밀어냅니다.", []),
        (129, 148, "<b>\"완료\" 버튼.</b> 저장 중이면 눌리지 않고(<code>onPressed: null</code>) 로딩 원을 보여주며, 누르면 <code>_submit</code>.", []),
        (149, 156, "아래 여백과 괄호 닫기들.", []),
    ],
    next_hint="뒤로 가서 <code>profile_screen.dart</code> 118줄의 \"사용자 설정\"을 눌러 <code>user_settings_screen.dart</code>로 갑니다. 뒤로가기 줄은 <code>app/widgets/back_header.dart</code>도 같이 봅니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/app/widgets/back_header.dart",
    title="\"‹ 제목\" 상단 바",
    role="공용 뒤로가기 줄",
    arrive="<code>profile_edit_screen.dart</code> 77줄 <code>BackHeader(title: '프로필 관리', onBack: ...)</code>에서 왔습니다. 루틴·기기·내 정보의 여러 화면이 같은 모양을 반복해서 공용으로 뺐습니다.",
    chunks=[
        (1, 2, "Flutter 위젯, SVG.", []),
        (4, 6, "문서 주석. 뒤로가기 화살표 + 제목 + (선택) 오른쪽 끝 위젯으로 이뤄진 줄을 여러 화면이 반복해서 쓰길래 공용 위젯으로 뺐다는 이유.", []),
        (7, 8, "<b>제목, 뒤로가기 함수, 선택 위젯(<code>trailing</code>, 예: 톱니바퀴)</b>을 받습니다. <code>Widget?</code>은 \"위젯이거나 없음\".", ["constructor"]),
        (10, 12, "필드 셋.", []),
        (14, 14, "색 상수.", []),
        (16, 19, "build와 <code>Row</code>.", ["build"]),
        (20, 37, "<b>왼쪽 화살표.</b> 원본이 위(^)를 가리켜서 반시계 90°(<code>quarterTurns: 3</code>) 돌려 왼쪽으로 만든다는 주석. 누르면 부모가 준 <code>onBack</code>.", ["tap"]),
        (38, 42, "4 간격 뒤에 제목 글자(20, 굵게).", []),
        (43, 43, "<b>오른쪽 위젯이 있을 때만</b> <code>Spacer</code>로 오른쪽 끝에 밀어 보여줍니다(<code>[const Spacer(), trailing!]</code>).", ["collectionif", "null"]),
        (44, 47, "괄호 닫기.", []),
    ],
    next_hint="<code>user_settings_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/presentation/user_settings_screen.dart",
    title="사용자 설정: 로그아웃과 탈퇴",
    role="사용자 설정",
    arrive="<code>profile_screen.dart</code> 118줄 <code>context.push('/profile/user-settings')</code> → <code>router.dart</code> 202줄 <code>UserSettingsScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, Riverpod, 화면 이동.", []),
        (5, 9, "뒤로가기 줄, <code>ApiException</code>, <b>탈퇴 로직(<code>account_actions.dart</code>)</b>, 계정 provider·인증 저장소, 설정 카드.", []),
        (11, 15, "문서 주석. 로그아웃/탈퇴 확인창은 별도 화면이 아니라 이 화면 위에 <code>showDialog</code>로 띄웁니다.", []),
        (16, 17, "<code>ref</code>만 있으면 되는 <code>ConsumerWidget</code>(바뀌는 값 없음).", ["consumer"]),
        (19, 22, "build와 <b>보호자 이름 읽기</b>(계정 provider의 캐시 값; 이름을 고치면 프로필 관리에서 invalidate한 것이 여기 반영됩니다).", ["build", "asyncvalue"]),
        (23, 33, "화면 틀, 좌우 28 여백, Column. 뒤로가기 줄은 \"사용자 설정\".", ["layout"]),
        (34, 39, "<b>보호자 카드.</b> \"보호자 설정\"(눌러도 아직 반응 없는 줄)과 \"보호자 성명 — (이름)\" 값 줄.", []),
        (40, 40, "남는 공간을 먹는 <code>Spacer</code>로 버튼들을 아래로 밀어냅니다.", []),
        (41, 51, "<b>\"로그아웃\" 버튼.</b> 누르면 <code>_confirm(...)</code>에 팝업 제목·내용·버튼 글자를 넘겨 부릅니다. 이름 있는 인자(<code>title:</code>, <code>content:</code>, <code>confirmLabel:</code>)로 팝업 문구만 다르게 재사용합니다.", ["valuechanged"]),
        (52, 52, "10 간격.", []),
        (53, 64, "<b>\"탈퇴하기\" 버튼.</b> 같은 <code>_confirm</code>에 탈퇴 문구와 <b><code>withdraw: true</code></b>를 넘깁니다. 이 한 줄이 로그아웃과 탈퇴를 가르는 스위치입니다.", []),
        (65, 71, "아래 여백과 괄호 닫기.", []),
        (73, 84, "<b>두 버튼이 공유하는 확인 함수.</b> 주석: <code>withdraw</code>가 false면 로그아웃(서버 <code>access_uuid</code> 무효화 후 로그인 화면), true면 탈퇴(서버에서 계정을 지우고 이 기기 데이터까지 지운 뒤 로그인 화면). <code>bool withdraw = false</code>는 안 넘기면 false인 이름 있는 인자의 기본값입니다.", ["constructor"]),
        (85, 98, "<b>확인창.</b> 제목·내용·확인 글자만 인자로 받은 값으로 채웁니다(<code>profile_screen.dart</code>의 두 확인창을 하나로 합친 함수입니다).", ["dialog"]),
        (99, 112, "<b>실행.</b> 취소했으면(<code>confirmed != true</code>) 바로 끝냅니다. 그 뒤 <code>try</code> 안에서 <code>withdraw</code>이면 <code>accountActions.withdraw()</code>, 아니면 <code>logout()</code>을 부릅니다. 서버 오류(<code>ApiException</code>)면 스낵바를 띄우고 <code>return</code>해서 <b>화면에 남고</b>, 성공하면 <code>context.go('/login')</code>입니다. <code>context.mounted</code>는 await 뒤에도 화면이 살아 있는지 확인합니다.", ["trycatch", "async"]),
        (113, 113, "클래스 끝.", []),
        (115, 121, "<b>위험 버튼 위젯.</b> 라벨, <code>filled</code>(연빨강 배경 여부), 눌림 함수.", ["voidcallback"]),
        (123, 145, "<b>알약 버튼.</b> 높이 55. <code>filled</code>이면 연한 빨강 배경에 그림자 없음, 아니면 흰 배경에 옅은 그림자. 글자는 항상 빨강 굵게. <code>조건 ? 값 : null</code>로 그림자를 껐다 켭니다.", ["tap", "null"]),
    ],
    next_hint="뒤로 가서 <code>profile_screen.dart</code> 98줄의 \"언어\", 122줄의 \"로그인 기록\"을 차례로 봅니다. 먼저 <code>language_screen.dart</code>.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/presentation/language_screen.dart",
    title="언어 선택 (자리만 잡은 화면)",
    role="언어 (/profile/language)",
    arrive="<code>profile_screen.dart</code> 98줄 <code>context.push('/profile/language')</code> → <code>router.dart</code> 198줄 <code>LanguageScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, SVG, 화면 이동.", []),
        (5, 5, "뒤로가기 줄.", []),
        (7, 13, "문서 주석. 앱 전체를 다국어로 바꾸는 국제화(l10n)가 아직 없어서 <b>골라도 화면 안의 체크 표시만 바뀌고 실제 언어는 안 바뀐다</b>는 설명.", []),
        (14, 15, "<b>선택 표시가 바뀌므로 Stateful이지만 <code>ref</code>는 필요 없어서</b> 일반 <code>StatefulWidget</code>입니다. 이 앱에서 드문 경우입니다(Riverpod을 안 씀).", ["stateful"]),
        (17, 19, "State 연결.", []),
        (21, 31, "<b>언어 목록 8개</b>(한국어, English, 中文, 日本語, Tiếng Việt, العربية, ภาษาไทย, Español). 글자 자체가 해당 언어로 적혀 있습니다.", ["const"]),
        (33, 33, "<b>지금 선택된 언어</b>를 State가 들고 있습니다(처음은 \"한국어\"). 서버·기기 어디에도 저장되지 않아서 화면을 나가면 사라집니다.", []),
        (35, 45, "화면 틀, 좌우 26 여백, Column.", ["build", "layout"]),
        (46, 47, "뒤로가기 줄(\"언어\")과 16 간격.", []),
        (48, 53, "<b>스크롤되는 목록.</b> <code>Expanded</code> 안의 <code>ListView</code>가 남는 세로 공간을 쓰고, <code>for</code>로 언어마다 줄을 만듭니다. 줄을 누르면 <code>setState</code>로 선택값을 바꿉니다.", ["tap", "collectionif"]),
        (54, 70, "<b>줄 하나.</b> 언어 이름 글자, <code>Spacer</code>, 오른쪽 체크 그림. 선택된 언어면 채운 체크(<code>checkbox_filled.svg</code>), 아니면 빈 체크. 이 두 그림은 루틴 폼의 구성원 칩과 같은 에셋입니다.", []),
        (71, 73, "목록 괄호 닫기.", []),
        (74, 87, "<b>\"완료\" 버튼.</b> 누르면 그냥 <code>pop</code>합니다(저장 동작 없음).", []),
        (88, 95, "괄호 닫기.", []),
    ],
    next_hint="<code>login_history_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=5,
    file="lib/features/profile/presentation/login_history_screen.dart",
    title="로그인 기록 (목업 값)",
    role="로그인 기록 (/profile/login-history)",
    arrive="<code>profile_screen.dart</code> 122줄 <code>context.push('/profile/login-history')</code> → <code>router.dart</code> 207줄 <code>LoginHistoryScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 2, "Flutter 위젯, 화면 이동.", []),
        (4, 4, "뒤로가기 줄.", []),
        (6, 11, "문서 주석. 실제 로그인 이력을 남기는 서버가 없어서 <b>Figma 목업의 예시 값을 그대로 정적으로</b> 보여줍니다. 지금 나오는 기기 이름과 시각은 진짜 기록이 아닙니다.", []),
        (12, 13, "상태가 없어서 StatelessWidget.", ["class"]),
        (15, 19, "<b>예시 항목 셋을 레코드 목록으로.</b> <code>('iPhone 13', '2일 전 접속')</code>은 클래스를 따로 만들 만큼 크지 않은 \"기기 이름 + 시각\" 묶음입니다.", ["record", "const"]),
        (21, 22, "build.", ["build"]),
        (23, 33, "화면 틀과 Column, 뒤로가기 줄(\"로그인 기록\"), 24 간격.", ["layout"]),
        (34, 42, "<b>항목마다 카드 하나.</b> <code>for (final entry in _entries) ...[</code>로 돌며 흰 둥근 상자(높이 55, 모서리 21)를 만듭니다. 목록 뒤 12 간격도 같이 펼칩니다.", ["collectionif"]),
        (43, 62, "<b>카드 안.</b> 기기 이름은 <code>entry.$1</code>(레코드의 첫 값, 굵게), 시각은 <code>'・${entry.$2}'</code>(둘째 값), <code>Spacer</code>, 오른쪽 \">\" 아이콘.", ["record", "interp"]),
        (63, 64, "12 간격과 반복 목록 닫기.", []),
        (65, 79, "<b>맨 아래 \"완료\" 버튼.</b> <code>Spacer</code>로 아래로 밀고, 누르면 <code>pop</code>. 언어 화면과 같은 모양입니다.", []),
        (80, 87, "괄호 닫기. 5장 끝, 그리고 이 투어의 끝입니다.", []),
    ],
    next_hint="투어 끝. 읽지 않은 화면(기기 추가·기기 상세·통계·와이파이 설정, 소셜 로그인 목업, 와치 연결)은 이 장들에서 배운 패턴(provider, Hive 저장소, Stateful 폼, 공용 위젯)의 반복입니다.",
))
