# -*- coding: utf-8 -*-
# 3장: 홈 화면과 하단 탭, 기기 (홈 → 기기 데이터 → 공용 위젯 → 하단 탭 → 기기 탭)

CONCEPTS_CH = {
    "consumer": ("ConsumerWidget 과 WidgetRef", "<code>ConsumerWidget</code>은 \"<code>ref</code>를 쓸 수 있는 StatelessWidget\"입니다. 바뀌는 값을 자기가 들고 있지 않고 Riverpod provider에서 읽기만 하면 이걸로 충분합니다. <code>build(BuildContext context, WidgetRef ref)</code>처럼 <code>ref</code>가 build의 두 번째 인자로 들어옵니다. 입력 중인 글자처럼 화면이 직접 들고 있어야 하는 값이 있으면 <code>ConsumerStatefulWidget</code>을 씁니다(1장의 로그인 화면)."),
    "asyncvalue": ("FutureProvider 와 .value ?? const []", "<code>FutureProvider</code>는 서버나 Hive에서 값을 \"나중에\" 가져오는 provider이고, <code>ref.watch</code>하면 <code>AsyncValue</code>라는 상자가 옵니다. 상자에는 <b>로딩 중 / 오류 / 값 있음</b> 세 상태가 있어서, 값이 있을 때만 <code>.value</code>로 꺼낼 수 있고 로딩 중에는 null입니다. 그래서 <code>.value ?? const []</code>는 \"값이 있으면 그것을, 없으면 빈 리스트를\"이라는 뜻입니다."),
    "stateprovider": ("StateProvider 와 .notifier.state", "화면 여러 곳이 같이 보고 같이 바꾸는 <b>값 하나</b>를 담는 provider입니다. 읽기는 <code>ref.watch(p)</code>, 바꾸기는 <code>ref.read(p.notifier).state = 새값</code>입니다. 바꾸면 그 값을 watch하던 화면이 다시 그려집니다. 서버에 저장하지 않는 \"지금 보고 있는 칸 번호\" 같은 화면 상태에 어울립니다."),
    "invalidate": ("*Actions 와 ref.invalidate", "데이터를 저장한 뒤에는 목록 provider가 들고 있던 옛 값이 낡습니다. 저장 직후 <code>ref.invalidate(목록Provider)</code>를 부르면 그 provider의 캐시가 버려지고, 그것을 watch하던 모든 화면이 다음 build에서 새로 불러옵니다. 이 앱은 \"저장 + invalidate\"를 <code>*Actions</code> 클래스 한 곳에 모아 두고 화면은 <code>ref.read(xActionsProvider).addDevice(...)</code> 한 줄만 부릅니다."),
    "collectionif": ("리스트 안의 if / for / ...", "<code>children: [ ... ]</code> 안에서 <code>if (조건) 위젯</code>은 조건이 참일 때만 그 위젯을 넣고, <code>for (var i = 0; ...) 위젯</code>은 반복해서 여러 개를 넣습니다. 여러 위젯을 한꺼번에 넣고 싶으면 <code>if (조건) ...[위젯1, 위젯2]</code>처럼 <code>...</code>(펼치기)를 씁니다. 화면에 \"있을 때만 그리기\"를 코드 흐름 그대로 쓸 수 있어서 자주 보입니다."),
    "voidcallback": ("VoidCallback 과 콜백 인자", "<code>VoidCallback</code>은 \"인자도 반환값도 없는 함수\"의 타입 이름입니다. 위젯이 <code>onTap</code>, <code>onPrev</code>처럼 함수를 인자로 받으면, <b>무엇을 할지는 부르는 쪽이 정하고</b> 위젯은 \"눌리면 이 함수를 부른다\"만 합니다. 타입 뒤에 <code>?</code>가 붙은 <code>VoidCallback?</code>은 null이어도 된다는 뜻이고, null이면 눌러도 아무 일도 안 일어납니다."),
    "scroll": ("SingleChildScrollView / SafeArea", "<code>SingleChildScrollView</code>는 자식이 화면보다 길면 세로로 스크롤되게 해줍니다. <code>SafeArea</code>는 상태바, 노치, 하단 제스처 바에 가리지 않도록 안쪽으로 들여 그립니다. <code>top: false</code>, <code>bottom: false</code>로 특정 방향만 끌 수 있습니다."),
    "tap": ("InkWell · InkResponse · GestureDetector", "위젯을 누를 수 있게 만드는 도구들입니다. <code>InkWell</code>과 <code>InkResponse</code>는 누르면 물결(ripple) 효과가 보이고, <code>GestureDetector</code>는 효과 없이 눌림만 감지합니다. 셋 다 <code>onTap: () { ... }</code>에 \"눌렸을 때 할 일\"을 넘깁니다."),
}

STOPS_CH = []

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/home/presentation/home_screen.dart",
    title="홈 화면의 뼈대",
    role="홈 탭 (/)",
    arrive="<code>device_connection_screen.dart</code> 67줄 <code>context.go('/')</code>, 또는 이름이 이미 있는 계정이 <code>login_screen.dart</code> 55줄에서 <code>context.go('/')</code> → <code>router.dart</code> 86줄 <code>HomeScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG 그림, 화면 이동.", []),
        (6, 10, "우리 코드 다섯. 하단 탭바, 기기 목록 provider와 모델, 알림 개수 provider, 그리고 홈과 기기 상세가 같이 쓰는 위젯 모음(<code>device_overview.dart</code>)입니다.", []),
        (12, 21, "문서 주석. 제목부터 \"현재 루틴\" 카드까지는 기기 상세 화면과 디자인이 같아서 <code>device_overview.dart</code>에 공용 위젯으로 빼 두었고, 이 파일은 그것들의 <b>배치 순서</b>와 홈 고유의 상단 바만 맡는다는 설명입니다.", []),
        (22, 23, "<b>HomeScreen은 StatelessWidget.</b> 화면 스스로 바뀌는 값이 없고, 바뀌는 데이터를 읽는 일은 안쪽의 작은 위젯들이 각자 합니다.", ["class"]),
        (25, 25, "화면 배경색(연한 회색). 줄 끝 <code>//</code> 뒤는 주석입니다.", []),
        (27, 32, "화면 틀과 배경색. 아래 주석대로 작은 화면에서는 내용이 길 수 있어서 스크롤 가능한 영역으로 감쌉니다.", ["build", "scroll"]),
        (33, 38, "<code>SingleChildScrollView</code> 안의 <code>Column</code>. <code>crossAxisAlignment.stretch</code>는 자식들이 가로를 꽉 채우게 합니다(흰 상단 바가 좌우 끝까지 닿아야 해서).", ["layout"]),
        (39, 46, "<b>Column의 자식 두 개.</b> 맨 위 흰 상단 바(<code>_TopBar</code>)와, 위 20·아래 24 여백을 준 본문(<code>_DeviceHeroSection</code>). 이름 앞 <code>_</code>는 이 파일 안에서만 쓰는 위젯이라는 뜻입니다.", ["private"]),
        (47, 52, "<b>하단 탭바.</b> <code>Scaffold</code>의 <code>bottomNavigationBar</code> 자리에 <code>BottomNavBar(currentIndex: 0)</code>를 둡니다. 0은 \"지금 홈 탭\"이라는 뜻이고, 루틴·기기·프로필 화면도 각자 자기 번호를 넘깁니다.", []),
        (53, 54, "괄호 닫기.", []),
        (56, 62, "문서 주석. 기기가 하나도 없으면 가짜 이름과 배터리를 보여줄 수 없어서 안내로 바꾸지만, \"연결된 기기\" 카드와 \"현재 루틴\" 카드는 계정 전체를 요약하는 카드라 항상 보인다는 설계 이유입니다.", []),
        (63, 64, "<b>ConsumerWidget.</b> provider 값을 읽어야 해서 <code>ref</code>가 필요한 StatelessWidget입니다.", ["consumer"]),
        (66, 67, "build 시작. 두 번째 인자 <code>ref</code>가 provider를 꺼내는 손잡이입니다.", ["override"]),
        (68, 68, "<b>기기 목록 읽기.</b> <code>deviceListProvider</code>는 Hive에서 목록을 \"나중에\" 가져오는 FutureProvider라서, 값이 있을 때만 <code>.value</code>로 꺼내고 로딩 중이면 빈 리스트로 대신합니다. watch했으므로 목록이 바뀌면 이 위젯이 다시 그려집니다.", ["asyncvalue"]),
        (70, 71, "<code>Column</code> 시작.", []),
        (72, 77, "<b>기기가 없으면 안내, 있으면 선택된 기기 패널.</b> 리스트 안의 <code>if / else</code>입니다. 안내의 \"기기 추가하기\"를 누르면 <code>context.push('/devices/add')</code>로 기기 추가 화면이 위에 쌓입니다.", ["collectionif", "voidcallback"]),
        (78, 83, "24 간격 뒤에, 좌우 28 여백을 준 영역을 엽니다.", []),
        (84, 88, "<b>카드 두 장.</b> \"연결된 기기\" 카드(누르면 <code>/connected-devices</code>로 이동)와 \"현재 루틴\" 카드. 두 카드는 다음 정류장 <code>device_overview.dart</code>에 정의돼 있습니다.", []),
        (89, 95, "괄호 닫기들.", []),
        (97, 102, "문서 주석과 위젯 선언. 기기 목록 <code>devices</code>를 부모에게서 받아 씁니다.", []),
        (104, 105, "build 시작.", ["build"]),
        (106, 112, "<b>지금 보고 있는 기기 고르기.</b> <code>selectedDeviceIndexProvider</code>(몇 번째 기기를 보는지)를 읽고, 기기가 삭제돼 목록이 줄었어도 범위를 벗어나지 않도록 <code>clamp(0, 마지막)</code>로 자릅니다. 그 번호로 <code>devices[index]</code>를 꺼냅니다.", ["stateprovider"]),
        (113, 115, "맨 앞이면 이전으로, 맨 끝이면 다음으로 더 못 갑니다. 그 판단을 bool 두 개로 만들어 둡니다.", []),
        (117, 123, "<code>Column</code> 시작. 주석대로 기본 가운데 정렬이면 상태 목록이 붕 뜨기 때문에 왼쪽(<code>start</code>)에 붙였습니다.", ["layout"]),
        (124, 135, "<b>\"OO의 기기\" 제목과 상태 3줄</b>(온라인·연결됨·배터리). 상태는 아직 BLE 데이터가 없어서 고정값입니다.", []),
        (136, 136, "20 간격.", []),
        (137, 151, "<b>기기 캐러셀(좌우로 넘기기).</b> 가운데 로봇 그림, 양옆 화살표. 화살표를 누르면 <code>ref.read(selectedDeviceIndexProvider.notifier).state = index - 1</code>로 <b>번호만 바꿉니다</b>. 그러면 이 위젯이 다시 그려지고 다른 기기가 보입니다. 끝에서는 함수 대신 <code>null</code>을 넘겨 눌러도 반응이 없게 합니다(<code>조건 ? 함수 : null</code>).", ["stateprovider"]),
        (152, 162, "\"기기 상태\" 소제목 줄과 괄호 닫기.", []),
        (164, 169, "<b>상단 바.</b> 흰 배경, 상태바와 겹치지 않게 <code>SafeArea</code>(<code>bottom: false</code>는 아래쪽은 신경 안 쓴다는 뜻).", ["scroll"]),
        (170, 177, "흰 배경 <code>Container</code>와 안쪽 <code>SafeArea</code>, 좌우 31·위아래 16 여백.", []),
        (178, 192, "<code>Row</code>에 로고(왼쪽), <code>Spacer()</code>(남는 공간을 전부 차지해서 로고와 벨을 양 끝으로 벌림), 알림 벨(오른쪽).", ["layout"]),
        (194, 205, "<b>알림 벨 위젯.</b> <code>notificationCountProvider</code>로 알림 개수를 읽습니다. 지금은 알림을 만드는 기능이 없어서 항상 0입니다.", ["consumer"]),
        (206, 210, "누르면 물결이 보이는 영역(<code>InkResponse</code>). <code>onTap: () {}</code>는 빈 함수라 지금은 반응이 없습니다.", ["tap"]),
        (211, 221, "<b><code>Stack</code>은 자식을 앞뒤로 겹쳐 쌓습니다.</b> 벨 그림 위에 빨간 뱃지를 올리려는 것입니다. <code>clipBehavior: Clip.none</code>은 뱃지가 벨 바깥으로 삐져나가도 잘라내지 말라는 뜻입니다.", []),
        (222, 245, "<b>알림이 1개 이상일 때만</b>(<code>if (count > 0)</code>) 뱃지를 그립니다. <code>Positioned(top: -5, right: -6)</code>은 Stack 안에서 위치를 지정하며, 음수라 벨 오른쪽 위 바깥으로 나갑니다. 안에는 빨간 동그라미와 개수 글자(<code>'$count'</code>).", ["collectionif", "interp"]),
        (246, 251, "괄호 닫기.", []),
    ],
    next_hint="<code>deviceListProvider</code>와 <code>selectedDeviceIndexProvider</code>의 정의를 보려고 7줄 <code>device_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/devices/data/device_providers.dart",
    title="기기 목록과 \"지금 보는 기기\"",
    role="기기 provider",
    arrive="<code>home_screen.dart</code> 68줄 <code>ref.watch(deviceListProvider)</code>, 110줄 <code>selectedDeviceIndexProvider</code>에서 왔습니다.",
    chunks=[
        (1, 2, "Riverpod과, <code>StateProvider</code>를 쓰기 위한 <code>legacy.dart</code>(Riverpod 3부터 따로 가져와야 한다고 주석에 적혀 있습니다).", []),
        (4, 6, "Hive 도구, 기기 모델, 기기 저장소.", []),
        (8, 11, "<b>이 파일 안에서만 쓰는</b>(<code>_</code>) Hive 도구 provider. 다른 기능에도 같은 이름이 있지만 파일마다 독립이라 충돌하지 않고, 이 도구는 상태가 없어서 여러 개여도 문제없다고 주석이 설명합니다.", ["provider", "private"]),
        (13, 15, "<code>deviceRepositoryProvider</code>. 1장의 <code>authRepositoryProvider</code>와 같은 모양인데, 안쪽이 서버(Dio)가 아니라 <b>Hive를 쓰는 <code>LocalDeviceRepository</code></b>라는 점이 다릅니다. 기기는 아직 서버와 동기화하지 않습니다.", []),
        (17, 23, "<b>기기 목록 provider.</b> <code>FutureProvider</code>는 값을 \"나중에\" 가져오는 provider입니다. 저장소에서 목록을 받아 <code>connectedAt</code>(등록 시각) 오름차순으로 정렬해 돌려줍니다. <code>devices..sort(...)</code>의 <code>..</code>는 \"정렬을 시킨 뒤 그 리스트 자신을 돌려줘라\"입니다.", ["asyncvalue", "arrow"]),
        (25, 29, "<b>\"지금 몇 번째 기기를 보는가\"를 담는 <code>StateProvider</code>.</b> 처음 값은 0. 홈 화면의 캐러셀 화살표가 이 값을 바꾸고, 같은 값을 읽는 위젯이 다시 그려집니다.", ["stateprovider"]),
        (31, 31, "<code>DeviceActions</code>를 만들어 주는 provider. 화면은 이걸로 쓰기 기능을 꺼냅니다.", []),
        (33, 36, "<b>쓰기 기능 모음 클래스.</b> <code>Ref</code>를 받아 보관합니다. provider 밖의 평범한 클래스도 이렇게 <code>Ref</code>를 받으면 다른 provider를 읽을 수 있습니다.", []),
        (38, 44, "<b>기기 하나 등록.</b> 현재 시각을 마이크로초 숫자로 바꿔 id로 씁니다(겹칠 일이 거의 없어서). 저장소의 <code>addDevice</code>로 Hive에 저장합니다.", ["async"]),
        (45, 47, "<b>저장 직후 <code>ref.invalidate(deviceListProvider)</code>.</b> 낡은 목록 캐시를 버려서 홈, 기기 탭, 연결된 기기 화면이 다음 build에서 새 목록을 받습니다.", ["invalidate"]),
    ],
    next_hint="14줄 <code>LocalDeviceRepository</code>를 Ctrl+클릭해 <code>device_repository.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/devices/data/device_repository.dart",
    title="기기를 Hive 상자에 넣고 꺼내기",
    role="기기 저장소(Hive)",
    arrive="<code>device_providers.dart</code> 14줄 <code>LocalDeviceRepository(...)</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Hive, 1장에서 본 <code>LocalStorageService</code>(박스를 열어주는 도구), 기기 모델.", []),
        (6, 9, "<b>\"기기 저장소가 할 일\" 약속.</b> 목록 읽기, 하나 추가. 화면과 provider는 이 약속만 봅니다.", ["abstract"]),
        (11, 14, "Hive 기반 구현체. 실제 BLE 페어링이 붙기 전까지 기기 추가 흐름을 흉내 내는 용도라고 주석에 적혀 있습니다. 박스를 여는 도구를 받아 보관합니다.", []),
        (16, 17, "<b>상자 이름 <code>'devices'</code></b>와 도구 필드. 이 이름이 폰 안 저장소의 상자 이름입니다.", []),
        (19, 19, "<b>getter.</b> <code>_box</code>를 읽을 때마다 <code>openBox('devices')</code>를 실행해 상자를 엽니다. 이미 열려 있으면 Hive가 열린 것을 돌려줍니다.", ["getter"]),
        (21, 27, "<b>목록 읽기.</b> 상자의 값들(<code>box.values</code>)을 하나씩 <code>ConnectedDevice.fromMap</code>으로 모델로 바꿔 리스트로 만듭니다. Hive가 주는 Map의 타입이 느슨해서 <code>Map&lt;String, dynamic&gt;.from(...)</code>로 한 번 변환합니다.", ["maplist", "generic"]),
        (29, 34, "<b>하나 저장.</b> <code>box.put(키, 값)</code>으로 id를 키로, 모델을 Map(<code>toMap</code>)으로 바꿔 넣습니다. 같은 id면 덮어씁니다.", []),
    ],
    next_hint="<code>ConnectedDevice</code>를 Ctrl+클릭해 모델 파일로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/devices/domain/connected_device.dart",
    title="기기 한 대를 담는 상자",
    role="기기 모델",
    arrive="<code>device_repository.dart</code> 25줄 <code>ConnectedDevice.fromMap(...)</code>에서 왔습니다.",
    chunks=[
        (1, 6, "문서 주석. 홈 카드와 \"연결된 기기\" 화면이 보여주는 목록의 원소라는 설명과, BLE가 아직 없어서 지금은 이름만 받아 저장한다는 사정.", []),
        (7, 12, "기기 하나의 설계도와 생성자. 세 값 모두 <code>required</code>입니다.", ["constructor"]),
        (14, 14, "기기 id(문자열).", []),
        (16, 20, "기기 주인의 짧은 이름(예: \"지예\"). 화면마다 \"지예의 기기\", \"지예님의 기기\"처럼 접미사를 다르게 붙입니다. 접미사를 저장하지 않고 화면에서 붙이는 이유입니다.", []),
        (22, 24, "등록 시각. 등록 순서대로 정렬하고, 색을 돌려 배정하는 데 씁니다.", []),
        (26, 32, "<b>Hive에서 꺼낸 Map → 모델.</b> 1·2장의 <code>fromJson</code>과 같은 아이디어인데 서버 JSON이 아니라 Hive에 저장한 Map이라 이름이 <code>fromMap</code>입니다. 시각은 저장할 때 문자열로 바꿔 두었으니 <code>DateTime.parse</code>로 되돌립니다.", ["factory"]),
        (34, 41, "<b>모델 → Map.</b> 위의 반대 방향. Hive는 DateTime을 그대로 못 저장해서 <code>toIso8601String()</code>(\"2026-10-05T12:30:00.000\" 모양)으로 바꿉니다. 이 한 쌍(<code>fromMap</code>/<code>toMap</code>)이 루틴 등 다른 Hive 모델에도 반복됩니다.", []),
    ],
    next_hint="홈 화면의 부품들을 보려고 <code>home_screen.dart</code> 10줄로 돌아가 <code>device_overview.dart</code>를 엽니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/home/presentation/widgets/device_overview.dart",
    title="홈과 기기 상세가 같이 쓰는 위젯 모음",
    role="공용 위젯 모음",
    arrive="<code>home_screen.dart</code> 10줄 import(<code>NoConnectedDeviceHero</code>, <code>DeviceTitleRow</code>, <code>DeviceCarousel</code>, <code>ConnectedDevicesCard</code> 등)에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, Riverpod, SVG.", []),
        (5, 6, "기기 목록 provider와 <b>루틴 provider</b>. 아래 \"현재 루틴\" 카드가 루틴 데이터를 읽기 때문입니다(4장에서 다룹니다).", []),
        (8, 13, "문서 주석. 홈 화면과 기기 상세 화면은 상단 바만 다르고 나머지가 똑같아서, 이 한 파일에 모아 두 화면이 가져다 쓴다는 설명입니다.", []),
        (15, 18, "<b>색 상수 네 개.</b> 맨 앞 <code>k</code>는 상수(constant) 이름에 붙이는 관례입니다. 파일 맨 위에 있어서 다른 파일이 <code>import</code>해서 쓸 수 있습니다(기기 탭이 <code>kDeviceOverviewLabelColor</code>를 가져다 씁니다).", ["const"]),
        (20, 34, "<b>SVG 그림을 그리는 얇은 포장 위젯.</b> <code>SvgPicture.asset(...)</code>과 <code>fit: contain</code>(상자 안에 비율을 유지하며 들어가게)을 매번 쓰기 번거로워 한 번에 묶었습니다. <code>colorFilter</code>는 색을 덮어씌우고 싶을 때만 넘기는 선택 인자입니다. <code>=&gt;</code> 한 줄 build입니다.", ["arrow", "null"]),
        (36, 46, "<b>카드 모양을 만드는 함수.</b> 위젯이 아니라 <code>BoxDecoration</code>(상자의 꾸밈)을 돌려줍니다. 흰 배경, 둥근 모서리(기본 25), 아주 옅은 그림자. <code>{double radius = 25}</code>는 이름 있는 인자의 <b>기본값</b>입니다. 여러 카드가 이 한 함수로 같은 모양을 얻습니다.", ["constructor"]),
        (48, 78, "<b>\"OO의 기기\" 제목.</b> 이름을 부모가 넘겨주고(<code>deviceOwnerName</code>), <code>'$deviceOwnerName의 기기'</code>로 문자열에 끼웁니다. 옆에 7×7 작은 장식 그림.", ["interp"]),
        (80, 102, "<b>상태 3줄 목록</b>(온라인·연결됨·95%). <code>onWifiTap</code>은 \"연결됨\" 줄을 눌렀을 때 할 일인데, 기기 상세 화면에서만 넘기고 홈에서는 null이라 반응이 없습니다.", ["voidcallback"]),
        (104, 121, "<b>상태 한 줄 위젯.</b> 줄마다 아이콘만 다르고 모양이 같아서, \"어느 아이콘을 쓸지\"를 bool 세 개로 받아 한 위젯을 재사용합니다. <code>this.useOnlineDot = false</code>는 안 넘기면 false라는 기본값입니다.", []),
        (122, 151, "<b>어떤 아이콘을 쓸지 고르는 if / else if 사슬.</b> 초록 점은 7×7 동그라미(<code>BoxDecoration</code>의 <code>shape: circle</code>), 와이파이는 SVG, 배터리는 SVG를 <code>RotatedBox(quarterTurns: 1)</code>로 90° 돌려 가로로 눕힙니다. 위젯을 변수(<code>rowIcon</code>)에 담아 두었다가 아래에서 쓰는 방식입니다.", []),
        (153, 171, "<b>아이콘 + 글자 한 줄.</b> <code>mainAxisSize.min</code>이라 내용만큼만 차지합니다. 마지막 두 줄은 \"눌림 동작이 없으면 그대로 돌려주고, 있으면 <code>GestureDetector</code>로 감싸서\"라는 분기입니다.", ["tap"]),
        (173, 177, "캐러셀 화살표 색 두 개. 넘길 수 있으면 파랑, 끝이면 회색으로 \"여기가 끝\"임을 알려줍니다. 다른 상수를 이어서 이름을 붙이는 것도 됩니다(<code>= kDeviceOverviewBrandBlue</code>).", []),
        (179, 207, "<b>캐러셀 위젯의 선언과 인자.</b> 모든 인자가 선택(이름 있는 인자, <code>required</code> 없음)이며 타입 끝 <code>?</code>는 null 허용입니다. 문서 주석 설명: 함수를 안 넘기면 화살표를 눌러도 반응이 없는 \"자리만 잡은 상태\"가 됩니다.", ["voidcallback", "null"]),
        (209, 214, "높이 149로 고정한 <code>Row</code>를 엽니다. 왼쪽 화살표 / 가운데 기기 그림 / 오른쪽 화살표 순서입니다.", ["layout"]),
        (215, 239, "<b>왼쪽 화살표.</b> 폭 103 칸의 가운데에 누를 수 있는 영역을 두고, 화살표 SVG를 <code>quarterTurns: 3</code>(270° 회전)해서 왼쪽을 향하게 합니다. <code>onTap: onPrev ?? () {}</code>는 \"onPrev가 null이면 빈 함수를 대신 써라\"입니다. 색은 <code>canGoPrev</code>가 null이면 SVG 원래 색, 아니면 파랑/회색으로 덮어씁니다(<code>ColorFilter.mode(색, BlendMode.srcIn)</code>은 그림의 불투명한 부분을 그 색 하나로 칠합니다).", ["tap", "null"]),
        (240, 248, "<b>가운데 기기 그림.</b> <code>Expanded</code>로 남는 폭을 차지하고, 143×149 크기로 <code>iconAsset</code>을 그립니다.", []),
        (249, 273, "<b>오른쪽 화살표.</b> 왼쪽의 거울상: 폭 92, <code>quarterTurns: 1</code>(90° 회전), <code>onNext</code>, <code>canGoNext</code>.", []),
        (274, 278, "괄호 닫기.", []),
        (280, 288, "<b>기기가 하나도 없을 때</b> 제목+상태+캐러셀을 통째로 대신하는 안내. 이 구역이 줄면 아래 카드들이 위아래로 크게 들썩이기 때문에 캐러셀과 같은 높이(149)로 맞췄다고 주석이 설명합니다.", []),
        (290, 311, "높이 149 영역의 가운데에 세로로 쌓은 아이콘(40×40), 간격, \"연결된 기기가 없어요\" 글자.", ["layout"]),
        (312, 333, "<b>\"기기 추가하기\" 글자 버튼.</b> <code>onAddDevice</code>(부모가 준 함수)를 눌렀을 때 부릅니다. 홈에서는 <code>context.push('/devices/add')</code>가 넘어옵니다.", ["tap"]),
        (335, 358, "<b>페이지 점 5개</b>(첫 번째만 파랑). <code>List.generate(5, ...)</code>로 만듭니다. 기기 상세 화면에만 쓰입니다.", []),
        (360, 388, "<b>\"기기 상태\" 소제목 + \"3분전 동기화됨\" 작은 글자.</b> 이 문구는 지금 고정 글자입니다(실제 동기화 시각이 아님).", []),
        (390, 395, "<b>색 돌려쓰기 팔레트.</b> Figma가 3명(연두·회색·보라) 고정이었던 걸 \"몇 번째로 연결됐는가\"로 일반화했습니다. 4번째 기기부터는 처음 색으로 돌아옵니다.", ["generic"]),
        (396, 400, "기기 그림 3종의 파일 경로.", []),
        (402, 408, "<b>번호로 팔레트에서 고르는 함수 둘.</b> <code>index % 3</code>은 \"3으로 나눈 나머지\"(0,1,2,0,1,2...)라서 번호가 3을 넘어도 팔레트 안에서 순환합니다. 같은 번호면 그림과 점 색이 항상 짝이 맞습니다.", ["arrow"]),
        (410, 424, "<b>\"연결된 기기\" 카드.</b> 문서 주석은 \"기기가 없으면 안내로 바뀐다\"고 설명합니다. <code>ConsumerWidget</code>이라 <code>deviceListProvider</code>를 직접 watch합니다. 부모 화면이 목록을 넘기지 않아도 기기를 추가하면 카드가 알아서 갱신됩니다.", ["consumer", "asyncvalue"]),
        (426, 432, "흰 카드 상자와 안쪽 <code>Column</code>.", []),
        (433, 456, "<b>제목 줄.</b> \"연결된 기기\" 글자, 오른쪽 끝으로 미는 <code>Spacer</code>, 그리고 <b>기기가 있을 때만</b> \"N개 기기 연결중\"(<code>${devices.length}</code>로 숫자를 끼움). 리스트 안의 <code>if (...) ...[...]</code>(펼치기)로 두 위젯을 한꺼번에 넣고 뺍니다.", ["collectionif", "interp"]),
        (457, 466, "오른쪽 끝 작은 \">\" 화살표(<code>quarterTurns: 1</code>로 아래 화살표를 오른쪽으로 돌림).", []),
        (467, 481, "<b>빈 상태 vs 기기 목록.</b> 기기가 없으면 <code>_NoConnectedDevices</code>, 있으면 12 간격 뒤에 <code>for</code>로 기기마다 한 줄(<code>_ConnectedDeviceRow</code>)을 만듭니다. <code>if (i &gt; 0)</code>은 \"첫 줄 앞에는 간격 없이, 그 다음부터만 10 간격\"입니다.", ["collectionif"]),
        (482, 485, "<b>누를 수 있는 카드로 만들기.</b> <code>onTap</code>이 null이면 카드 그대로, 아니면 <code>GestureDetector</code>로 감쌉니다. 홈은 <code>/connected-devices</code>로 가는 함수를 넘깁니다.", ["tap"]),
        (487, 534, "<b>기기가 없을 때의 안내 줄.</b> 아이콘 20×20 + \"연결된 기기가 없어요\" + 작은 설명. 기기 탭의 \"기기 추가하기\" 카드와 같은 아이콘을 써서 \"여기서 추가할 수 있다\"를 같은 그림으로 말합니다. <code>Expanded</code> 안의 <code>Column</code>이 글자 두 줄을 쌓습니다.", []),
        (536, 566, "<b>기기 한 줄: 색 점 + 이름.</b> 점은 7.09×7.09 동그라미, 색은 부모가 정해 넘깁니다(<code>deviceDotColorFor(i)</code>).", []),
        (568, 574, "<b>\"현재 루틴\" 카드.</b> 오늘 루틴 중 가장 이른 것 하나를 보여줍니다. 루틴 탭에서 새 루틴을 추가하면 이 카드도 자동으로 갱신된다고 주석에 적혀 있습니다.", []),
        (575, 580, "<b>오늘 날짜의 루틴 목록 읽기.</b> <code>routinesForDateProvider(날짜)</code>는 \"날짜를 인자로 받는 provider\"라서 <code>ref.watch(provider(인자))</code> 모양으로 씁니다. 시·분·초를 떼고 \"오늘 0시\"만 넘깁니다.", ["consumer"]),
        (581, 581, "목록이 비었으면 null, 아니면 첫 번째 루틴(목록이 시간순이라 가장 이른 것).", []),
        (583, 589, "흰 카드 상자와 <code>Column</code>.", []),
        (590, 610, "\"현재 루틴\" 라벨과 오른쪽 \">\" 화살표.", []),
        (611, 620, "<b>루틴이 없으면</b> \"오늘 등록된 루틴이 없어요\" 글자.", ["collectionif"]),
        (621, 643, "<b>있으면</b> \"시각 제목\"(<code>'${_timeLabel(routine.dateTime)} ${routine.title}'</code>)과 옆의 \"・태그\". 줄 안에 식을 넣으려고 <code>${...}</code>를 씁니다.", ["interp"]),
        (644, 646, "괄호 닫기.", []),
        (648, 653, "<b>시각을 \"09:05\" 모양 글자로.</b> <code>padLeft(2, '0')</code>로 한 자리 숫자 앞에 0을 붙입니다. 두 문자열 리터럴을 붙여 쓰면 하나로 이어집니다. 앞의 <code>static</code>은 객체를 만들지 않고 클래스 이름으로 바로 부를 수 있는 함수라는 뜻입니다.", []),
    ],
    next_hint="홈 화면 맨 아래 <code>BottomNavBar(currentIndex: 0)</code>(<code>home_screen.dart</code> 51줄)를 Ctrl+클릭해 <code>bottom_nav_bar.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/app/widgets/bottom_nav_bar.dart",
    title="네 화면이 같이 쓰는 하단 탭바",
    role="하단 탭바",
    arrive="<code>home_screen.dart</code> 51줄 <code>BottomNavBar(currentIndex: 0)</code>에서 왔습니다. 루틴·기기·프로필 화면도 각자 자기 번호로 같은 위젯을 씁니다.",
    chunks=[
        (1, 3, "Flutter 위젯, SVG, 화면 이동.", []),
        (5, 14, "문서 주석. 디자인에서 \"홈\"은 동그란 배경에, 나머지 세 탭은 긴 알약 배경에 묶여 있고 활성 탭만 파랗다는 것, 그리고 쓰는 법(<code>currentIndex</code>만 넘기면 됨).", []),
        (15, 16, "<b>StatelessWidget.</b> 어느 탭이 켜졌는지는 부모(화면)가 숫자로 정해 주므로 이 위젯에는 바뀌는 값이 없습니다.", ["class"]),
        (18, 20, "지금 화면이 몇 번째 탭인지(0~3).", []),
        (22, 24, "<b>탭 번호 → 이동 경로표.</b> 순서가 <code>router.dart</code>의 경로와 같아야 합니다. 번호 1을 누르면 <code>_routes[1]</code>, 즉 <code>'/routine'</code>으로 갑니다.", []),
        (26, 31, "색 상수들. <code>0xA3FFFFFF</code>에서 앞 두 자리 <code>A3</code>가 투명도(약 64% 불투명), 나머지가 흰색이라 <b>반투명 흰색</b> 알약입니다.", ["const"]),
        (33, 39, "<b>탭을 눌렀을 때.</b> 이미 보고 있는 탭이면 아무것도 안 하고(<code>return</code>), 다른 탭이면 <code>context.go(경로)</code>로 화면을 갈아치웁니다. push가 아니라 go라서 탭을 오갈 때 화면이 계속 쌓이지 않습니다.", ["gopush"]),
        (41, 51, "<b>바깥 틀.</b> <code>ColoredBox</code>(배경색만 칠하는 가벼운 상자)에 홈 배경색을 맞추고, <code>SafeArea(top: false)</code>로 아래쪽 제스처 바만 피합니다. 안쪽 여백은 좌24·위24·우24·아래8(<code>fromLTRB</code>).", ["scroll", "build"]),
        (52, 70, "<b><code>Row</code>(<code>spaceBetween</code>)</b>: 왼쪽에 홈 알약, 오른쪽에 나머지 세 탭 알약을 두고 사이를 최대한 벌립니다. 홈 알약에는 <code>active: currentIndex == 0</code>(내가 0번이면 켜짐)과 눌림 함수를 넘기고, 오른쪽에는 <code>currentIndex</code>와 \"몇 번을 눌렀는지 알려주는\" 함수를 넘깁니다.", ["voidcallback"]),
        (71, 71, "클래스 끝.", []),
        (73, 79, "<b>홈 알약 위젯.</b> 홈 아이콘만 다른 셋과 분리된 원이라서 따로 뺐습니다.", []),
        (81, 98, "<b>59×59 원형 배경.</b> 긴 주석의 요지: <code>Container</code>가 크기를 정하면 자식에게도 \"그 크기로 꽉 채워라\"를 강요해서 안쪽 아이콘 크기가 무시되는데, <code>alignment: center</code>를 주면 그 강요가 \"원하는 만큼 써도 된다\"로 풀려 지정한 크기가 먹습니다. Flutter 레이아웃의 대표적 함정이라 주석으로 남긴 것입니다.", []),
        (99, 114, "<b>홈 아이콘.</b> <code>_NavIconButton</code>에 그림 경로, 크기(27×30, Figma 원본 값), 켜짐 여부, 눌림 함수를 넘깁니다.", []),
        (116, 124, "<b>세 탭 알약.</b> 눌림 콜백의 타입 <code>void Function(int index)</code>은 \"번호를 받는 함수\"입니다. 몇 번을 눌렀는지만 알려주면 부모가 실제 이동을 처리합니다.", ["voidcallback"]),
        (126, 136, "207×59 크기에 모서리 반지름 30(높이 절반 이상이면 양끝이 완전히 둥근 알약).", []),
        (137, 148, "<b>아이콘 3개를 균등 간격으로</b>(<code>spaceEvenly</code>). 첫째는 루틴(달력)으로 <code>active: currentIndex == 1</code>, <code>onTap: () =&gt; onTap(1)</code>입니다.", ["layout", "arrow"]),
        (149, 169, "기기(2번), 내 정보(3번) 아이콘. 같은 패턴에 번호만 다릅니다.", []),
        (171, 192, "<b>아이콘 하나짜리 버튼 위젯.</b> 문서 주석의 핵심: SVG 파일은 회색 하나뿐이고 <code>colorFilter</code>로 상황에 따라 다시 칠해서 활성/비활성을 표현합니다. 아이콘 파일을 두 벌 만들 필요가 없습니다.", []),
        (194, 200, "누르면 물결이 보이는 <code>InkResponse</code>. 터치 반경 28로 아이콘보다 넉넉히 잡아 손가락으로 누르기 쉽게 합니다.", ["tap", "build"]),
        (201, 210, "<b>활성 탭 배경.</b> 켜져 있으면 아이콘 뒤에 아주 옅은 알약(검정 5% 투명도), 꺼져 있으면 꾸밈 없음(<code>null</code>). <code>조건 ? A : null</code> 패턴입니다.", []),
        (211, 225, "<b>아이콘 그리기와 색 입히기.</b> <code>BlendMode.srcIn</code>은 \"그림의 불투명한 부분만 이 색으로 칠하라\"입니다. 켜졌으면 브랜드 하늘색, 아니면 회색(<code>#D9D9D9</code>).", []),
    ],
    next_hint="홈 화면의 알림 벨이 읽는 <code>notificationCountProvider</code>(<code>home_screen.dart</code> 204줄)를 짧게 봅니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/notifications/data/notification_providers.dart",
    title="알림 개수 provider",
    role="알림 provider",
    arrive="<code>home_screen.dart</code> 204줄 <code>ref.watch(notificationCountProvider)</code>에서 왔습니다.",
    chunks=[
        (1, 5, "Riverpod, Hive 도구, 알림 모델, 알림 저장소.", []),
        (7, 10, "이 파일 안에서만 쓰는 Hive 도구 provider(기기 provider와 같은 이유).", ["private"]),
        (12, 14, "알림 저장소 provider. Hive를 쓰는 로컬 구현체입니다.", ["provider"]),
        (16, 18, "<b>알림 목록 provider.</b> <code>FutureProvider</code>이고, 아직 알림을 <b>쓰는</b> 기능이 없어서 목록은 항상 비어 있습니다(<code>notifications</code> 박스에 아무도 쓰지 않음).", ["asyncvalue"]),
        (20, 23, "<b>개수만 뽑아 내는 파생 provider.</b> 다른 provider(<code>notificationListProvider</code>)의 값을 읽어 <code>?.length ?? 0</code>(값이 없으면 0)로 가공합니다. 이렇게 하면 벨 위젯은 \"개수\"만 구독해서 단순해집니다. 값이 이미 있는 <code>Provider</code>라 FutureProvider와 달리 바로 <code>int</code>를 돌려줍니다.", ["null"]),
    ],
    next_hint="하단 탭의 \"기기\"(2번) 화면, <code>devices_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/devices/presentation/devices_screen.dart",
    title="기기 탭: 2열 카드 그리드",
    role="기기 탭 (/devices)",
    arrive="하단 탭바 두 번째 기기 아이콘 → <code>bottom_nav_bar.dart</code> 38줄 <code>context.go('/devices')</code> → <code>router.dart</code> 158줄 <code>DevicesScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 8, "하단 탭바, 위에서 본 공용 위젯 모음(<code>AssetIcon</code>, 색 상수, <code>deviceCardDecoration</code>), 기기 provider.", []),
        (10, 14, "문서 주석. 기기 탭. 연결된 기기들을 2열 그리드로 보여주고 카드를 누르면 상세 화면으로, 기기가 없으면 \"기기 추가하기\" 점선 카드만 남습니다.", []),
        (15, 16, "홈 위젯들처럼 provider를 읽기만 하는 <code>ConsumerWidget</code>.", ["consumer"]),
        (18, 18, "배경색.", []),
        (20, 22, "build와 기기 목록 읽기. 홈 화면과 <b>같은</b> <code>deviceListProvider</code>를 watch하므로, 기기를 추가하면 홈과 이 탭이 함께 갱신됩니다.", ["asyncvalue", "build"]),
        (24, 30, "화면 틀. <code>SafeArea(bottom: false)</code>(아래는 탭바가 있어서 끔), 스크롤 영역, 안쪽 여백.", ["scroll"]),
        (31, 44, "<code>Column</code>의 첫 자식 \"기기 관리\" 제목 글자. 색 상수를 <code>device_overview.dart</code>에서 가져다 씁니다.", []),
        (45, 49, "30 간격과, <b>왜 GridView가 아니라 Wrap인지</b> 설명하는 주석. 카드 수가 적고 높이가 고정이라 내용만큼만 차지하는 <code>Wrap</code>이 더 간단하다는 것.", []),
        (50, 53, "<code>Wrap</code>은 자식들을 가로로 채우다가 줄이 차면 다음 줄로 넘깁니다. 가로 간격 14, 세로 간격 14.", ["layout"]),
        (54, 59, "<b>기기마다 카드 하나.</b> <code>for</code>로 목록을 돌며 이름, 순번에 맞는 로봇 그림(<code>deviceIconAssetFor(i)</code>)을 넘깁니다. 누르면 <code>context.push('/devices/${devices[i].name}')</code>으로 그 기기의 상세 화면이 위에 쌓입니다.", ["collectionif", "gopush"]),
        (60, 62, "<b>마지막 칸은 항상 \"기기 추가하기\" 카드.</b> 기기가 0개면 이것만 남습니다.", []),
        (63, 73, "괄호 닫기와 하단 탭바(<code>currentIndex: 2</code> — 기기 탭이 켜짐).", []),
        (75, 78, "<b>카드 크기 상수.</b> 주석: 화면 폭 402에서 좌우 여백 36×2와 카드 사이 간격 14를 빼고 2로 나눈 값에 맞춘 고정 폭입니다.", ["const"]),
        (80, 91, "<b>기기 카드 위젯.</b> 이름, 그림 경로, 눌림 함수를 부모에게서 받습니다.", ["voidcallback"]),
        (92, 101, "<code>InkWell</code>(눌림 + 물결)로 감싼 카드. 물결이 카드의 둥근 모서리(반지름 25) 밖으로 번지지 않게 <code>borderRadius</code>를 같은 값으로 맞춥니다. 상자 꾸밈은 공용 <code>deviceCardDecoration()</code>.", ["tap"]),
        (102, 114, "<b>오른쪽 위 작은 \">\".</b> <code>Align(topRight)</code>로 구석에 붙이고 <code>RotatedBox</code>로 화살표를 돌립니다.", []),
        (115, 123, "<b>카드 가운데 큰 로봇 그림.</b> <code>Expanded</code> 안의 <code>Center</code>라 남는 세로 공간의 한가운데에 86×89 크기로 놓입니다.", []),
        (124, 137, "카드 아래 기기 이름(굵은 13). 괄호 닫기.", []),
        (139, 145, "<b>\"기기 추가하기\" 점선 카드 위젯.</b> 색 상수 하나.", []),
        (147, 161, "카드 틀. 주석: Figma는 점선이지만 Flutter 기본 <code>Border</code>는 점선이 없어서(커스텀 페인터가 필요) <b>실선으로 대체</b>했습니다. 디자인과 코드가 다른 부분을 주석으로 남겨 두는 좋은 예입니다.", []),
        (162, 180, "가운데 정렬 <code>Column</code>: 플러스 아이콘, 10 간격, \"기기 추가하기\" 글자. <code>const Column</code>이라 안의 위젯도 전부 const입니다.", ["const"]),
    ],
    next_hint="홈 화면의 \"연결된 기기\" 카드를 누르면 가는 <code>connected_devices_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=3,
    file="lib/features/devices/presentation/connected_devices_screen.dart",
    title="연결된 기기 화면",
    role="/connected-devices",
    arrive="<code>home_screen.dart</code> 85줄 <code>context.push('/connected-devices')</code> → <code>router.dart</code> 227줄 <code>ConnectedDevicesScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, Riverpod, 화면 이동.", []),
        (5, 8, "뒤로가기 줄 위젯(<code>BackHeader</code>), 공용 상수, 기기 provider, \"라벨 + 입력 칸\" 위젯(<code>LabeledFieldRow</code>).", []),
        (10, 16, "문서 주석. Figma에서 이름 없는 프레임으로 저장돼 있었다는 이력, WIFI 정보와 실제 연결된 기기 목록을 보여준다는 설명.", []),
        (17, 18, "provider를 읽기만 하는 <code>ConsumerWidget</code>.", ["consumer"]),
        (20, 22, "build와 기기 목록 읽기(홈과 같은 provider).", ["build", "asyncvalue"]),
        (23, 24, "<b>WIFI ID와 비밀번호 칸의 컨트롤러.</b> 처음 글자를 <b>고정 샘플값</b>('U+Net1024' 등)으로 넣어둔 상태입니다. 실제 와이파이 정보가 아니라 디자인 자리 채우기입니다.", ["formfield"]),
        (26, 30, "화면 틀, 배경, 안쪽 여백 26.", ["scroll"]),
        (31, 40, "<code>Column</code> 안: 뒤로가기 줄(<code>onBack: () =&gt; context.pop()</code>이 쌓인 화면을 한 장 걷어냄), WIFI ID 칸, PW 칸.", ["gopush", "arrow"]),
        (41, 60, "<b>\"+ 연결 기기 추가\" 버튼.</b> 흰 둥근 상자, 옅은 그림자(<code>BoxShadow</code>). 누르면 <code>/connected-devices/add</code>로 이동합니다. 아이콘과 글자를 <code>Row</code>로 나란히.", ["tap"]),
        (61, 62, "<b>기기가 하나라도 있을 때만</b> 아래 목록 카드를 그립니다(<code>if (devices.isNotEmpty) ...[</code>).", ["collectionif"]),
        (63, 70, "목록 카드의 흰 상자와 안쪽 <code>Column</code>.", []),
        (71, 89, "카드 제목 줄: \"연결된 기기\", 오른쪽으로 민 \"N개 기기 연결중\".", ["interp"]),
        (90, 113, "<b>기기마다 한 줄.</b> 색 점(<code>deviceDotColorFor(i)</code>, 홈 카드와 같은 색)과 \"이름님의 기기\". 줄 사이 10 간격은 마지막 줄 뒤에는 넣지 않습니다(<code>if (i &lt; devices.length - 1)</code>).", ["collectionif", "interp"]),
        (114, 121, "괄호 닫기들. 3장 끝.", []),
    ],
    next_hint="3장 끝. 4장에서 루틴(하단 탭 1번)을 읽습니다.",
))
