# -*- coding: utf-8 -*-
# 4장: 루틴 (달력 → 데이터 → 카드 → 추가 폼 → 반복 규칙 → 템플릿 → 오늘 할 일 → 상세)

CONCEPTS_CH = {
    "late": ("late 변수", "<code>late DateTime _selectedDate;</code>는 \"지금은 값이 없지만 <b>쓰기 전에는 반드시 채우겠다</b>\"는 약속입니다. null을 허용하는 <code>DateTime?</code>과 달리 쓸 때마다 null 검사를 안 해도 됩니다. 값을 <code>initState</code>에서 채우거나, <code>late final x = ...;</code>처럼 <b>처음 쓰는 순간에</b> 계산되게 할 수도 있습니다(widget 값을 쓰는 초기값에 유용합니다)."),
    "family": ("Provider.family (인자를 받는 provider)", "<code>Provider.family&lt;결과, 인자&gt;</code>는 \"인자마다 따로 만들어지는 provider\"입니다. <code>ref.watch(routinesForDateProvider(날짜))</code>처럼 인자를 붙여 쓰며, 같은 인자면 같은 결과를 캐싱해서 돌려줍니다. 날짜별 목록, id별 루틴 하나처럼 <b>\"무엇에 대한\"</b>이 필요한 데이터에 씁니다."),
    "switchexpr": ("switch 식 (=>)", "<code>switch (값) { 'A' =&gt; 결과1, 'B' =&gt; 결과2, _ =&gt; 나머지 }</code>는 값에 따라 <b>결과를 돌려주는 식</b>입니다(<code>_</code>는 \"그 외 전부\"). 위젯 목록 안에서 \"탭에 따라 다른 위젯\"을 고를 때 깔끔합니다. 옛 형태의 <code>switch (x) { case 'A': ...; return ...; }</code> 문장도 같이 쓰입니다."),
    "spread": ("[...목록, 새원소] 와 ..", "<code>[..._steps, text]</code>는 \"<code>_steps</code>의 모든 원소를 펼치고 뒤에 <code>text</code>를 붙인 <b>새 리스트</b>\"입니다. 기존 리스트를 직접 고치지 않고 새로 만들어 대입하면 상태 변경이 안전합니다. <code>[..._steps]..removeAt(i)</code>의 <code>..</code>(캐스케이드)는 \"앞의 값에 이 동작을 한 뒤 그 값 자신을 돌려줘라\"입니다."),
    "setmap": ("Set 과 {키: 값} 컬렉션", "<code>Set&lt;String&gt;</code>은 <b>중복 없는 모음</b>입니다(<code>{'지예', '예담'}</code>). <code>contains</code>, <code>add</code>, <code>remove</code>로 \"선택됐나/선택/해제\"를 표현하기 좋습니다. <code>Map&lt;String, X&gt;</code>은 키로 값을 찾는 사전이고, <code>{ for (final p in 목록) p.name: p }</code>처럼 반복으로 사전을 만들 수도 있습니다."),
    "pickers": ("showTimePicker / showDatePicker", "시간·날짜를 고르는 <b>표준 팝업</b>을 띄우는 함수입니다. <code>await showTimePicker(...)</code>가 사용자가 고른 값을 돌려주고, 팝업을 그냥 닫으면 <code>null</code>이 옵니다. 그래서 <code>if (picked == null) return;</code>로 취소를 처리합니다."),
    "listview": ("ListView.separated", "항목이 많은 목록을 <b>화면에 보이는 것만</b> 만들어 효율적으로 그리는 스크롤 목록입니다. <code>itemCount</code>(몇 개), <code>itemBuilder</code>(i번째 항목 위젯을 만드는 함수), <code>separatorBuilder</code>(항목 사이 간격 위젯)를 줍니다. <code>(_, _) =&gt; ...</code>의 밑줄은 \"쓰지 않는 인자\"입니다."),
    "painter": ("CustomPaint 와 Canvas", "기본 위젯으로 못 그리는 모양은 <code>CustomPainter</code>를 만들어 <code>paint(Canvas, Size)</code> 안에서 선·원·호를 직접 그립니다. <code>Paint()</code>에 색과 굵기를 정하고 <code>canvas.drawCircle</code>, <code>canvas.drawArc</code> 같은 함수로 그립니다. <code>shouldRepaint</code>는 \"값이 바뀌었을 때만 다시 그려라\"를 알려줍니다."),
    "valuechanged": ("ValueChanged&lt;T&gt; 와 제네릭 위젯", "<code>ValueChanged&lt;int&gt;</code>는 \"int를 받는 함수\"의 타입 이름입니다. 부모가 <code>onMonthChanged: (v) =&gt; setState(() =&gt; _repeatMonth = v)</code>처럼 <b>\"값이 바뀌면 이렇게 해라\"</b>를 넘기고, 자식은 선택이 바뀔 때 그 함수를 부릅니다. 위젯 이름 뒤의 <code>&lt;T&gt;</code>(예: <code>_Dropdown&lt;T&gt;</code>)는 \"어떤 타입이든 쓰는 위젯\"이라는 뜻입니다."),
}

STOPS_CH = []

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_screen.dart",
    title="루틴 탭: 달력과 그날의 카드",
    role="루틴 탭 (/routine)",
    arrive="하단 탭바 두 번째 아이콘 → <code>bottom_nav_bar.dart</code> 38줄 <code>context.go('/routine')</code> → <code>router.dart</code> 90줄 <code>RoutineScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 10, "하단 탭바, <b>자녀 선택 칩</b>(<code>child_selector.dart</code>), 루틴 provider, \"+\" 버튼, 루틴 카드 목록 위젯.", []),
        (12, 27, "문서 주석. 진짜 달력 + 선택한 날짜의 루틴 카드 + \"+\" 버튼 구성이고, 카드는 하드코딩이 아니라 Hive에 저장된 루틴이라는 점, 그리고 목록 맨 아래를 더 당기면(overscroll) \"오늘 할 일\" 화면으로 넘어간다는 동작이 적혀 있습니다.", []),
        (28, 33, "<b>달력 월과 선택 날짜가 바뀌므로 Stateful.</b> <code>ref</code>도 필요해서 <code>ConsumerStatefulWidget</code>입니다.", ["stateful"]),
        (35, 36, "State 클래스와 배경색.", []),
        (38, 43, "<b>화면이 들고 있는 값 둘.</b> <code>_displayedMonth</code>(지금 달력에 펼친 달, 일은 항상 1)와 <code>_selectedDate</code>(눌러서 고른 날). <code>late</code>는 선언할 때 값이 없고 아래 <code>initState</code>에서 채운다는 약속입니다.", ["late"]),
        (45, 52, "<b>화면이 처음 생길 때 한 번.</b> 오늘 날짜로 두 값을 정합니다. <code>DateTime(년, 월, 일)</code>로 시·분·초를 0으로 맞춥니다(<code>super.initState()</code>를 먼저 부르는 것이 규칙).", ["stateful"]),
        (54, 62, "<b>달력 칸을 눌렀을 때.</b> <code>setState</code>로 선택 날짜를 바꾸고, 다른 달의 칸을 눌렀다면 보여주는 달도 그 날짜의 달로 맞춥니다.", []),
        (64, 72, "<b>달 넘기기.</b> <code>_shiftMonth(-1)</code>은 이전 달. <code>DateTime(년, 월 + delta)</code>에서 월이 0이나 13이어도 Dart가 알아서 이전·다음 해로 넘겨 줍니다.", []),
        (74, 77, "맨 아래를 넘어 <b>60픽셀</b> 더 당기면 \"오늘 할 일\"로 넘어갑니다. 너무 작으면 실수로 넘어가고, 너무 크면 반응이 없는 느낌이라는 설명입니다.", ["const"]),
        (79, 96, "<b>중복 이동을 막는 깃발.</b> 긴 주석의 요지: 한 번 드래그하는 동안 스크롤 알림이 여러 번 오기 때문에, 깃발이 없으면 <code>push</code>가 겹쳐 호출돼 \"오늘 할 일\" 화면이 여러 겹 쌓입니다. <code>push</code>가 돌려주는 Future가 끝날 때(= 그 화면이 닫혀 돌아올 때) 깃발을 내립니다. 과거에 다른 방식으로 풀려다 생긴 버그 이력도 적혀 있습니다.", ["async"]),
        (98, 122, "<b>스크롤 알림 처리.</b> 맨 끝을 이미 넘어 더 당긴 거리(<code>pixels - maxScrollExtent</code>)를 직접 계산해 60을 넘으면 <code>context.push('/routine/today')</code>를 합니다. iOS 스타일 스크롤은 <code>OverscrollNotification</code>을 안 보내고 <code>ScrollUpdateNotification</code>만 보내서 이렇게 계산해야 한다고 주석이 설명합니다. <code>.then((_) {...})</code>는 push가 끝난 뒤 실행할 일이고, <code>false</code>를 돌려줘야 알림이 위로 계속 전달됩니다.", ["gopush"]),
        (124, 131, "build 시작. <b>선택한 날의 루틴 목록</b>과 <b>이 달의 날짜별 개수</b> 두 가지를 provider에서 읽습니다. 둘 다 인자를 받는 provider(<code>family</code>)입니다. 선택 날짜나 표시 월이 바뀌면 인자가 달라져 자동으로 다른 목록을 읽습니다.", ["build", "family"]),
        (133, 138, "<b>Stack으로 \"스크롤되는 본문\"과 \"고정된 + 버튼\"을 겹칩니다.</b> + 버튼은 스크롤해도 같은 자리에 떠 있어야 해서 스크롤 영역 바깥에 둡니다.", ["layout"]),
        (139, 145, "주석: <code>Positioned.fill</code>이 없으면 Stack이 스크롤 내용의 높이에만 맞춰 줄어들어서, 루틴이 없는 날에는 + 버튼이 화면 아래가 아니라 짧은 내용 바로 밑에 붙어버립니다. fill로 화면 전체를 차지하게 합니다.", []),
        (146, 150, "<code>SafeArea</code> 안에 <code>NotificationListener</code>. 이 위젯이 아래에서 올라오는 스크롤 알림을 <code>_handleScrollNotification</code>으로 받습니다.", ["scroll"]),
        (151, 163, "<b>스크롤 물리.</b> 안드로이드 기본은 끝에서 멈춰서 overscroll이 생기지 않으니, 끝에서 튕기는 <code>BouncingScrollPhysics</code>가 필요하고, 내용이 짧아도 당길 수 있게 <code>AlwaysScrollableScrollPhysics</code>로 감쌉니다.", []),
        (164, 180, "<code>Column</code>의 첫 자식은 <b>자녀 선택 칩 줄</b>(<code>ChildSelector</code>, 서버 루틴 API가 자녀별이라 어느 자녀를 볼지 고름), 그 아래 월 제목 줄(<code>_MonthHeader</code>). 화살표 눌림에 <code>_shiftMonth(-1)</code>/<code>(1)</code>을 연결하고 18 간격.", ["layout"]),
        (181, 187, "요일 헤더 줄과 <b>달력 그리드</b>. 어느 달인지, 어느 날이 선택됐는지, 날짜별 개수, 날짜를 눌렀을 때 할 일(<code>_selectDate</code>)을 넘깁니다. 부모(이 State)가 값을 들고 있고 자식은 그리기만 합니다.", []),
        (188, 200, "<b>그날의 루틴 카드 목록.</b> <code>RoutineCardList(routines: ...)</code>에 선택한 날의 루틴을 넘깁니다. 아래 여백 120은 + 버튼에 마지막 카드가 가리지 않게 하려는 것입니다.", []),
        (201, 211, "<b>고정 \"+\" 버튼</b>(오른쪽·아래 위치는 두 화면이 공유하는 상수)과 하단 탭바(<code>currentIndex: 1</code> — 루틴 탭 켜짐).", []),
        (213, 249, "<b>월 제목 줄 위젯.</b> 큰 \"10월\" 글자와 좌우 화살표 둘. 디자인에는 화살표가 없었지만 월을 넘길 수 있어야 해서 추가했다고 주석에 적혀 있습니다. 화살표 에셋은 홈 캐러셀 것을 재사용합니다.", ["voidcallback"]),
        (251, 285, "<b>월 화살표 버튼 하나.</b> 원본 아이콘이 위쪽(^)을 가리켜서 <code>RotatedBox(quarterTurns)</code>로 3(왼쪽)이나 1(오른쪽)만큼 돌려 씁니다. 눌리는 반경 18, 안쪽 여백 8로 손가락이 닿기 쉽게 합니다.", ["tap"]),
        (287, 311, "<b>요일 헤더 \"일 월 화 수 목 금 토\".</b> 리스트를 <code>for</code>로 돌며 <code>Expanded</code> 일곱 칸을 만듭니다. 일요일·토요일도 같은 회색인 것이 Figma 값입니다.", ["collectionif", "layout"]),
        (313, 329, "<b>달력 그리드 위젯.</b> 달, 선택 날짜, 날짜별 개수(<code>Map&lt;int,int&gt;</code>), 눌림 함수를 받습니다. <code>ValueChanged&lt;DateTime&gt;</code>은 \"날짜를 받는 함수\" 타입입니다.", ["valuechanged"]),
        (331, 344, "<b>빈 칸 계산.</b> 그 달의 일수와 1일의 요일을 구합니다. Dart의 요일은 월=1…일=7이라 \"일요일 시작 달력\"에는 <code>% 7</code>로 앞에 둘 빈 칸 수를 얻습니다(일→0칸, 월→1칸). 마지막 주도 7칸을 채우게 뒤 빈 칸 수도 계산합니다.", []),
        (346, 372, "<b>칸 목록 만들기.</b> 앞 빈 칸 → 1일부터 말일까지 날짜 칸(<code>_CalendarDayCell</code>) → 뒤 빈 칸. 날짜 칸에는 오늘인지, 선택됐는지, 그날 개수를 계산해 넘깁니다. 빈 칸은 크기 0의 <code>SizedBox.shrink()</code>입니다.", ["setmap"]),
        (374, 389, "<b>7칸씩 끊어 한 주(Row)로, 주들을 Column으로.</b> <code>sublist(i, i + 7)</code>이 7개씩 잘라내고 <code>.map(...).toList()</code>로 각 칸을 <code>Expanded</code>로 감쌉니다.", ["maplist"]),
        (391, 410, "<b>날짜 칸 하나.</b> 날짜, 요일 번호(<code>column</code>, 0=일…6=토), 오늘/선택 여부, 개수, 눌림 함수를 받습니다.", []),
        (412, 415, "색 상수 넷(일요일 빨강, 토요일 파랑, 선택 하늘색, 개수 배지 회색).", ["const"]),
        (417, 428, "<b>숫자 색 정하기.</b> 선택됐으면 흰색, 아니면 일요일(0)은 빨강, 토요일(6)은 파랑, 나머지는 검정. <code>Color textColor;</code>는 값 없이 선언했다가 if / else if로 한 번씩 정합니다.", []),
        (430, 455, "<b>눌리는 영역 + 날짜 숫자.</b> 25×25 상자에 숫자를 가운데 놓고, 선택됐으면 하늘색 원 배경을 깝니다(<code>조건 ? 꾸밈 : null</code>).", ["tap"]),
        (456, 483, "<b>그날 루틴이 1개 이상이면</b> 작은 회색 원 안에 개수를 보여주고(<code>routineCount! &gt; 0</code>의 <code>!</code>는 위의 null 검사를 보증), 없으면 같은 높이의 빈 상자로 칸 높이를 맞춥니다.", ["collectionif", "null"]),
    ],
    next_hint="자녀 선택 칩(<code>ChildSelector</code>)은 다음 정류장에서 보고, 그 뒤 <code>routinesForDateProvider</code>를 Ctrl+클릭해 <code>routine_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/children/presentation/child_selector.dart",
    title="자녀 선택 칩",
    role="자녀 선택 줄",
    arrive="<code>routine_screen.dart</code> 170줄 <code>ChildSelector()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, 자녀 provider.", []),
        (6, 13, "문서 주석. 서버의 루틴·기기 API가 자녀별이라 루틴 탭 맨 위에서 자녀를 고르게 하고, 선택은 <code>selectedChildIdProvider</code>에 담깁니다. 자녀는 최대 10명이라 칩이 가로로 스크롤됩니다.", []),
        (14, 17, "provider만 읽는 <code>ConsumerWidget</code>과 색 상수.", ["consumer"]),
        (19, 22, "<b>자녀 목록과 값 꺼내기.</b> <code>async.value</code>는 값이 도착했을 때만 있고(<code>List&lt;Child&gt;?</code>) 아직이면 <code>null</code>입니다.", ["asyncvalue", "build"]),
        (24, 36, "<b>값이 아직 없을 때 두 갈래.</b> 로딩이면 칩 높이(31)만큼 빈 상자(로딩이 짧아 스피너는 오히려 깜빡이니까), 오류면 안내 글을 보여주고 <b>누르면 <code>ref.invalidate</code>로 다시 시도</b>합니다.", ["null", "tap"]),
        (37, 41, "<b>자녀가 0명</b>이면 칩 대신 \"등록된 자녀가 없어요\".", []),
        (42, 43, "<b>지금 기준 자녀</b>(<code>currentChildProvider</code>)를 읽습니다. 칩이 켜졌는지 비교하는 데 씁니다.", []),
        (44, 61, "<b>칩 줄.</b> 가로 스크롤 안의 <code>Row</code>에 자녀마다 칩을 만듭니다(첫 칩만 빼고 앞에 6 간격). 칩을 누르면 <code>ref.read(selectedChildIdProvider.notifier).state = child.childId</code>로 선택만 바꿉니다. 그러면 이 값을 watch하는 위젯들이 다시 그려집니다.", ["stateprovider", "collectionif"]),
        (63, 70, "<b>칩 한 개.</b> 이름, 켜졌는지, 눌림 함수를 받습니다.", ["voidcallback"]),
        (72, 99, "알약 모양(높이 31, 모서리 44). 켜진 칩은 하늘색 배경에 흰 글씨, 아니면 흰 배경에 회색 글씨와 옅은 그림자. 루틴 추가 폼의 탭 칩과 같은 모양입니다.", ["tap"]),
    ],
    next_hint="이제 루틴 목록을 만드는 <code>routine_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/data/routine_providers.dart",
    title="루틴 목록에서 \"그날 것\"을 뽑아내는 provider들",
    role="루틴 provider",
    arrive="<code>routine_screen.dart</code> 126줄 <code>routinesForDateProvider(_selectedDate)</code>, 129줄 <code>routineCountsByDayProvider</code>에서 왔습니다.",
    chunks=[
        (1, 5, "Riverpod, Hive 도구, 루틴 모델, 루틴 저장소.", []),
        (7, 7, "Hive 도구 provider. 기기 쪽과 달리 <code>_</code>가 없어서 <b>다른 파일(템플릿 provider)도 이걸 가져다 씁니다</b>.", ["provider"]),
        (9, 11, "루틴 저장소 provider. 안쪽은 Hive를 쓰는 <code>LocalRoutineRepository</code>입니다.", []),
        (13, 15, "<b>모든 루틴 목록.</b> 날짜 상관없이 통째로 읽는 <code>FutureProvider</code>. 아래 파생 provider들의 원본입니다.", ["asyncvalue"]),
        (17, 28, "<b>날짜별 목록 provider(family).</b> 달력에서 고른 날짜를 인자로 받습니다. 목록이 아직 로딩 중이거나 실패하면 빈 목록으로 취급해서 로딩 스피너 없이 \"루틴 없음\"으로 보이게 하고, 데이터가 도착하면 자동으로 다시 계산됩니다.", ["family"]),
        (29, 40, "<b>걸러내고 정렬.</b> 전체에서 연·월·일이 같은 것만 <code>where</code>로 남기고 <code>toList()</code>, 시작 시각 순으로 <code>sort</code>합니다. 루틴 수가 적은 로컬 앱이라 매번 전부 불러온 뒤 메모리에서 거르는 것으로 충분하다고 저장소 주석이 설명합니다.", ["arrow"]),
        (42, 51, "<b>id로 루틴 하나 찾기.</b> 상세·수정 화면이 라우트 주소의 id로 루틴을 찾을 때 씁니다. 없으면 <code>null</code>(<code>Routine?</code>).", ["family", "null"]),
        (53, 56, "<b>쓰기 기능 묶음 provider.</b> 저장 후 목록을 무효화해서 달력·오늘 할 일·상세가 자동 갱신되게 한다는 설명입니다.", ["invalidate"]),
        (58, 67, "<b>저장 + <code>invalidate</code> 한 쌍.</b> 기기의 <code>DeviceActions</code>와 똑같은 패턴입니다. 루틴 하나를 Hive에 저장하고 <code>routineListProvider</code>의 낡은 캐시를 버립니다.", ["invalidate", "async"]),
        (69, 85, "<b>달력 아래 개수 배지용 맵 만들기.</b> 그 달의 루틴을 돌며 <code>일 → 개수</code>를 셉니다. <code>(counts[일] ?? 0) + 1</code>은 \"없으면 0에서 시작해 하나 더하라\"입니다. 루틴이 없는 날은 키 자체가 없습니다.", ["setmap", "null"]),
    ],
    next_hint="14줄 <code>getRoutines()</code> 뒤의 저장소를 보려고 <code>routine_repository.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/data/routine_repository.dart",
    title="루틴을 Hive 'routines' 상자에",
    role="루틴 저장소(Hive)",
    arrive="<code>routine_providers.dart</code> 10줄 <code>LocalRoutineRepository(...)</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Hive, Hive 도구, 루틴 모델.", []),
        (6, 13, "<b>저장소가 할 일 약속.</b> 전체 읽기와 하나 저장. 주석: 날짜로 거르는 일은 저장소가 아니라 provider들이 맡습니다.", ["abstract"]),
        (15, 22, "Hive 구현체. 상자 이름은 <code>'routines'</code>. 기기 저장소와 완전히 같은 틀입니다.", ["getter"]),
        (24, 30, "<b>전체 읽기.</b> 상자의 모든 값을 <code>Routine.fromMap</code>으로 모델로 바꿉니다.", ["maplist"]),
        (32, 37, "<b>저장.</b> <code>box.put(id, 루틴의 Map)</code>. <b>같은 id로 다시 저장하면 덮어씁니다.</b> 이 성질 덕에 \"수정하기\"가 별도 update 함수 없이 같은 <code>saveRoutine</code>으로 동작합니다.", []),
    ],
    next_hint="<code>Routine</code>을 Ctrl+클릭해 모델 <code>routine.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/domain/routine.dart",
    title="루틴 한 개와 참여자",
    role="루틴 모델",
    arrive="<code>routine_repository.dart</code> 28줄 <code>Routine.fromMap(...)</code>에서 왔습니다.",
    chunks=[
        (1, 15, "문서 주석(\"11:00 교무실 가기\" 같은 카드 한 장이 루틴 한 개)과 생성자. <code>steps = const []</code>처럼 <code>= 값</code>이 붙은 인자는 안 넘기면 그 기본값(빈 목록)을 씁니다.", ["constructor"]),
        (17, 40, "<b>필드 다섯.</b> <code>id</code>, <code>title</code>, <code>dateTime</code>(날짜와 시작 시각을 한 값에), <code>tag</code>(\"공통\" 또는 \"지예님의 기기\"), <code>steps</code>(하위 할 일 글자 목록), <code>participants</code>(누가 했는지). 날짜 확인은 연·월·일만, 정렬·표시는 시·분까지 쓴다는 설명이 주석에 있습니다.", []),
        (42, 53, "<b>Hive Map → 모델.</b> <code>steps</code>는 <code>List&lt;String&gt;.from(...)</code>로 문자열 목록을 만들고, <code>?? const []</code>로 없으면 빈 목록. 참여자는 <code>.map(...).toList()</code>로 참여자 모델 목록으로 바꿉니다.", ["factory", "maplist"]),
        (55, 65, "<b>모델 → Hive Map.</b> 시각은 문자열로, 참여자는 각자 <code>toMap()</code>으로 바꿔 리스트에 담습니다.", []),
        (67, 86, "<b>참여자 한 명(이름 + 완료 여부).</b> 아이콘 색 같은 화면 꾸밈은 저장하지 않고 이름으로 찾아 쓴다고 주석에 적혀 있습니다. 같은 <code>fromMap</code>/<code>toMap</code> 한 쌍이 여기에도 있습니다.", []),
    ],
    next_hint="<code>routine_screen.dart</code> 191줄 <code>RoutineCardList</code>를 Ctrl+클릭해 <code>routine_card.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/widgets/routine_card.dart",
    title="루틴 카드와 카드 목록",
    role="루틴 카드 위젯",
    arrive="<code>routine_screen.dart</code> 191줄 <code>RoutineCardList(routines: ...)</code>에서 왔습니다. \"오늘 할 일\" 화면도 같은 위젯을 씁니다.",
    chunks=[
        (1, 5, "Flutter 위젯, SVG, 화면 이동, 루틴 모델.", []),
        (7, 18, "문서 주석. 카드 한 장 = \"11:00 교무실 가기 ・공통\" 한 줄 + 아래 번호 붙은 하위 할 일들. 오른쪽 화살표는 상세 화면으로 가는 버튼이고, 옛 버전에서는 접기/펼치기였다는 이력이 적혀 있습니다.", []),
        (19, 25, "<b>루틴 하나를 받아 그리는 위젯.</b> 공용 위젯이라 두 화면 어디서든 씁니다.", ["class"]),
        (27, 33, "<b>시각을 \"09:05\" 글자로.</b> <code>TimeOfDay.fromDateTime</code>으로 시·분을 얻고 <code>padLeft(2, '0')</code>로 두 자리를 맞춥니다. 두 문자열을 이어 붙여 씁니다.", ["interp"]),
        (35, 50, "<b>카드 전체가 눌리는 영역.</b> 누르면 <code>/routine/detail/<b>${routine.id}</b></code>로 push. 흰 배경·둥근 모서리 25·옅은 그림자 상자입니다(홈 카드와 같은 꾸밈이 한 번 더 복붙돼 있습니다).", ["tap", "gopush"]),
        (51, 53, "<code>Column</code>으로 \"첫 줄\" 아래에 하위 할 일들을 쌓을 준비.", ["layout"]),
        (54, 88, "<b>첫 줄: \"시각 제목 ・꼬리표\"와 오른쪽 \">\".</b> 글자 둘은 <code>Wrap</code> 안에 있어서 길면 다음 줄로 넘어갑니다. <code>Expanded</code>로 화살표를 오른쪽 끝에 밀어냅니다.", []),
        (89, 99, "<b>하위 할 일이 있을 때만</b>(<code>if (hasSteps) ...[</code>) 14 간격 뒤에 번호 줄들을 그립니다. 첫 줄은 위 여백 0, 그 다음부터 12로 간격을 맞춥니다(<code>i == 0 ? 0 : 12</code>).", ["collectionif"]),
        (100, 105, "괄호 닫기.", []),
        (107, 112, "<b>하위 할 일 한 줄 위젯</b>의 선언. 번호와 글자를 받습니다.", []),
        (114, 143, "회색 번호 배지(14×13, 모서리 2)와 글자. 번호는 <code>i + 1</code>로 1부터 보여줍니다.", ["build"]),
        (145, 174, "<b>루틴이 하나도 없을 때의 안내 카드.</b> \"등록된 루틴이 없어요 / 오른쪽 아래 + 버튼으로 추가해 보세요\".", []),
        (176, 197, "<b>목록 위젯.</b> 비었으면 안내 카드를 돌려주고(<code>if (...) return</code>으로 먼저 끝냄), 아니면 <code>for</code>로 루틴마다 카드 + 10 간격을 쌓습니다.", ["collectionif"]),
    ],
    next_hint="카드를 누르면 가는 상세 화면은 뒤에서 보고, 먼저 <code>routine_screen.dart</code> 204줄의 \"+\" 버튼 <code>AddRoutineButton</code>을 열어봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/widgets/add_routine_button.dart",
    title="오른쪽 아래 \"+\" 버튼",
    role="+ 버튼 위젯",
    arrive="<code>routine_screen.dart</code> 204줄 <code>AddRoutineButton()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, SVG, 화면 이동.", []),
        (5, 11, "<b>위치 상수 두 개.</b> 달력 화면과 \"오늘 할 일\" 화면이 똑같이 써야 화면을 오가도 버튼이 같은 자리에 떠 있는 것처럼 보입니다. 주석이 사용법까지 보여줍니다. 앞의 <code>k</code>는 상수 관례입니다.", ["const"]),
        (13, 16, "버튼 위젯 선언. 누르면 \"단일/복합/템플릿\" 중 고르는 화면으로 간다는 설명.", []),
        (18, 30, "<b>한 줄 핵심: <code>onTap: () =&gt; context.push('/routine/add')</code>.</b> 78×78 SVG가 버튼 그림이고 반경 39로 눌러서, 누르면 물결이 번집니다.", ["tap", "gopush"]),
    ],
    next_hint="<code>/routine/add</code> → <code>router.dart</code> 131줄 <code>RoutineTypeSelectScreen()</code> → <code>routine_type_select_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_type_select_screen.dart",
    title="무엇을 추가할까요?",
    role="루틴 유형 선택",
    arrive="<code>add_routine_button.dart</code> 21줄 <code>context.push('/routine/add')</code> → <code>router.dart</code> 131줄 <code>RoutineTypeSelectScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 3, "Flutter 위젯, SVG, 화면 이동.", []),
        (5, 5, "하단 탭바.", []),
        (7, 13, "문서 주석. 세 선택지가 모두 실제 화면으로 이어지고, 단일/복합은 같은 <code>AddRoutineScreen</code>을 <code>compound</code> 플래그만 다르게 연다는 설명.", []),
        (14, 15, "상태가 없는 화면이라 StatelessWidget.", ["class"]),
        (17, 18, "색 상수 둘.", []),
        (20, 28, "화면 틀과 Column.", ["build", "layout"]),
        (29, 63, "<b>맨 위 줄: 뒤로가기 화살표 + 제목.</b> <code>context.pop()</code>이 쌓인 화면을 한 장 걷어냅니다. 제목 글자가 \"오늘 할 일\"인 것은 Figma 값을 그대로 복사한 것이라 이 화면 제목으로는 어색할 수 있습니다.", ["gopush"]),
        (64, 64, "33 간격.", []),
        (65, 88, "<b>선택지 카드 세 장.</b> 각각 아이콘 경로, 글자, 눌렸을 때 이동할 주소를 넘깁니다: <code>/routine/add/single</code>, <code>/routine/add/compound</code>, <code>/routine/add/templates</code>. 카드 사이 9 간격.", []),
        (89, 95, "괄호 닫기와 하단 탭바(루틴 탭 켜짐).", []),
        (97, 103, "<b>선택지 카드 위젯.</b> 아이콘, 글자, 눌림 함수(null 가능)를 받습니다.", ["voidcallback"]),
        (105, 137, "<b>알약 모양 카드.</b> 높이 88, 모서리 44, 옅은 그림자. 안에 아이콘(28×31) → 20 간격 → 글자(21). 위젯 하나를 세 번 재사용해서 세 카드가 같은 모양입니다.", ["tap"]),
    ],
    next_hint="\"단일 루틴 추가하기\"를 누르면 <code>router.dart</code> 138줄 <code>AddRoutineScreen</code> → <code>add_routine_screen.dart</code>(1,164줄, 이 앱에서 가장 큰 파일)로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/add_routine_screen.dart",
    title="루틴 추가·수정 폼 (일반·기간·반복·다중)",
    role="루틴 추가/수정 폼",
    arrive="<code>routine_type_select_screen.dart</code> 72줄 <code>context.push('/routine/add/single')</code> → <code>router.dart</code> 138줄 <code>AddRoutineScreen(...)</code>에서 왔습니다. 루틴 상세의 톱니바퀴를 누르면 <code>RoutineEditScreen</code>이 같은 폼을 \"수정\" 모드로 엽니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 10, "루틴 provider와 모델, 템플릿 provider와 모델, <b>반복 규칙 계산</b>(<code>routine_recurrence.dart</code>, 다음 정류장).", []),
        (12, 15, "문서 주석. <code>RoutineEditScreen</code>은 \"기존 루틴을 수정 모드로 여는\" 얇은 포장입니다. 라우트 빌더는 <code>ref</code>를 못 받아서 <code>ConsumerWidget</code> 한 겹이 필요하다는 이유.", []),
        (16, 19, "수정할 루틴의 id를 받는 <code>ConsumerWidget</code>.", ["consumer"]),
        (21, 29, "<b>id로 루틴을 찾아 폼에 넘깁니다.</b> 못 찾으면 안내 글자만, 찾으면 <code>AddRoutineScreen(compound: ..., editing: routine)</code>. 하위 할 일이 있으면 복합 루틴 폼으로 엽니다.", ["family"]),
        (31, 55, "<b>이 폼의 설계도(문서 주석).</b> 단일/복합은 <code>compound</code> 플래그 하나만 달라서 화면 하나로 합쳤고, <b>일반·기간·반복·다중</b> 네 탭이 어떻게 날짜를 만드는지 설명합니다. 핵심 설계: 반복 <b>규칙을 저장하지 않고</b>, \"완료\" 순간에 날짜를 전부 계산해 날짜마다 루틴을 하나씩 저장합니다. 수정 모드에서는 여러 개를 새로 만들면 원본이 남아 꼬이므로 탭을 숨깁니다.", []),
        (56, 70, "<b>입력으로 받는 값 셋.</b> <code>compound</code>(복합 여부), <code>template</code>(템플릿으로 들어왔을 때), <code>editing</code>(수정 중인 루틴). 모두 선택 인자이고 <code>editing == null</code>이면 \"추가\" 모드입니다.", ["constructor", "null"]),
        (72, 75, "State와 색 상수 셋.", []),
        (77, 81, "<b>고정 선택지 목록들.</b> 구성원(지예·예담·예소), 탭 이름, 요일, 반복 단위, 주기 단위. 구성원이 하드코딩인 것은 아직 서버 자녀 목록과 연결되지 않았기 때문입니다.", ["const"]),
        (83, 89, "<b>입력 상태의 초기값.</b> 이름 칸 컨트롤러는 \"수정 중이면 그 이름, 템플릿이면 템플릿 이름, 아니면 빈 글자\"로 시작합니다(<code>a ?? b ?? ''</code>). <code>late final</code>이라 <code>widget</code>을 쓰는 초기값이 가능합니다. 하위 할 일은 <code>List.of(...)</code>로 <b>복사본</b>을 만들어 수정해도 원본이 안 바뀝니다.", ["late", "null"]),
        (91, 100, "시작·종료 시각(기본 00:00), 선택된 구성원(<code>Set</code>, 기본 \"지예\"), 지금 탭, 저장 중 여부, 템플릿 저장 체크 여부.", ["setmap"]),
        (102, 121, "<b>탭마다 따로 가지는 상태.</b> 일반(선택 날짜 하나), 기간(시작·끝), 다중(날짜 모음 <code>Set</code>), 반복(단위, 요일 모음, 며칠, 몇 월, 주기 숫자·단위, 시작·끝). 값이 많은 이유는 네 탭이 서로의 상태를 덮어쓰지 않게 따로 들고 있기 때문입니다.", ["setmap"]),
        (123, 134, "<b><code>initState</code>.</b> 수정 중이면 그 루틴의 날짜, 아니면 오늘 날짜로 \"일반\" 날짜와 반복의 시작·며칠·몇 월을 맞춥니다.", ["stateful"]),
        (136, 141, "컨트롤러 둘 정리.", []),
        (143, 156, "<b>시간 고르기.</b> <code>showTimePicker</code>로 표준 시간 선택 팝업을 띄우고, 취소하면 <code>null</code>이라 그냥 끝냅니다. 시작/종료 중 어느 쪽인지 <code>isStart</code>로 구분해 <code>setState</code>로 저장합니다.", ["pickers", "async"]),
        (158, 166, "<b>구성원 선택 토글.</b> 이미 있으면 빼고 없으면 넣습니다(<code>Set</code>의 <code>contains/remove/add</code>).", ["setmap"]),
        (168, 175, "<b>하위 할 일 추가.</b> 입력 글자를 <code>trim()</code>(앞뒤 공백 제거)해서 비었으면 무시. <code>[..._steps, text]</code>로 <b>새 리스트</b>를 만들어 대입하고 입력 칸을 비웁니다.", ["spread"]),
        (177, 181, "하위 할 일 삭제. 복사본에서 <code>removeAt(index)</code>한 새 리스트로 교체합니다.", ["spread"]),
        (183, 189, "<b>\"이 루틴이 등록될 날짜들\"을 계산하는 함수.</b> 수정 모드는 항상 날짜 하나입니다. 비어 있으면 저장할 수 없다는 뜻입니다.", []),
        (190, 203, "<b>탭별 계산 1.</b> 일반은 선택한 날 하나. 기간은 시작부터 끝까지 하루씩 <code>while</code>로 더해 모읍니다. 다중은 찍어 둔 날짜들 그대로.", ["switchexpr"]),
        (204, 236, "<b>탭별 계산 2: 반복.</b> 단위(매주·매월·매년·주기)에 따라 <code>RoutineRecurrence</code>의 네 함수 중 하나를 불러 날짜 목록을 받습니다. 어떤 경우에도 걸리지 않으면 빈 목록.", ["switchexpr"]),
        (238, 258, "<b>\"완료\" 버튼 처리 (1) 입력 검사.</b> 이름이 비었거나, 구성원이 0명이거나, 날짜가 없으면 스낵바로 알리고 <code>return</code>합니다. 저장하기 전에 불가능한 입력을 걸러내는 전형적인 모양입니다.", []),
        (260, 268, "<b>(2) 저장할 값 준비.</b> 전원이 선택됐으면 꼬리표는 \"공통\", 아니면 \"지예, 예담님의 기기\". <code>baseId</code>는 현재 시각의 마이크로초(루틴마다 <code>'$baseId-$i'</code>로 구분). 수정 모드라면 이미 완료 표시된 구성원의 상태를 이름으로 찾아 유지하려고 <code>{ for (...) 이름: 참여자 }</code> 사전을 만듭니다.", ["setmap", "interp"]),
        (270, 271, "<b>저장 중 표시를 켜고, 쓰기 기능(<code>routineActionsProvider</code>)을 꺼냅니다.</b>", []),
        (272, 290, "<b>(3) 날짜마다 루틴 하나씩 저장.</b> 수정이면 기존 id를 그대로 써서 <b>덮어쓰고</b>, 추가면 새 id입니다. <code>DateTime(년, 월, 일, 시, 분)</code>으로 날짜와 시작 시각을 합치고, 참여자는 완료 여부를 이전 값 또는 <code>false</code>로 채웁니다. 저장마다 <code>invalidate</code>가 일어나 화면이 갱신됩니다.", ["async", "null"]),
        (292, 296, "<b>(4) 템플릿에 저장하기</b>가 켜진 복합 루틴이면 이름과 하위 할 일만 템플릿으로도 저장합니다.", []),
        (298, 302, "<b>(5) 끝내기.</b> 화면이 살아 있는지 확인하고 <code>context.go('/routine')</code>으로 달력에 돌아갑니다. 선택 화면까지 두 겹 쌓여 있어서 <code>pop</code> 대신 <code>go</code>를 쓴다고 주석이 설명합니다.", ["gopush"]),
        (304, 314, "<b>build.</b> 흰 배경, 스크롤, 아래 여백 32, <code>Column</code>.", ["build", "scroll"]),
        (315, 346, "<b>맨 위 줄: 뒤로가기 + 제목.</b> 제목은 <code>_titleForMode()</code>가 \"단일 루틴 추가하기\"/\"복합 루틴 수정하기\" 등으로 돌려줍니다.", []),
        (347, 347, "간격.", []),
        (348, 354, "<b>\"루틴 이름\"</b> 라벨. 좌우 37 여백 안의 <code>Column</code>.", ["layout"]),
        (355, 366, "<b>이름 입력 칸.</b> 알약 모양 껍데기(<code>_PillField</code>) 안의 <code>TextField</code>. 컨트롤러를 연결하고 밑줄 없는(<code>InputBorder.none</code>) 꾸밈입니다.", ["formfield"]),
        (367, 369, "\"시간 설정\" 라벨.", []),
        (370, 388, "<b>시작·종료 시간 칸 두 개</b>를 가로로. 눌리면 <code>_pickTime</code>을 시작/종료로 구분해서 부릅니다.", ["layout"]),
        (389, 391, "\"대상 선택\" 라벨.", []),
        (392, 405, "<b>구성원 칩 세 개</b>를 가로로. <code>for</code>로 돌며 첫 번째 말고는 5 간격을 먼저 넣습니다. 선택 여부는 <code>_selectedMembers.contains(member)</code>로 칩에 알려 줍니다.", ["collectionif"]),
        (406, 433, "<b>복합 루틴일 때만</b>(<code>if (widget.compound)</code>) \"행동 추가\" 입력 칸. 글자 칸 + 오른쪽 \"+\" 아이콘. 엔터(<code>onSubmitted</code>)나 + 누름이 <code>_addStep</code>을 부릅니다.", ["collectionif"]),
        (434, 474, "<b>추가된 하위 할 일 목록.</b> 번호 배지 + 글자 + 오른쪽 \"×\" 삭제 아이콘(<code>_removeStep(i)</code>). 목록이 비면 아무것도 안 그립니다.", ["collectionif"]),
        (475, 485, "간격 뒤에 회색 둥근 상자(<b>날짜 설정 영역</b>)를 엽니다.", []),
        (486, 504, "<b>탭 버튼 네 개.</b> 수정 모드(<code>editing != null</code>)에서는 숨깁니다. 누르면 <code>_activeTab</code>이 바뀌어 아래 내용이 바뀝니다.", ["collectionif"]),
        (505, 545, "<b>탭에 따라 다른 위젯을 고르는 <code>switch</code> 식.</b> 일반·기간·다중은 같은 <code>_MonthCalendar</code>를 쓰되 \"무엇을 선택된 것으로 볼지\"와 \"날짜를 누르면 무엇을 할지\"만 다르게 넘기고, 나머지(반복)는 <code>_RepeatSettings</code>에 값 20여 개와 \"값이 바뀌면 이렇게\" 함수들을 넘깁니다. 수정 모드는 항상 \"일반\"입니다.", ["switchexpr", "valuechanged"]),
        (546, 549, "괄호 닫기.", []),
        (550, 575, "<b>복합 루틴일 때만 \"템플릿에 저장하기\" 체크박스.</b> 누르면 <code>_saveAsTemplate</code>을 반대로 뒤집고(<code>!</code>), 체크 그림도 그 값으로 바뀝니다.", ["collectionif", "tap"]),
        (576, 592, "<b>\"완료\" 버튼.</b> 저장 중이면 <code>onPressed: null</code>이라 눌리지 않습니다. 누르면 위의 <code>_submit</code>.", []),
        (593, 598, "괄호 닫기.", []),
        (600, 604, "<b>제목 글자.</b> 복합/단일 × 추가/수정 네 가지.", ["arrow"]),
        (606, 607, "<b>같은 날인지 비교하는 작은 함수.</b> 연·월·일이 모두 같으면 true. <code>static</code>이라 객체 없이 쓸 수 있습니다.", []),
        (609, 613, "<b>\"기간\" 탭에서 이 날이 선택 범위 안인가.</b> 끝이 아직 없으면 시작일만, 있으면 시작 이상 끝 이하.", []),
        (615, 628, "<b>\"기간\" 탭 날짜 누르기 규칙.</b> 첫 탭은 시작일, 그보다 늦은 날을 또 누르면 끝일, 시작일보다 이른 날을 누르면 시작일을 새로 잡습니다. 끝까지 정해진 뒤 다시 누르면 새 시작일부터 다시.", []),
        (630, 639, "<b>\"다중\" 탭 날짜 누르기.</b> 이미 찍은 날이면 빼고, 아니면 추가합니다(<code>firstOrNull</code>은 없으면 null).", ["setmap"]),
        (640, 640, "State 클래스 끝.", []),
        (642, 666, "<b>알약 입력 껍데기 위젯.</b> 높이 55, 모서리 21, 옅은 그림자. 안에 무엇이든 <code>child</code>로 받아서 글자 칸과 시간 버튼이 같은 껍데기를 씁니다. <code>onTap</code>이 있으면 눌리는 <code>InkWell</code>로 감쌉니다.", ["class"]),
        (668, 693, "<b>시간 버튼.</b> \"00:00 부터\"처럼 시각과 안내 글자를 양끝에 놓습니다. 시각 글자는 앞에서 본 <code>padLeft</code> 방식.", []),
        (695, 737, "<b>구성원 칩.</b> 선택되면 채운 체크 그림, 아니면 빈 체크 그림. 높이 44, 모서리 25.", []),
        (739, 771, "<b>탭 버튼.</b> 활성이면 하늘색 배경에 흰 글자, 아니면 흰 배경에 회색 글자.", []),
        (773, 786, "<b>일반·기간·다중이 공유하는 달력.</b> 부모가 <code>isSelected</code>(이 날이 선택됐나?)와 <code>onSelectDate</code>(누르면 무엇을?)를 정해 주므로 달력 그리드 하나로 세 가지 선택 방식을 표현합니다. <code>bool Function(DateTime)</code>은 \"날짜를 받아 bool을 돌려주는 함수\"의 타입입니다.", ["valuechanged"]),
        (787, 800, "<b>그 달의 칸 계산.</b> 이번 달 일수와 1일의 요일(앞 빈 칸 수)은 루틴 화면 달력과 같은 방식입니다. 이 폼의 달력은 <b>이번 달 하나만</b> 보여줍니다(월 이동 없음).", []),
        (801, 832, "<b>날짜 칸 만들기.</b> 선택 여부를 부모에게 물어 색을 정하고(선택=흰색, 일요일=빨강, 토요일=파랑), 29×29 상자에 숫자를 놓고 선택됐으면 하늘색 원을 깝니다.", ["tap"]),
        (833, 845, "뒤 빈 칸을 채우고 7칸씩 한 주(Row)로 묶습니다.", ["maplist"]),
        (847, 871, "<b>달력 맨 위 \"10월 2026\" 제목 + 요일 헤더 + 주들.</b> 마지막 <code>...rows</code>의 <code>...</code>는 주 목록을 펼쳐서 Column의 자식으로 끼웁니다.", ["spread"]),
        (873, 900, "<b>\"반복\" 탭 위젯.</b> 단위(<code>unit</code>)에 따라 요일/며칠/몇월 며칠/주기 중 하나를 보여주고, 공통으로 시작·종료 날짜를 고릅니다. 생성자가 길어 보이지만 \"값과, 그 값이 바뀌었을 때 부를 함수\" 쌍이 반복되는 것뿐입니다.", ["constructor"]),
        (902, 929, "<b>필드 목록.</b> <code>ValueChanged&lt;int&gt;</code> 같은 타입은 \"새 값을 받아 부모에게 알리는 함수\"입니다. 이 위젯은 값을 직접 바꾸지 않고(Stateless) 부모 State가 바꿉니다.", ["valuechanged"]),
        (931, 946, "build. 첫 줄은 \"반복 기간\" 설정 행과 단위 드롭다운, 12 간격. 그 아래 <code>switch (unit)</code>이 시작됩니다.", ["build"]),
        (947, 958, "<b>'매주'.</b> 요일 동그라미 7개를 <code>Wrap</code>으로 나열. 눌리면 <code>onToggleWeekday(i)</code>.", ["switchexpr"]),
        (959, 967, "<b>'매월'.</b> \"매월 며칠\" 행과 1~31일 드롭다운.", []),
        (968, 988, "<b>'매년'.</b> 월 드롭다운(1~12)과 일 드롭다운(1~31)을 가로로 나란히.", []),
        (989, 1010, "<b>그 외 = '주기'.</b> \"N + 일/주/개월마다\" 두 드롭다운을 나란히. 숫자는 1~30. <code>_</code>는 위의 세 경우가 아닌 나머지 전부입니다.", ["switchexpr"]),
        (1011, 1026, "<b>\"시작 날짜\"</b> 행. 누르면 <code>showDatePicker</code>로 표준 날짜 선택 팝업을 띄워(전후 1년·5년 범위) 고른 날짜를 부모에게 알립니다. 취소하면 <code>null</code>이라 무시합니다.", ["pickers"]),
        (1027, 1048, "<b>\"종료 날짜\"</b> 행. 비워 두면 \"없음\"이고, 값이 있으면 \"×\"로 지웁니다. 끝을 안 정하면 무한 반복이 되므로 실제로는 1년·개수 제한까지만 만들어진다고 위 문서 주석이 알려 줍니다.", ["pickers"]),
        (1050, 1066, "<b>\"라벨 ····· 오른쪽 위젯\"</b> 한 줄 위젯. 양끝 정렬(<code>spaceBetween</code>).", []),
        (1068, 1096, "<b>범용 드롭다운 <code>_Dropdown&lt;T&gt;</code>.</b> <code>T</code>가 int여도 String이어도 쓰는 제네릭 위젯입니다. 선택지 목록, \"선택지를 글자로 바꾸는 함수\"(<code>labelOf</code>), 바뀌면 부를 함수를 받습니다.", ["valuechanged", "arrow"]),
        (1098, 1130, "<b>날짜 버튼.</b> 값이 없으면 안내 글자(\"없음\"/\"선택\"), 있으면 \"2026년 10월 5일\". 지우기 함수가 주어졌을 때만 \"×\"를 그립니다.", ["collectionif", "null"]),
        (1132, 1164, "<b>요일 동그라미 하나.</b> 32×32 원, 선택되면 하늘색. 이 파일 끝. 다음은 이 폼이 \"반복\"의 날짜를 계산하는 데 쓰는 <code>routine_recurrence.dart</code>입니다.", []),
    ],
    next_hint="6~10줄 <code>routine_recurrence.dart</code>의 <code>RoutineRecurrence</code>를 Ctrl+클릭합니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/domain/routine_recurrence.dart",
    title="\"매주 월·수\"를 날짜 목록으로 펼치기",
    role="반복 날짜 계산",
    arrive="<code>add_routine_screen.dart</code> 207·213·219·226줄 <code>RoutineRecurrence.weekly/monthly/yearly/interval(...)</code>에서 왔습니다.",
    chunks=[
        (1, 2, "<b><code>enum</code>.</b> 정해진 값 몇 개 중 하나만 가능한 타입입니다(<code>weekly</code>, <code>monthly</code>, <code>yearly</code>, <code>interval</code>).", []),
        (4, 15, "문서 주석. <b>반복 규칙 자체는 저장하지 않습니다.</b> 저장·조회가 \"특정 날짜의 루틴\"만 알면 되게 이미 짜여 있어서, 저장하는 시점에 날짜별 <code>Routine</code>을 미리 여러 개 만드는 쪽이 간단하다는 설계 이유. 끝 날짜가 없으면 무한 반복이 되니 기간(1년)과 최대 개수로 제한합니다. 객체를 만들지 않는 <b>순수 함수 모음</b>이라 <code>static</code> 함수만 있습니다.", []),
        (16, 22, "<b>매주.</b> 시작일, 요일 번호 모음(<code>Set&lt;int&gt;</code>, 0=일…6=토), 끝날짜, 범위(365일), 최대 200개를 받습니다. 인자 뒤의 <code>= 365</code>는 기본값.", ["constructor", "setmap"]),
        (23, 32, "요일을 하나도 안 골랐으면 빈 목록. 아니면 <b>시작일부터 하루씩 더해 가며</b> 그 요일이면 모읍니다. 끝날짜가 없으면 <code>시작 + 365일</code>이 한계입니다. <code>day.weekday % 7</code>은 Dart의 일=7을 0으로 맞춥니다.", []),
        (34, 40, "<b>매달 N일.</b> 시작일, 며칠, 끝, 범위, 최대 60개.", []),
        (41, 58, "달을 한 칸씩 넘기며 N일을 만들되 그 달의 말일(<code>DateTime(년, 월+1, 0).day</code> — 0일은 \"전달 말일\")을 넘으면 <code>clamp(1, 말일)</code>로 잘라 31일이 없는 달은 말일로 둡니다. 시작일 이전이나 끝 이후는 제외합니다.", []),
        (60, 78, "<b>매년.</b> 몇 월 며칠을 해마다 만듭니다. 시작일 이전은 건너뛰고 끝날짜를 넘으면 <code>break</code>로 반복을 끝냅니다. 최대 20년.", []),
        (80, 102, "<b>주기(N일·주·개월마다).</b> 한 번 모은 뒤 <code>switch</code> 식으로 다음 날짜를 정합니다: 주 → <code>7 × N</code>일 뒤, 개월 → 월에 N을 더한 날, 나머지(일) → N일 뒤. 첫 날짜도 포함됩니다.", ["switchexpr"]),
        (103, 103, "클래스 끝.", []),
    ],
    next_hint="<code>add_routine_screen.dart</code>의 \"템플릿에 저장하기\"가 만든 템플릿을 쓰는 쪽, <code>routine_template_providers.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/data/routine_template_providers.dart",
    title="저장해 둔 템플릿 목록과 저장",
    role="템플릿 provider",
    arrive="<code>add_routine_screen.dart</code> 293줄 <code>ref.read(routineTemplateActionsProvider).addTemplate(...)</code>에서 왔습니다.",
    chunks=[
        (1, 5, "Riverpod, 템플릿 모델, 루틴 provider(<code>localStorageServiceProvider</code>를 재사용), 템플릿 저장소.", []),
        (7, 9, "템플릿 저장소 provider. Hive <code>'routine_templates'</code> 상자를 씁니다. 루틴 저장소와 이름만 다른 같은 틀(<code>routine_template_repository.dart</code>, <code>routine_template.dart</code>도 <code>routine_repository.dart</code>·<code>routine.dart</code>와 같은 모양이라 따로 읽지 않습니다).", ["provider"]),
        (11, 13, "템플릿 목록 provider.", ["asyncvalue"]),
        (15, 15, "쓰기 기능 provider.", []),
        (17, 26, "<b>템플릿 추가 = 저장 + 목록 invalidate.</b> 기기·루틴과 똑같은 패턴이 세 번째 나옵니다. 이 패턴을 알아보면 이 앱의 \"저장 흐름\"이 전부 같다는 것이 보입니다.", ["invalidate"]),
    ],
    next_hint="템플릿 목록을 보여주는 <code>routine_template_list_screen.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_template_list_screen.dart",
    title="템플릿 사용: 고르면 폼이 미리 채워진다",
    role="템플릿 목록 화면",
    arrive="<code>routine_type_select_screen.dart</code> 84줄 <code>context.push('/routine/add/templates')</code> → <code>router.dart</code> 150줄 <code>RoutineTemplateListScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 7, "Flutter 위젯, Riverpod, SVG, 화면 이동, 템플릿 provider와 모델.", []),
        (9, 15, "문서 주석. 템플릿을 고르면 단일 루틴 폼으로 가면서 <b>이름과 하위 할 일만</b> 미리 채워 줍니다. 시간·대상·날짜는 매번 다르므로 담지 않습니다.", []),
        (16, 17, "provider만 읽는 <code>ConsumerWidget</code>.", ["consumer"]),
        (19, 20, "색 상수 둘.", []),
        (22, 24, "템플릿 목록 읽기(없으면 빈 리스트).", ["asyncvalue", "build"]),
        (26, 32, "화면 틀과 Column.", ["layout"]),
        (33, 60, "<b>뒤로가기 화살표 + \"템플릿 사용\" 제목 줄.</b> 앞의 유형 선택 화면과 같은 모양입니다(같은 코드가 화면마다 복붙돼 있습니다).", []),
        (61, 61, "간격.", []),
        (62, 81, "<b>비었으면 안내 글자, 있으면 <code>ListView.separated</code>.</b> 안내는 \"저장된 템플릿이 없어요 — 루틴을 추가할 때 '템플릿에 저장하기'를 켜면 여기에 모여요\". <code>Expanded</code> 안에 넣어 남는 세로 공간을 목록이 쓰게 합니다.", ["listview"]),
        (82, 87, "괄호 닫기.", []),
        (89, 92, "<b>템플릿 카드 위젯.</b>", []),
        (94, 107, "<b>누르면 <code>context.push('/routine/add/single', extra: template)</code>.</b> <code>extra</code>는 주소에 안 들어가는 <b>덤 데이터</b>를 다음 화면에 실어 보내는 go_router 기능입니다. <code>router.dart</code>가 <code>state.extra as RoutineTemplate?</code>로 받아 폼에 넘깁니다. 이하는 흰 둥근 카드 꾸밈.", ["gopush"]),
        (108, 132, "<b>첫 줄: 템플릿 이름 + 오른쪽 \">\".</b>", []),
        (133, 168, "<b>하위 할 일이 있으면 번호 배지 + 글자 줄들.</b> 루틴 카드의 단계 줄과 같은 모양을 한 번 더 직접 그렸습니다(공용 위젯으로 뺄 수 있는 중복).", ["collectionif"]),
        (169, 174, "괄호 닫기.", []),
    ],
    next_hint="오른쪽 위 \"+\" 쪽으로 돌아가서, 달력 목록의 맨 아래를 당기면 가는 <code>today_routines_screen.dart</code>를 봅니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/today_routines_screen.dart",
    title="오늘 할 일: 위로 당기면 달력으로",
    role="오늘 할 일 목록",
    arrive="<code>routine_screen.dart</code> 116줄 <code>context.push('/routine/today')</code> → <code>router.dart</code> 107줄 <code>TodayRoutinesScreen()</code>에서 왔습니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 9, "하단 탭바, 루틴 provider, <b>+ 버튼과 카드 목록</b>(달력 화면과 같은 위젯을 재사용).", []),
        (11, 22, "문서 주석. 달력 화면과 <b>대칭</b>입니다. 거기서는 맨 아래를 넘어 당기면 이 화면으로 오고, 여기서는 맨 위를 넘어 당기거나 위쪽 화살표를 누르면 돌아갑니다. + 버튼 위치 상수를 같게 쓴 이유도 적혀 있습니다.", []),
        (23, 24, "Stateful + <code>ref</code>가 필요한 <code>ConsumerStatefulWidget</code>.", ["stateful"]),
        (26, 29, "State 연결.", []),
        (31, 32, "State 클래스와 배경색.", []),
        (34, 36, "달력 화면과 같은 값 60(px).", ["const"]),
        (38, 43, "<b>\"한 번만 pop\" 깃발.</b> 화살표 탭과 위로 당기는 알림이 거의 동시에 오면 <code>pop</code>이 두 번 불려 스택이 꼬일 수 있어서 막는다는 설명.", []),
        (45, 49, "<b>뒤로 가기.</b> 이미 한 번 불렸으면 무시하고, 아니면 깃발을 세운 뒤 <code>context.pop()</code>.", ["gopush"]),
        (51, 63, "<b>스크롤 알림 처리(맨 위 버전).</b> 맨 위(<code>minScrollExtent</code>)를 넘어 더 당긴 거리가 60을 넘으면 <code>_goBack()</code>. 달력 화면의 함수와 부호만 반대입니다.", []),
        (65, 69, "build. <b>오늘 날짜의 루틴 목록</b>을 읽습니다(날짜는 시·분·초를 뺀 0시로).", ["build", "family"]),
        (71, 79, "<code>Stack</code>으로 본문과 고정 + 버튼을 겹칩니다. 주석은 <code>Positioned.fill</code>이 필요한 이유(루틴이 하나뿐일 때 버튼이 짧은 내용 밑에 붙는 문제)입니다.", ["layout"]),
        (80, 91, "<code>SafeArea</code> → <code>NotificationListener</code> → <code>SingleChildScrollView</code>. 위로 당김도 감지하려면 항상 당길 수 있게 + 살짝 튕기는 물리가 필요합니다.", ["scroll"]),
        (92, 103, "<b>Column: 제목 줄 → 간격 → 카드 목록.</b> 제목 줄에 <code>onBack: _goBack</code>을 연결합니다. 카드 목록은 달력 화면과 같은 <code>RoutineCardList</code>.", []),
        (104, 120, "닫기, <b>고정 + 버튼</b>, 하단 탭바(<code>currentIndex: 1</code>).", []),
        (122, 128, "<b>\"^ 오늘 할 일\" 제목 줄 위젯.</b> 위로 당겨도 같은 곳으로 돌아가므로 화살표도 위를 가리킵니다.", []),
        (130, 165, "화살표 아이콘(원본이 이미 위쪽이라 돌릴 필요 없음)과 \"오늘 할 일\" 글자. 주석에 \"왼쪽 화살표였을 때는 반시계 90도 돌렸었다\"는 이력이 있습니다.", ["tap"]),
    ],
    next_hint="카드를 눌러 가는 <code>routine_detail_screen.dart</code>로 갑니다(<code>routine_card.dart</code> 36줄 <code>/routine/detail/:id</code>).",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/features/routine/presentation/routine_detail_screen.dart",
    title="루틴 상세: 누가 했나",
    role="루틴 상세 (/routine/detail/:id)",
    arrive="<code>routine_card.dart</code> 36줄 <code>context.push('/routine/detail/${routine.id}')</code> → <code>router.dart</code> 118줄 <code>RoutineDetailScreen(routineId: ...)</code>에서 왔습니다. <code>state.pathParameters['id']!</code>가 주소 속 id입니다.",
    chunks=[
        (1, 4, "Flutter 위젯, Riverpod, SVG, 화면 이동.", []),
        (6, 9, "하단 탭바, <b>원형 진행률 위젯</b>(<code>progress_ring.dart</code>, 다음 정류장), 루틴 provider, 루틴 모델.", []),
        (11, 18, "문서 주석. 이 루틴을 하는 가족 구성원의 완료 현황을 \"원형 진행률 + 완료/미완료 아바타\"로 보여줍니다. 화면 전체가 이미 스크롤이라 아바타가 많아도 따로 처리할 것이 없습니다.", []),
        (19, 25, "<b>루틴 id를 받는 <code>ConsumerWidget</code>.</b> <code>routineId</code>는 주소에서 온 값입니다.", ["consumer"]),
        (27, 29, "<b>id로 루틴 찾기.</b> <code>routineByIdProvider(routineId)</code>로 읽습니다. 없으면 <code>null</code>.", ["family", "build"]),
        (31, 39, "화면 틀. <b>루틴이 없으면(<code>routine == null</code>) \"루틴을 찾을 수 없어요\".</b> 잘못된 id나 그 사이 삭제된 경우를 대비한 방어 코드라고 주석이 설명합니다. <code>조건 ? A : B</code>가 body 전체를 고릅니다.", ["null"]),
        (40, 50, "있으면 스크롤 영역 안 <code>Column</code>. 첫 줄은 헤더: 뒤로가기(<code>pop</code>)와 설정 톱니바퀴(<code>push('/routine/edit/$routineId')</code> → 수정 폼).", ["gopush", "interp"]),
        (51, 55, "32 간격 뒤에 <b>진행률 카드</b>(제목 + 원형 진행률 + 인원).", []),
        (56, 65, "<b>\"완료\" 구역.</b> 참여자 중 <code>completed</code>가 true인 사람만 <code>.where(...).toList()</code>로 걸러 넘깁니다.", ["maplist"]),
        (66, 75, "<b>\"미완료\" 구역.</b> 같은 방법으로 <code>!p.completed</code>인 사람.", []),
        (76, 84, "아래 여백 120과 하단 탭바(루틴 탭 켜짐).", []),
        (86, 91, "<b>헤더 위젯.</b> 뒤로가기 함수와 수정 함수를 부모에게서 받습니다.", ["voidcallback"]),
        (93, 118, "뒤로가기 화살표. 원본이 위(^)를 향하므로 <code>quarterTurns: 3</code>(왼쪽)으로 돌렸다는 주석이 있습니다.", []),
        (119, 127, "\"오늘 할 일\" 글자(Figma 값 그대로).", []),
        (128, 142, "<b>톱니바퀴.</b> <code>Spacer()</code>로 오른쪽 끝에 밀고 누르면 <code>onEdit</code>. 기기 관리 화면에 있는 것과 같은 아이콘입니다.", ["tap"]),
        (143, 146, "괄호 닫기.", []),
        (148, 153, "<b>진행률 카드 위젯.</b> 루틴 하나를 받습니다.", []),
        (155, 160, "<b>비율 계산.</b> 전체 인원, 완료 인원, 비율(<code>completed / total</code>, 0명이면 0.0으로 0 나누기를 피함), 백분율(<code>(ratio * 100).round()</code>).", []),
        (162, 172, "흰 카드 상자(홈 카드와 같은 꾸밈)와 <code>Column</code>.", []),
        (173, 192, "<b>루틴 제목 → 32 간격 → <code>ProgressRing</code>.</b> 링 가운데에 \"N%\" 글자를 <code>center</code>로 얹습니다.", ["interp"]),
        (193, 206, "<b>\"완료수/전체수\"</b> 큰 숫자(<code>'$completed/$total'</code>).", ["interp"]),
        (208, 215, "<b>\"완료\" 또는 \"미완료\" 구역 위젯.</b> 소제목과 그 상태인 구성원 목록을 받습니다.", []),
        (217, 219, "<b>아무도 없으면 아예 안 그립니다</b>(<code>SizedBox.shrink()</code>를 돌려줌).", []),
        (221, 243, "소제목 + 16 간격 + <code>Wrap</code>(줄이 차면 아래로 넘어감) 안에 <code>for</code>로 구성원마다 아바타 칩.", ["collectionif"]),
        (245, 252, "<b>구성원 아바타 칩 위젯.</b> 이름만 받습니다. 세 자녀(지예·예담·예소)는 Figma에서 색이 정해져 있어 이름으로 아이콘을 고른다는 설명.", []),
        (254, 282, "96×94 흰 카드 안에 이름에 맞는 로봇 그림(48×50)과 이름 글자.", []),
        (284, 296, "<b>이름 → 그림 경로를 고르는 <code>switch</code> 문장.</b> 알려진 세 이름은 색별 그림, 그 외는 회색 기본값(<code>default</code>). <code>static</code> 함수라 위젯 객체 없이 쓰입니다.", ["switchexpr"]),
    ],
    next_hint="<code>ProgressRing</code>을 Ctrl+클릭해 <code>progress_ring.dart</code>로 갑니다.",
))

STOPS_CH.append(dict(
    chapter=4,
    file="lib/app/widgets/progress_ring.dart",
    title="직접 그리는 원형 진행률",
    role="원형 게이지",
    arrive="<code>routine_detail_screen.dart</code> 182줄 <code>ProgressRing(ratio: ..., center: ...)</code>에서 왔습니다. 기기 통계 화면도 같은 위젯을 씁니다.",
    chunks=[
        (1, 3, "<code>dart:math</code>(원주율 <code>math.pi</code> 등), Flutter 위젯.", []),
        (5, 10, "문서 주석. Figma 원본은 66% 상태 이미지 하나뿐이라 <b>비율이 바뀌는 화면에는 못 써서</b> 직접 그린다는 이유. 회색 트랙 위에 파란 호를 12시 방향에서 시계 방향으로 비율만큼 그립니다.", []),
        (11, 16, "<b>비율(0.0~1.0), 가운데 위젯, 지름(기본 200)</b>을 받는 위젯.", ["constructor"]),
        (18, 35, "<code>Stack</code>으로 <b>그림(<code>CustomPaint</code>)과 가운데 글자를 겹칩니다.</b> 지름 크기의 정사각형 안에서 가운데 정렬.", ["layout", "build"]),
        (37, 40, "<b>실제로 그리는 클래스.</b> <code>CustomPainter</code>를 상속하고 비율을 받습니다.", ["painter"]),
        (42, 44, "트랙 회색, 진행 하늘색, 선 굵기 18.", ["const"]),
        (46, 57, "<b>트랙(바탕 원) 그리기.</b> 반지름은 \"짧은 변 − 선 굵기\"의 절반(선이 상자 밖으로 안 나가게). <code>Paint()</code>에 <code>..color = ..</code>처럼 <code>..</code>로 속성을 이어 적고, 끝을 둥글게(<code>StrokeCap.round</code>) 해서 <code>drawCircle</code>.", ["painter"]),
        (59, 73, "<b>진행 호 그리기.</b> 비율이 0 이하면 여기서 끝. 아니면 <code>drawArc</code>로 -90°(12시)부터 <code>2π × ratio</code>만큼(360° 최대) 그립니다. <code>clamp(0.0, 1.0)</code>은 범위를 벗어난 값을 잘라 줍니다.", ["painter"]),
        (75, 78, "<b>다시 그릴지 판단.</b> 비율이 바뀌었을 때만 다시 그려 불필요한 작업을 줄입니다. 4장 끝.", ["arrow"]),
    ],
    next_hint="4장 끝. 5장에서 프로필 탭(하단 탭 3번)과 계정 화면들을 읽습니다.",
))
